import type { EmojiEntry } from './types.js';

export const activities: EmojiEntry[] = [
	{ emoji: '⚽', name: 'soccer ball football' },
	{ emoji: '🏀', name: 'basketball' },
	{ emoji: '🏈', name: 'american football' },
	{ emoji: '⚾', name: 'baseball' },
	{ emoji: '🥎', name: 'softball' },
	{ emoji: '🎾', name: 'tennis' },
	{ emoji: '🏐', name: 'volleyball' },
	{ emoji: '🏉', name: 'rugby football' },
	{ emoji: '🥏', name: 'flying disc frisbee' },
	{ emoji: '🎱', name: 'pool billiards' },
	{ emoji: '🪀', name: 'yoyo' },
	{ emoji: '🏓', name: 'ping pong table tennis' },
	{ emoji: '🏸', name: 'badminton' },
	{ emoji: '🏒', name: 'ice hockey' },
	{ emoji: '🏑', name: 'field hockey' },
	{ emoji: '🥍', name: 'lacrosse' },
	{ emoji: '🏏', name: 'cricket game' },
	{ emoji: '🪃', name: 'boomerang' },
	{ emoji: '🥅', name: 'goal net' },
	{ emoji: '⛳', name: 'flag hole golf' },
	{ emoji: '🪁', name: 'kite' },
	{ emoji: '🏹', name: 'bow arrow archery' },
	{ emoji: '🎣', name: 'fishing pole' },
	{ emoji: '🤿', name: 'diving mask snorkel' },
	{ emoji: '🥊', name: 'boxing glove' },
	{ emoji: '🥋', name: 'martial arts uniform' },
	{ emoji: '🎽', name: 'running shirt' },
	{ emoji: '🛹', name: 'skateboard' },
	{ emoji: '🛼', name: 'roller skate' },
	{ emoji: '🛷', name: 'sled' },
	{ emoji: '⛸️', name: 'ice skate' },
	{ emoji: '🥌', name: 'curling stone' },
	{ emoji: '🎿', name: 'skis skiing' },
	{ emoji: '⛷️', name: 'skier' },
	{ emoji: '🏂', name: 'snowboarder' },
	{ emoji: '🪂', name: 'parachute' },
	{ emoji: '🏋️', name: 'person lifting weights gym' },
	{ emoji: '🤼', name: 'people wrestling' },
	{ emoji: '🤸', name: 'person cartwheeling gymnastics' },
	{ emoji: '🤺', name: 'person fencing' },
	{ emoji: '⛹️', name: 'person bouncing ball' },
	{ emoji: '🤾', name: 'person playing handball' },
	{ emoji: '🏌️', name: 'person golfing' },
	{ emoji: '🏇', name: 'horse racing jockey' },
	{ emoji: '🧘', name: 'person lotus position yoga' },
	{ emoji: '🏄', name: 'person surfing' },
	{ emoji: '🏊', name: 'person swimming' },
	{ emoji: '🤽', name: 'person playing water polo' },
	{ emoji: '🚣', name: 'person rowing boat' },
	{ emoji: '🧗', name: 'person climbing' },
	{ emoji: '🚵', name: 'person mountain biking' },
	{ emoji: '🚴', name: 'person biking cycling' },
	{ emoji: '🏆', name: 'trophy winner cup' },
	{ emoji: '🥇', name: 'first place medal gold' },
	{ emoji: '🥈', name: 'second place medal silver' },
	{ emoji: '🥉', name: 'third place medal bronze' },
	{ emoji: '🏅', name: 'sports medal' },
	{ emoji: '🎖️', name: 'military medal' },
	{ emoji: '🏵️', name: 'rosette' },
	{ emoji: '🎗️', name: 'reminder ribbon' },
	{ emoji: '🎫', name: 'ticket' },
	{ emoji: '🎟️', name: 'admission tickets' },
	{ emoji: '🎪', name: 'circus tent' },
	{ emoji: '🎭', name: 'performing arts theater masks' },
	{ emoji: '🎨', name: 'artist palette paint' },
	{ emoji: '🎬', name: 'clapper board movie film' },
	{ emoji: '🎤', name: 'microphone karaoke' },
	{ emoji: '🎧', name: 'headphone music' },
	{ emoji: '🎼', name: 'musical score' },
	{ emoji: '🎹', name: 'musical keyboard piano' },
	{ emoji: '🥁', name: 'drum' },
	{ emoji: '🪘', name: 'long drum' },
	{ emoji: '🎷', name: 'saxophone' },
	{ emoji: '🎺', name: 'trumpet' },
	{ emoji: '🪗', name: 'accordion' },
	{ emoji: '🎸', name: 'guitar' },
	{ emoji: '🪕', name: 'banjo' },
	{ emoji: '🎻', name: 'violin' },
	{ emoji: '🪈', name: 'flute' },
	{ emoji: '🎲', name: 'game die dice' },
	{ emoji: '♟️', name: 'chess pawn' },
	{ emoji: '🎯', name: 'bullseye target dart' },
	{ emoji: '🎳', name: 'bowling' },
	{ emoji: '🎮', name: 'video game controller' },
	{ emoji: '🕹️', name: 'joystick arcade' },
	{ emoji: '🎰', name: 'slot machine casino' },
];
