import type { EmojiEntry } from './types.js';

export const animals: EmojiEntry[] = [
	{ emoji: '🐶', name: 'dog face puppy' },
	{ emoji: '🐱', name: 'cat face kitten' },
	{ emoji: '🐭', name: 'mouse face' },
	{ emoji: '🐹', name: 'hamster face' },
	{ emoji: '🐰', name: 'rabbit face bunny' },
	{ emoji: '🦊', name: 'fox face' },
	{ emoji: '🐻', name: 'bear face' },
	{ emoji: '🐼', name: 'panda face' },
	{ emoji: '🐻‍❄️', name: 'polar bear' },
	{ emoji: '🐨', name: 'koala' },
	{ emoji: '🐯', name: 'tiger face' },
	{ emoji: '🦁', name: 'lion face' },
	{ emoji: '🐮', name: 'cow face' },
	{ emoji: '🐷', name: 'pig face' },
	{ emoji: '🐸', name: 'frog face' },
	{ emoji: '🐵', name: 'monkey face' },
	{ emoji: '🙈', name: 'see no evil monkey' },
	{ emoji: '🙉', name: 'hear no evil monkey' },
	{ emoji: '🙊', name: 'speak no evil monkey' },
	{ emoji: '🐒', name: 'monkey' },
	{ emoji: '🐔', name: 'chicken' },
	{ emoji: '🐧', name: 'penguin' },
	{ emoji: '🐦', name: 'bird' },
	{ emoji: '🐤', name: 'baby chick' },
	{ emoji: '🐣', name: 'hatching chick' },
	{ emoji: '🐥', name: 'front facing baby chick' },
	{ emoji: '🦆', name: 'duck' },
	{ emoji: '🦅', name: 'eagle' },
	{ emoji: '🦉', name: 'owl' },
	{ emoji: '🦇', name: 'bat' },
	{ emoji: '🐺', name: 'wolf' },
	{ emoji: '🐗', name: 'boar' },
	{ emoji: '🐴', name: 'horse face' },
	{ emoji: '🦄', name: 'unicorn' },
	{ emoji: '🐝', name: 'honeybee bee' },
	{ emoji: '🪱', name: 'worm' },
	{ emoji: '🐛', name: 'bug caterpillar' },
	{ emoji: '🦋', name: 'butterfly' },
	{ emoji: '🐌', name: 'snail' },
	{ emoji: '🐞', name: 'lady beetle ladybug' },
	{ emoji: '🐜', name: 'ant' },
	{ emoji: '🪰', name: 'fly' },
	{ emoji: '🪲', name: 'beetle' },
	{ emoji: '🪳', name: 'cockroach' },
	{ emoji: '🦟', name: 'mosquito' },
	{ emoji: '🦗', name: 'cricket' },
	{ emoji: '🕷️', name: 'spider' },
	{ emoji: '🦂', name: 'scorpion' },
	{ emoji: '🐢', name: 'turtle tortoise' },
	{ emoji: '🐍', name: 'snake' },
	{ emoji: '🦎', name: 'lizard' },
	{ emoji: '🦖', name: 'trex dinosaur' },
	{ emoji: '🦕', name: 'sauropod dinosaur' },
	{ emoji: '🐙', name: 'octopus' },
	{ emoji: '🦑', name: 'squid' },
	{ emoji: '🦐', name: 'shrimp' },
	{ emoji: '🦞', name: 'lobster' },
	{ emoji: '🦀', name: 'crab' },
	{ emoji: '🐡', name: 'blowfish pufferfish' },
	{ emoji: '🐠', name: 'tropical fish' },
	{ emoji: '🐟', name: 'fish' },
	{ emoji: '🐬', name: 'dolphin' },
	{ emoji: '🐳', name: 'spouting whale' },
	{ emoji: '🐋', name: 'whale' },
	{ emoji: '🦈', name: 'shark' },
	{ emoji: '🐊', name: 'crocodile alligator' },
	{ emoji: '🐅', name: 'tiger' },
	{ emoji: '🐆', name: 'leopard' },
	{ emoji: '🦓', name: 'zebra' },
	{ emoji: '🦍', name: 'gorilla' },
	{ emoji: '🦧', name: 'orangutan' },
	{ emoji: '🐘', name: 'elephant' },
	{ emoji: '🦛', name: 'hippopotamus hippo' },
	{ emoji: '🦏', name: 'rhinoceros rhino' },
	{ emoji: '🐪', name: 'camel dromedary' },
	{ emoji: '🐫', name: 'two hump camel' },
	{ emoji: '🦒', name: 'giraffe' },
	{ emoji: '🦘', name: 'kangaroo' },
	{ emoji: '🦬', name: 'bison buffalo' },
	{ emoji: '🐃', name: 'water buffalo' },
	{ emoji: '🐂', name: 'ox' },
	{ emoji: '🐄', name: 'cow' },
	{ emoji: '🐎', name: 'horse racing' },
	{ emoji: '🐖', name: 'pig' },
	{ emoji: '🐏', name: 'ram sheep' },
	{ emoji: '🐑', name: 'ewe sheep' },
	{ emoji: '🦙', name: 'llama alpaca' },
	{ emoji: '🐐', name: 'goat' },
	{ emoji: '🦌', name: 'deer' },
	{ emoji: '🐕', name: 'dog' },
	{ emoji: '🐩', name: 'poodle dog' },
	{ emoji: '🦮', name: 'guide dog' },
	{ emoji: '🐕‍🦺', name: 'service dog' },
	{ emoji: '🐈', name: 'cat' },
	{ emoji: '🐈‍⬛', name: 'black cat' },
	{ emoji: '🪶', name: 'feather' },
	{ emoji: '🐓', name: 'rooster' },
	{ emoji: '🦃', name: 'turkey' },
	{ emoji: '🦤', name: 'dodo' },
	{ emoji: '🦚', name: 'peacock' },
	{ emoji: '🦜', name: 'parrot' },
	{ emoji: '🦢', name: 'swan' },
	{ emoji: '🦩', name: 'flamingo' },
	{ emoji: '🕊️', name: 'dove peace' },
	{ emoji: '🐇', name: 'rabbit' },
	{ emoji: '🦝', name: 'raccoon' },
	{ emoji: '🦨', name: 'skunk' },
	{ emoji: '🦡', name: 'badger' },
	{ emoji: '🦫', name: 'beaver' },
	{ emoji: '🦦', name: 'otter' },
	{ emoji: '🦥', name: 'sloth' },
	{ emoji: '🐁', name: 'mouse' },
	{ emoji: '🐀', name: 'rat' },
	{ emoji: '🐿️', name: 'chipmunk squirrel' },
	{ emoji: '🦔', name: 'hedgehog' },
];
