import type { EmojiEntry } from './types.js';

export const faces: EmojiEntry[] = [
	{ emoji: '😀', name: 'grinning face' },
	{ emoji: '😃', name: 'grinning face big eyes' },
	{ emoji: '😄', name: 'grinning face smiling eyes' },
	{ emoji: '😁', name: 'beaming face' },
	{ emoji: '😆', name: 'grinning squinting face' },
	{ emoji: '😅', name: 'grinning face sweat' },
	{ emoji: '🤣', name: 'rolling on floor laughing' },
	{ emoji: '😂', name: 'face tears joy' },
	{ emoji: '🙂', name: 'slightly smiling face' },
	{ emoji: '🙃', name: 'upside down face' },
	{ emoji: '😉', name: 'winking face' },
	{ emoji: '😊', name: 'smiling face blushing' },
	{ emoji: '😇', name: 'smiling face halo angel' },
	{ emoji: '🥰', name: 'smiling face hearts love' },
	{ emoji: '😍', name: 'heart eyes love' },
	{ emoji: '🤩', name: 'star struck excited' },
	{ emoji: '😘', name: 'face blowing kiss' },
	{ emoji: '😗', name: 'kissing face' },
	{ emoji: '😚', name: 'kissing face closed eyes' },
	{ emoji: '😙', name: 'kissing face smiling eyes' },
	{ emoji: '🥲', name: 'smiling face tear' },
	{ emoji: '😋', name: 'face savoring food yummy' },
	{ emoji: '😛', name: 'face tongue' },
	{ emoji: '😜', name: 'winking face tongue' },
	{ emoji: '🤪', name: 'zany face crazy' },
	{ emoji: '😝', name: 'squinting face tongue' },
	{ emoji: '🤑', name: 'money mouth face' },
	{ emoji: '🤗', name: 'hugging face' },
	{ emoji: '🤭', name: 'face hand over mouth giggle' },
	{ emoji: '🫢', name: 'face open eyes hand over mouth' },
	{ emoji: '🤫', name: 'shushing face quiet' },
	{ emoji: '🤔', name: 'thinking face' },
	{ emoji: '🫡', name: 'saluting face' },
	{ emoji: '🤐', name: 'zipper mouth face' },
	{ emoji: '🤨', name: 'face raised eyebrow' },
	{ emoji: '😐', name: 'neutral face' },
	{ emoji: '😑', name: 'expressionless face' },
	{ emoji: '😶', name: 'face without mouth' },
	{ emoji: '🫥', name: 'dotted line face' },
	{ emoji: '😏', name: 'smirking face' },
	{ emoji: '😒', name: 'unamused face' },
	{ emoji: '🙄', name: 'face rolling eyes' },
	{ emoji: '😬', name: 'grimacing face' },
	{ emoji: '🤥', name: 'lying face pinocchio' },
	{ emoji: '😌', name: 'relieved face' },
	{ emoji: '😔', name: 'pensive face sad' },
	{ emoji: '😪', name: 'sleepy face' },
	{ emoji: '🤤', name: 'drooling face' },
	{ emoji: '😴', name: 'sleeping face zzz' },
	{ emoji: '😷', name: 'face medical mask sick' },
	{ emoji: '🤒', name: 'face thermometer fever' },
	{ emoji: '🤕', name: 'face head bandage hurt' },
	{ emoji: '🤢', name: 'nauseated face sick' },
	{ emoji: '🤮', name: 'face vomiting' },
	{ emoji: '🥵', name: 'hot face' },
	{ emoji: '🥶', name: 'cold face freezing' },
	{ emoji: '🥴', name: 'woozy face drunk' },
	{ emoji: '😵', name: 'face crossed out eyes dizzy' },
	{ emoji: '🤯', name: 'exploding head mind blown' },
	{ emoji: '🤠', name: 'cowboy hat face' },
	{ emoji: '🥳', name: 'partying face celebration' },
	{ emoji: '🥸', name: 'disguised face' },
	{ emoji: '😎', name: 'smiling face sunglasses cool' },
	{ emoji: '🤓', name: 'nerd face glasses' },
	{ emoji: '🧐', name: 'face monocle' },
	{ emoji: '😕', name: 'confused face' },
	{ emoji: '🫤', name: 'face diagonal mouth' },
	{ emoji: '😟', name: 'worried face' },
	{ emoji: '🙁', name: 'slightly frowning face' },
	{ emoji: '😮', name: 'face open mouth surprised' },
	{ emoji: '😯', name: 'hushed face' },
	{ emoji: '😲', name: 'astonished face' },
	{ emoji: '😳', name: 'flushed face embarrassed' },
	{ emoji: '🥺', name: 'pleading face puppy eyes' },
	{ emoji: '🥹', name: 'face holding back tears' },
	{ emoji: '😦', name: 'frowning face open mouth' },
	{ emoji: '😧', name: 'anguished face' },
	{ emoji: '😨', name: 'fearful face scared' },
	{ emoji: '😰', name: 'anxious face sweat' },
	{ emoji: '😥', name: 'sad but relieved face' },
	{ emoji: '😢', name: 'crying face' },
	{ emoji: '😭', name: 'loudly crying face' },
	{ emoji: '😱', name: 'face screaming fear' },
	{ emoji: '😖', name: 'confounded face' },
	{ emoji: '😣', name: 'persevering face' },
	{ emoji: '😞', name: 'disappointed face' },
	{ emoji: '😓', name: 'downcast face sweat' },
	{ emoji: '😩', name: 'weary face tired' },
	{ emoji: '😫', name: 'tired face' },
	{ emoji: '🥱', name: 'yawning face' },
	{ emoji: '😤', name: 'face steam nose angry' },
	{ emoji: '😡', name: 'pouting face angry red' },
	{ emoji: '😠', name: 'angry face' },
	{ emoji: '🤬', name: 'face symbols mouth swearing' },
	{ emoji: '😈', name: 'smiling face horns devil' },
	{ emoji: '👿', name: 'angry face horns devil' },
	{ emoji: '💀', name: 'skull dead' },
	{ emoji: '☠️', name: 'skull crossbones death' },
	{ emoji: '💩', name: 'pile poo poop' },
	{ emoji: '🤡', name: 'clown face' },
	{ emoji: '👹', name: 'ogre monster' },
	{ emoji: '👺', name: 'goblin' },
	{ emoji: '👻', name: 'ghost' },
	{ emoji: '👽', name: 'alien' },
	{ emoji: '👾', name: 'alien monster space invader' },
	{ emoji: '🤖', name: 'robot face' },
];
