import type { EmojiEntry } from './types.js';

export const flags: EmojiEntry[] = [
	{ emoji: '🏳️', name: 'white flag' },
	{ emoji: '🏴', name: 'black flag' },
	{ emoji: '🏁', name: 'chequered flag racing finish' },
	{ emoji: '🚩', name: 'triangular flag red' },
	{ emoji: '🏳️‍🌈', name: 'rainbow flag pride' },
	{ emoji: '🏳️‍⚧️', name: 'transgender flag' },
	{ emoji: '🏴‍☠️', name: 'pirate flag' },
	{ emoji: '🇦🇫', name: 'flag afghanistan' },
	{ emoji: '🇦🇱', name: 'flag albania' },
	{ emoji: '🇩🇿', name: 'flag algeria' },
	{ emoji: '🇦🇩', name: 'flag andorra' },
	{ emoji: '🇦🇴', name: 'flag angola' },
	{ emoji: '🇦🇬', name: 'flag antigua barbuda' },
	{ emoji: '🇦🇷', name: 'flag argentina' },
	{ emoji: '🇦🇲', name: 'flag armenia' },
	{ emoji: '🇦🇺', name: 'flag australia' },
	{ emoji: '🇦🇹', name: 'flag austria' },
	{ emoji: '🇦🇿', name: 'flag azerbaijan' },
	{ emoji: '🇧🇸', name: 'flag bahamas' },
	{ emoji: '🇧🇭', name: 'flag bahrain' },
	{ emoji: '🇧🇩', name: 'flag bangladesh' },
	{ emoji: '🇧🇧', name: 'flag barbados' },
	{ emoji: '🇧🇾', name: 'flag belarus' },
	{ emoji: '🇧🇪', name: 'flag belgium' },
	{ emoji: '🇧🇿', name: 'flag belize' },
	{ emoji: '🇧🇯', name: 'flag benin' },
	{ emoji: '🇧🇹', name: 'flag bhutan' },
	{ emoji: '🇧🇴', name: 'flag bolivia' },
	{ emoji: '🇧🇦', name: 'flag bosnia herzegovina' },
	{ emoji: '🇧🇼', name: 'flag botswana' },
	{ emoji: '🇧🇷', name: 'flag brazil brasil' },
	{ emoji: '🇧🇳', name: 'flag brunei' },
	{ emoji: '🇧🇬', name: 'flag bulgaria' },
	{ emoji: '🇧🇫', name: 'flag burkina faso' },
	{ emoji: '🇧🇮', name: 'flag burundi' },
	{ emoji: '🇰🇭', name: 'flag cambodia' },
	{ emoji: '🇨🇲', name: 'flag cameroon' },
	{ emoji: '🇨🇦', name: 'flag canada' },
	{ emoji: '🇨🇻', name: 'flag cape verde' },
	{ emoji: '🇨🇫', name: 'flag central african republic' },
	{ emoji: '🇹🇩', name: 'flag chad' },
	{ emoji: '🇨🇱', name: 'flag chile' },
	{ emoji: '🇨🇳', name: 'flag china' },
	{ emoji: '🇨🇴', name: 'flag colombia' },
	{ emoji: '🇰🇲', name: 'flag comoros' },
	{ emoji: '🇨🇬', name: 'flag congo brazzaville' },
	{ emoji: '🇨🇩', name: 'flag congo kinshasa' },
	{ emoji: '🇨🇷', name: 'flag costa rica' },
	{ emoji: '🇭🇷', name: 'flag croatia' },
	{ emoji: '🇨🇺', name: 'flag cuba' },
	{ emoji: '🇨🇾', name: 'flag cyprus' },
	{ emoji: '🇨🇿', name: 'flag czechia czech republic' },
	{ emoji: '🇩🇰', name: 'flag denmark' },
	{ emoji: '🇩🇯', name: 'flag djibouti' },
	{ emoji: '🇩🇲', name: 'flag dominica' },
	{ emoji: '🇩🇴', name: 'flag dominican republic' },
	{ emoji: '🇪🇨', name: 'flag ecuador' },
	{ emoji: '🇪🇬', name: 'flag egypt' },
	{ emoji: '🇸🇻', name: 'flag el salvador' },
	{ emoji: '🇬🇶', name: 'flag equatorial guinea' },
	{ emoji: '🇪🇷', name: 'flag eritrea' },
	{ emoji: '🇪🇪', name: 'flag estonia' },
	{ emoji: '🇸🇿', name: 'flag eswatini' },
	{ emoji: '🇪🇹', name: 'flag ethiopia' },
	{ emoji: '🇫🇯', name: 'flag fiji' },
	{ emoji: '🇫🇮', name: 'flag finland' },
	{ emoji: '🇫🇷', name: 'flag france' },
	{ emoji: '🇬🇦', name: 'flag gabon' },
	{ emoji: '🇬🇲', name: 'flag gambia' },
	{ emoji: '🇬🇪', name: 'flag georgia' },
	{ emoji: '🇩🇪', name: 'flag germany' },
	{ emoji: '🇬🇭', name: 'flag ghana' },
	{ emoji: '🇬🇷', name: 'flag greece' },
	{ emoji: '🇬🇩', name: 'flag grenada' },
	{ emoji: '🇬🇹', name: 'flag guatemala' },
	{ emoji: '🇬🇳', name: 'flag guinea' },
	{ emoji: '🇬🇼', name: 'flag guinea-bissau' },
	{ emoji: '🇬🇾', name: 'flag guyana' },
	{ emoji: '🇭🇹', name: 'flag haiti' },
	{ emoji: '🇭🇳', name: 'flag honduras' },
	{ emoji: '🇭🇺', name: 'flag hungary' },
	{ emoji: '🇮🇸', name: 'flag iceland' },
	{ emoji: '🇮🇳', name: 'flag india' },
	{ emoji: '🇮🇩', name: 'flag indonesia' },
	{ emoji: '🇮🇷', name: 'flag iran' },
	{ emoji: '🇮🇶', name: 'flag iraq' },
	{ emoji: '🇮🇪', name: 'flag ireland' },
	{ emoji: '🇮🇱', name: 'flag israel' },
	{ emoji: '🇮🇹', name: 'flag italy' },
	{ emoji: '🇯🇲', name: 'flag jamaica' },
	{ emoji: '🇯🇵', name: 'flag japan' },
	{ emoji: '🇯🇴', name: 'flag jordan' },
	{ emoji: '🇰🇿', name: 'flag kazakhstan' },
	{ emoji: '🇰🇪', name: 'flag kenya' },
	{ emoji: '🇰🇮', name: 'flag kiribati' },
	{ emoji: '🇰🇵', name: 'flag north korea' },
	{ emoji: '🇰🇷', name: 'flag south korea' },
	{ emoji: '🇰🇼', name: 'flag kuwait' },
	{ emoji: '🇰🇬', name: 'flag kyrgyzstan' },
	{ emoji: '🇱🇦', name: 'flag laos' },
	{ emoji: '🇱🇻', name: 'flag latvia' },
	{ emoji: '🇱🇧', name: 'flag lebanon' },
	{ emoji: '🇱🇸', name: 'flag lesotho' },
	{ emoji: '🇱🇷', name: 'flag liberia' },
	{ emoji: '🇱🇾', name: 'flag libya' },
	{ emoji: '🇱🇮', name: 'flag liechtenstein' },
	{ emoji: '🇱🇹', name: 'flag lithuania' },
	{ emoji: '🇱🇺', name: 'flag luxembourg' },
	{ emoji: '🇲🇬', name: 'flag madagascar' },
	{ emoji: '🇲🇼', name: 'flag malawi' },
	{ emoji: '🇲🇾', name: 'flag malaysia' },
	{ emoji: '🇲🇻', name: 'flag maldives' },
	{ emoji: '🇲🇱', name: 'flag mali' },
	{ emoji: '🇲🇹', name: 'flag malta' },
	{ emoji: '🇲🇭', name: 'flag marshall islands' },
	{ emoji: '🇲🇷', name: 'flag mauritania' },
	{ emoji: '🇲🇺', name: 'flag mauritius' },
	{ emoji: '🇲🇽', name: 'flag mexico' },
	{ emoji: '🇫🇲', name: 'flag micronesia' },
	{ emoji: '🇲🇩', name: 'flag moldova' },
	{ emoji: '🇲🇨', name: 'flag monaco' },
	{ emoji: '🇲🇳', name: 'flag mongolia' },
	{ emoji: '🇲🇪', name: 'flag montenegro' },
	{ emoji: '🇲🇦', name: 'flag morocco' },
	{ emoji: '🇲🇿', name: 'flag mozambique' },
	{ emoji: '🇲🇲', name: 'flag myanmar burma' },
	{ emoji: '🇳🇦', name: 'flag namibia' },
	{ emoji: '🇳🇷', name: 'flag nauru' },
	{ emoji: '🇳🇵', name: 'flag nepal' },
	{ emoji: '🇳🇱', name: 'flag netherlands' },
	{ emoji: '🇳🇿', name: 'flag new zealand' },
	{ emoji: '🇳🇮', name: 'flag nicaragua' },
	{ emoji: '🇳🇪', name: 'flag niger' },
	{ emoji: '🇳🇬', name: 'flag nigeria' },
	{ emoji: '🇲🇰', name: 'flag north macedonia' },
	{ emoji: '🇳🇴', name: 'flag norway' },
	{ emoji: '🇴🇲', name: 'flag oman' },
	{ emoji: '🇵🇰', name: 'flag pakistan' },
	{ emoji: '🇵🇼', name: 'flag palau' },
	{ emoji: '🇵🇸', name: 'flag palestine' },
	{ emoji: '🇵🇦', name: 'flag panama' },
	{ emoji: '🇵🇬', name: 'flag papua new guinea' },
	{ emoji: '🇵🇾', name: 'flag paraguay' },
	{ emoji: '🇵🇪', name: 'flag peru' },
	{ emoji: '🇵🇭', name: 'flag philippines' },
	{ emoji: '🇵🇱', name: 'flag poland' },
	{ emoji: '🇵🇹', name: 'flag portugal' },
	{ emoji: '🇶🇦', name: 'flag qatar' },
	{ emoji: '🇷🇴', name: 'flag romania' },
	{ emoji: '🇷🇺', name: 'flag russia' },
	{ emoji: '🇷🇼', name: 'flag rwanda' },
	{ emoji: '🇰🇳', name: 'flag saint kitts nevis' },
	{ emoji: '🇱🇨', name: 'flag saint lucia' },
	{ emoji: '🇻🇨', name: 'flag saint vincent grenadines' },
	{ emoji: '🇼🇸', name: 'flag samoa' },
	{ emoji: '🇸🇲', name: 'flag san marino' },
	{ emoji: '🇸🇹', name: 'flag sao tome principe' },
	{ emoji: '🇸🇦', name: 'flag saudi arabia' },
	{ emoji: '🇸🇳', name: 'flag senegal' },
	{ emoji: '🇷🇸', name: 'flag serbia' },
	{ emoji: '🇸🇨', name: 'flag seychelles' },
	{ emoji: '🇸🇱', name: 'flag sierra leone' },
	{ emoji: '🇸🇬', name: 'flag singapore' },
	{ emoji: '🇸🇰', name: 'flag slovakia' },
	{ emoji: '🇸🇮', name: 'flag slovenia' },
	{ emoji: '🇸🇧', name: 'flag solomon islands' },
	{ emoji: '🇸🇴', name: 'flag somalia' },
	{ emoji: '🇿🇦', name: 'flag south africa' },
	{ emoji: '🇸🇸', name: 'flag south sudan' },
	{ emoji: '🇪🇸', name: 'flag spain' },
	{ emoji: '🇱🇰', name: 'flag sri lanka' },
	{ emoji: '🇸🇩', name: 'flag sudan' },
	{ emoji: '🇸🇷', name: 'flag suriname' },
	{ emoji: '🇸🇪', name: 'flag sweden' },
	{ emoji: '🇨🇭', name: 'flag switzerland' },
	{ emoji: '🇸🇾', name: 'flag syria' },
	{ emoji: '🇹🇼', name: 'flag taiwan' },
	{ emoji: '🇹🇯', name: 'flag tajikistan' },
	{ emoji: '🇹🇿', name: 'flag tanzania' },
	{ emoji: '🇹🇭', name: 'flag thailand' },
	{ emoji: '🇹🇱', name: 'flag timor-leste' },
	{ emoji: '🇹🇬', name: 'flag togo' },
	{ emoji: '🇹🇴', name: 'flag tonga' },
	{ emoji: '🇹🇹', name: 'flag trinidad tobago' },
	{ emoji: '🇹🇳', name: 'flag tunisia' },
	{ emoji: '🇹🇷', name: 'flag turkey turkiye' },
	{ emoji: '🇹🇲', name: 'flag turkmenistan' },
	{ emoji: '🇹🇻', name: 'flag tuvalu' },
	{ emoji: '🇺🇬', name: 'flag uganda' },
	{ emoji: '🇺🇦', name: 'flag ukraine' },
	{ emoji: '🇦🇪', name: 'flag united arab emirates uae' },
	{ emoji: '🇬🇧', name: 'flag united kingdom uk britain' },
	{ emoji: '🇺🇸', name: 'flag united states usa america' },
	{ emoji: '🇺🇾', name: 'flag uruguay' },
	{ emoji: '🇺🇿', name: 'flag uzbekistan' },
	{ emoji: '🇻🇺', name: 'flag vanuatu' },
	{ emoji: '🇻🇦', name: 'flag vatican city' },
	{ emoji: '🇻🇪', name: 'flag venezuela' },
	{ emoji: '🇻🇳', name: 'flag vietnam' },
	{ emoji: '🇾🇪', name: 'flag yemen' },
	{ emoji: '🇿🇲', name: 'flag zambia' },
	{ emoji: '🇿🇼', name: 'flag zimbabwe' },
	{ emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'flag england' },
	{ emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'flag scotland' },
	{ emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'flag wales' },
];
