import type { EmojiEntry } from './types.js';

export const food: EmojiEntry[] = [
	{ emoji: '🍏', name: 'green apple' },
	{ emoji: '🍎', name: 'red apple' },
	{ emoji: '🍐', name: 'pear' },
	{ emoji: '🍊', name: 'tangerine orange' },
	{ emoji: '🍋', name: 'lemon' },
	{ emoji: '🍌', name: 'banana' },
	{ emoji: '🍉', name: 'watermelon' },
	{ emoji: '🍇', name: 'grapes' },
	{ emoji: '🍓', name: 'strawberry' },
	{ emoji: '🫐', name: 'blueberries' },
	{ emoji: '🍈', name: 'melon' },
	{ emoji: '🍒', name: 'cherries' },
	{ emoji: '🍑', name: 'peach' },
	{ emoji: '🥭', name: 'mango' },
	{ emoji: '🍍', name: 'pineapple' },
	{ emoji: '🥥', name: 'coconut' },
	{ emoji: '🥝', name: 'kiwi fruit' },
	{ emoji: '🍅', name: 'tomato' },
	{ emoji: '🍆', name: 'eggplant aubergine' },
	{ emoji: '🥑', name: 'avocado' },
	{ emoji: '🥦', name: 'broccoli' },
	{ emoji: '🥬', name: 'leafy green lettuce' },
	{ emoji: '🥒', name: 'cucumber' },
	{ emoji: '🌶️', name: 'hot pepper chili' },
	{ emoji: '🫑', name: 'bell pepper' },
	{ emoji: '🌽', name: 'ear corn' },
	{ emoji: '🥕', name: 'carrot' },
	{ emoji: '🫒', name: 'olive' },
	{ emoji: '🧄', name: 'garlic' },
	{ emoji: '🧅', name: 'onion' },
	{ emoji: '🥔', name: 'potato' },
	{ emoji: '🍠', name: 'roasted sweet potato' },
	{ emoji: '🫘', name: 'beans' },
	{ emoji: '🥐', name: 'croissant' },
	{ emoji: '🍞', name: 'bread loaf' },
	{ emoji: '🥖', name: 'baguette bread french' },
	{ emoji: '🥨', name: 'pretzel' },
	{ emoji: '🧀', name: 'cheese wedge' },
	{ emoji: '🥚', name: 'egg' },
	{ emoji: '🍳', name: 'cooking fried egg' },
	{ emoji: '🧈', name: 'butter' },
	{ emoji: '🥞', name: 'pancakes' },
	{ emoji: '🧇', name: 'waffle' },
	{ emoji: '🥓', name: 'bacon' },
	{ emoji: '🥩', name: 'cut meat steak' },
	{ emoji: '🍗', name: 'poultry leg chicken' },
	{ emoji: '🍖', name: 'meat bone' },
	{ emoji: '🦴', name: 'bone' },
	{ emoji: '🌭', name: 'hot dog' },
	{ emoji: '🍔', name: 'hamburger burger' },
	{ emoji: '🍟', name: 'french fries' },
	{ emoji: '🍕', name: 'pizza' },
	{ emoji: '🫓', name: 'flatbread' },
	{ emoji: '🥪', name: 'sandwich' },
	{ emoji: '🥙', name: 'stuffed flatbread pita' },
	{ emoji: '🧆', name: 'falafel' },
	{ emoji: '🌮', name: 'taco' },
	{ emoji: '🌯', name: 'burrito wrap' },
	{ emoji: '🫔', name: 'tamale' },
	{ emoji: '🥗', name: 'green salad' },
	{ emoji: '🥘', name: 'shallow pan food paella' },
	{ emoji: '🫕', name: 'fondue' },
	{ emoji: '🥫', name: 'canned food' },
	{ emoji: '🍝', name: 'spaghetti pasta' },
	{ emoji: '🍜', name: 'steaming bowl noodles ramen' },
	{ emoji: '🍲', name: 'pot food stew' },
	{ emoji: '🍛', name: 'curry rice' },
	{ emoji: '🍣', name: 'sushi' },
	{ emoji: '🍱', name: 'bento box' },
	{ emoji: '🥟', name: 'dumpling' },
	{ emoji: '🦪', name: 'oyster' },
	{ emoji: '🍤', name: 'fried shrimp tempura' },
	{ emoji: '🍙', name: 'rice ball onigiri' },
	{ emoji: '🍚', name: 'cooked rice' },
	{ emoji: '🍘', name: 'rice cracker' },
	{ emoji: '🍥', name: 'fish cake' },
	{ emoji: '🥠', name: 'fortune cookie' },
	{ emoji: '🥮', name: 'moon cake' },
	{ emoji: '🍢', name: 'oden skewer' },
	{ emoji: '🍡', name: 'dango' },
	{ emoji: '🍧', name: 'shaved ice' },
	{ emoji: '🍨', name: 'ice cream' },
	{ emoji: '🍦', name: 'soft ice cream cone' },
	{ emoji: '🥧', name: 'pie' },
	{ emoji: '🧁', name: 'cupcake' },
	{ emoji: '🍰', name: 'shortcake' },
	{ emoji: '🎂', name: 'birthday cake' },
	{ emoji: '🍮', name: 'custard pudding flan' },
	{ emoji: '🍭', name: 'lollipop candy' },
	{ emoji: '🍬', name: 'candy sweet' },
	{ emoji: '🍫', name: 'chocolate bar' },
	{ emoji: '🍿', name: 'popcorn' },
	{ emoji: '🍩', name: 'doughnut donut' },
	{ emoji: '🍪', name: 'cookie' },
	{ emoji: '🌰', name: 'chestnut' },
	{ emoji: '🥜', name: 'peanuts' },
	{ emoji: '🍯', name: 'honey pot' },
];
