import type { EmojiEntry } from './types.js';

export const gestures: EmojiEntry[] = [
	{ emoji: '👋', name: 'waving hand hello' },
	{ emoji: '🤚', name: 'raised back hand' },
	{ emoji: '🖐️', name: 'hand splayed fingers' },
	{ emoji: '✋', name: 'raised hand stop' },
	{ emoji: '🖖', name: 'vulcan salute spock' },
	{ emoji: '🫱', name: 'rightwards hand' },
	{ emoji: '🫲', name: 'leftwards hand' },
	{ emoji: '🫳', name: 'palm down hand' },
	{ emoji: '🫴', name: 'palm up hand' },
	{ emoji: '👌', name: 'ok hand' },
	{ emoji: '🤌', name: 'pinched fingers italian' },
	{ emoji: '🤏', name: 'pinching hand small' },
	{ emoji: '✌️', name: 'victory hand peace' },
	{ emoji: '🤞', name: 'crossed fingers luck' },
	{ emoji: '🫰', name: 'hand index thumb crossed' },
	{ emoji: '🤟', name: 'love you gesture' },
	{ emoji: '🤘', name: 'sign horns rock' },
	{ emoji: '🤙', name: 'call me hand' },
	{ emoji: '👈', name: 'backhand pointing left' },
	{ emoji: '👉', name: 'backhand pointing right' },
	{ emoji: '👆', name: 'backhand pointing up' },
	{ emoji: '🖕', name: 'middle finger' },
	{ emoji: '👇', name: 'backhand pointing down' },
	{ emoji: '☝️', name: 'index pointing up' },
	{ emoji: '🫵', name: 'index pointing at viewer' },
	{ emoji: '👍', name: 'thumbs up like' },
	{ emoji: '👎', name: 'thumbs down dislike' },
	{ emoji: '✊', name: 'raised fist' },
	{ emoji: '👊', name: 'oncoming fist punch' },
	{ emoji: '🤛', name: 'left facing fist bump' },
	{ emoji: '🤜', name: 'right facing fist bump' },
	{ emoji: '👏', name: 'clapping hands applause' },
	{ emoji: '🙌', name: 'raising hands celebrate' },
	{ emoji: '🫶', name: 'heart hands love' },
	{ emoji: '👐', name: 'open hands' },
	{ emoji: '🤲', name: 'palms up together' },
	{ emoji: '🤝', name: 'handshake deal' },
	{ emoji: '🙏', name: 'folded hands pray please' },
	{ emoji: '✍️', name: 'writing hand' },
	{ emoji: '💪', name: 'flexed biceps strong muscle' },
	{ emoji: '🦾', name: 'mechanical arm prosthetic' },
	{ emoji: '🦿', name: 'mechanical leg prosthetic' },
	{ emoji: '🦶', name: 'foot' },
	{ emoji: '🦵', name: 'leg' },
	{ emoji: '👀', name: 'eyes looking' },
	{ emoji: '👁️', name: 'eye' },
	{ emoji: '👅', name: 'tongue' },
	{ emoji: '👄', name: 'mouth lips' },
	{ emoji: '🫦', name: 'biting lip' },
	{ emoji: '💋', name: 'kiss mark lips' },
];
