import type { EmojiEntry } from './types.js';

export const nature: EmojiEntry[] = [
	{ emoji: '🌵', name: 'cactus desert' },
	{ emoji: '🎄', name: 'christmas tree' },
	{ emoji: '🌲', name: 'evergreen tree pine' },
	{ emoji: '🌳', name: 'deciduous tree' },
	{ emoji: '🌴', name: 'palm tree tropical' },
	{ emoji: '🪵', name: 'wood log' },
	{ emoji: '🌱', name: 'seedling sprout' },
	{ emoji: '🌿', name: 'herb leaf' },
	{ emoji: '☘️', name: 'shamrock clover' },
	{ emoji: '🍀', name: 'four leaf clover luck' },
	{ emoji: '🎍', name: 'bamboo pine decoration' },
	{ emoji: '🪴', name: 'potted plant' },
	{ emoji: '🎋', name: 'tanabata tree' },
	{ emoji: '🍃', name: 'leaf fluttering wind' },
	{ emoji: '🍂', name: 'fallen leaf autumn' },
	{ emoji: '🍁', name: 'maple leaf fall' },
	{ emoji: '🪺', name: 'nest eggs' },
	{ emoji: '🪹', name: 'empty nest' },
	{ emoji: '🍄', name: 'mushroom' },
	{ emoji: '🌾', name: 'sheaf rice wheat' },
	{ emoji: '💐', name: 'bouquet flowers' },
	{ emoji: '🌷', name: 'tulip flower' },
	{ emoji: '🌹', name: 'rose flower red' },
	{ emoji: '🥀', name: 'wilted flower' },
	{ emoji: '🌺', name: 'hibiscus flower' },
	{ emoji: '🌸', name: 'cherry blossom sakura' },
	{ emoji: '🌼', name: 'blossom flower' },
	{ emoji: '🌻', name: 'sunflower' },
	{ emoji: '🌞', name: 'sun face' },
	{ emoji: '🌝', name: 'full moon face' },
	{ emoji: '🌛', name: 'first quarter moon face' },
	{ emoji: '🌜', name: 'last quarter moon face' },
	{ emoji: '🌚', name: 'new moon face' },
	{ emoji: '🌕', name: 'full moon' },
	{ emoji: '🌖', name: 'waning gibbous moon' },
	{ emoji: '🌗', name: 'last quarter moon' },
	{ emoji: '🌘', name: 'waning crescent moon' },
	{ emoji: '🌑', name: 'new moon' },
	{ emoji: '🌒', name: 'waxing crescent moon' },
	{ emoji: '🌓', name: 'first quarter moon' },
	{ emoji: '🌔', name: 'waxing gibbous moon' },
	{ emoji: '🌙', name: 'crescent moon night' },
	{ emoji: '🌎', name: 'globe americas earth' },
	{ emoji: '🌍', name: 'globe europe africa earth' },
	{ emoji: '🌏', name: 'globe asia australia earth' },
	{ emoji: '🪐', name: 'ringed planet saturn' },
	{ emoji: '💫', name: 'dizzy star' },
	{ emoji: '⭐', name: 'star' },
	{ emoji: '🌟', name: 'glowing star sparkle' },
	{ emoji: '✨', name: 'sparkles magic' },
	{ emoji: '⚡', name: 'high voltage lightning' },
	{ emoji: '☄️', name: 'comet' },
	{ emoji: '💥', name: 'collision boom explosion' },
	{ emoji: '🔥', name: 'fire flame hot' },
	{ emoji: '🌪️', name: 'tornado' },
	{ emoji: '🌈', name: 'rainbow' },
	{ emoji: '☀️', name: 'sun sunny' },
	{ emoji: '🌤️', name: 'sun small cloud' },
	{ emoji: '⛅', name: 'sun behind cloud' },
	{ emoji: '🌥️', name: 'sun behind large cloud' },
	{ emoji: '☁️', name: 'cloud' },
	{ emoji: '🌦️', name: 'sun behind rain cloud' },
	{ emoji: '🌧️', name: 'cloud rain' },
	{ emoji: '⛈️', name: 'cloud lightning rain storm' },
	{ emoji: '🌩️', name: 'cloud lightning' },
	{ emoji: '🌨️', name: 'cloud snow' },
	{ emoji: '❄️', name: 'snowflake cold winter' },
	{ emoji: '☃️', name: 'snowman' },
	{ emoji: '⛄', name: 'snowman without snow' },
	{ emoji: '🌬️', name: 'wind face blow' },
	{ emoji: '💨', name: 'dashing away wind' },
	{ emoji: '💧', name: 'droplet water' },
	{ emoji: '💦', name: 'sweat droplets splash' },
	{ emoji: '🫧', name: 'bubbles' },
	{ emoji: '☔', name: 'umbrella rain' },
	{ emoji: '☂️', name: 'umbrella' },
	{ emoji: '🌊', name: 'water wave ocean' },
	{ emoji: '🌫️', name: 'fog mist' },
];
