import type { EmojiEntry } from './types.js';

export const objects: EmojiEntry[] = [
	{ emoji: '⌚', name: 'watch wristwatch' },
	{ emoji: '📱', name: 'mobile phone smartphone' },
	{ emoji: '📲', name: 'mobile phone arrow' },
	{ emoji: '💻', name: 'laptop computer' },
	{ emoji: '⌨️', name: 'keyboard' },
	{ emoji: '🖥️', name: 'desktop computer monitor' },
	{ emoji: '🖨️', name: 'printer' },
	{ emoji: '🖱️', name: 'computer mouse' },
	{ emoji: '🖲️', name: 'trackball' },
	{ emoji: '🕹️', name: 'joystick game controller' },
	{ emoji: '🗜️', name: 'clamp compression' },
	{ emoji: '💽', name: 'minidisc' },
	{ emoji: '💾', name: 'floppy disk save' },
	{ emoji: '💿', name: 'optical disc cd' },
	{ emoji: '📀', name: 'dvd' },
	{ emoji: '📼', name: 'videocassette vhs tape' },
	{ emoji: '📷', name: 'camera photo' },
	{ emoji: '📸', name: 'camera flash' },
	{ emoji: '📹', name: 'video camera camcorder' },
	{ emoji: '🎥', name: 'movie camera film' },
	{ emoji: '📽️', name: 'film projector' },
	{ emoji: '🎞️', name: 'film frames' },
	{ emoji: '📞', name: 'telephone receiver phone' },
	{ emoji: '☎️', name: 'telephone' },
	{ emoji: '📟', name: 'pager' },
	{ emoji: '📠', name: 'fax machine' },
	{ emoji: '📺', name: 'television tv' },
	{ emoji: '📻', name: 'radio' },
	{ emoji: '🎙️', name: 'studio microphone' },
	{ emoji: '🎚️', name: 'level slider' },
	{ emoji: '🎛️', name: 'control knobs' },
	{ emoji: '🧭', name: 'compass navigation' },
	{ emoji: '⏱️', name: 'stopwatch timer' },
	{ emoji: '⏲️', name: 'timer clock' },
	{ emoji: '⏰', name: 'alarm clock' },
	{ emoji: '🕰️', name: 'mantelpiece clock' },
	{ emoji: '⌛', name: 'hourglass done' },
	{ emoji: '⏳', name: 'hourglass flowing' },
	{ emoji: '📡', name: 'satellite antenna dish' },
	{ emoji: '🔋', name: 'battery' },
	{ emoji: '🪫', name: 'low battery' },
	{ emoji: '🔌', name: 'electric plug' },
	{ emoji: '💡', name: 'light bulb idea' },
	{ emoji: '🔦', name: 'flashlight torch' },
	{ emoji: '🕯️', name: 'candle' },
	{ emoji: '🧯', name: 'fire extinguisher' },
	{ emoji: '🛢️', name: 'oil drum barrel' },
	{ emoji: '💸', name: 'money wings flying' },
	{ emoji: '💵', name: 'dollar banknote money' },
	{ emoji: '💴', name: 'yen banknote' },
	{ emoji: '💶', name: 'euro banknote' },
	{ emoji: '💷', name: 'pound banknote' },
	{ emoji: '🪙', name: 'coin' },
	{ emoji: '💰', name: 'money bag' },
	{ emoji: '💳', name: 'credit card' },
	{ emoji: '💎', name: 'gem stone diamond jewel' },
	{ emoji: '⚖️', name: 'balance scale justice' },
	{ emoji: '🪜', name: 'ladder' },
	{ emoji: '🧰', name: 'toolbox' },
	{ emoji: '🪛', name: 'screwdriver' },
	{ emoji: '🔧', name: 'wrench spanner' },
	{ emoji: '🔨', name: 'hammer' },
	{ emoji: '⚒️', name: 'hammer pick' },
	{ emoji: '🛠️', name: 'hammer wrench tools' },
	{ emoji: '⛏️', name: 'pick axe mining' },
	{ emoji: '🪚', name: 'carpentry saw' },
	{ emoji: '🔩', name: 'nut bolt' },
	{ emoji: '⚙️', name: 'gear cog settings' },
	{ emoji: '🪤', name: 'mouse trap' },
	{ emoji: '🧲', name: 'magnet' },
	{ emoji: '🔗', name: 'link chain' },
	{ emoji: '📎', name: 'paperclip' },
	{ emoji: '🖇️', name: 'linked paperclips' },
	{ emoji: '📐', name: 'triangular ruler' },
	{ emoji: '📏', name: 'straight ruler' },
	{ emoji: '🧮', name: 'abacus' },
	{ emoji: '📌', name: 'pushpin pin' },
	{ emoji: '📍', name: 'round pushpin location' },
	{ emoji: '✂️', name: 'scissors cut' },
	{ emoji: '🖊️', name: 'pen ballpoint' },
	{ emoji: '🖋️', name: 'fountain pen' },
	{ emoji: '✒️', name: 'black nib pen' },
	{ emoji: '🖌️', name: 'paintbrush art' },
	{ emoji: '🖍️', name: 'crayon' },
	{ emoji: '📝', name: 'memo note pencil' },
	{ emoji: '✏️', name: 'pencil write' },
	{ emoji: '🔍', name: 'magnifying glass left search' },
	{ emoji: '🔎', name: 'magnifying glass right' },
	{ emoji: '🔏', name: 'locked pen' },
	{ emoji: '🔐', name: 'locked key' },
	{ emoji: '🔒', name: 'locked padlock' },
	{ emoji: '🔓', name: 'unlocked padlock' },
	{ emoji: '🔑', name: 'key' },
	{ emoji: '🗝️', name: 'old key' },
	{ emoji: '🔮', name: 'crystal ball magic' },
	{ emoji: '🧿', name: 'nazar amulet evil eye' },
	{ emoji: '🪬', name: 'hamsa' },
	{ emoji: '🏺', name: 'amphora vase' },
	{ emoji: '🧫', name: 'petri dish' },
	{ emoji: '🧪', name: 'test tube' },
	{ emoji: '🌡️', name: 'thermometer temperature' },
	{ emoji: '🧬', name: 'dna double helix' },
	{ emoji: '🔬', name: 'microscope science' },
	{ emoji: '🔭', name: 'telescope' },
	{ emoji: '🩻', name: 'x-ray' },
	{ emoji: '🩺', name: 'stethoscope medical' },
	{ emoji: '💊', name: 'pill medicine' },
	{ emoji: '💉', name: 'syringe injection vaccine' },
	{ emoji: '🩸', name: 'drop blood' },
	{ emoji: '🩹', name: 'adhesive bandage' },
	{ emoji: '🩼', name: 'crutch' },
	{ emoji: '🪣', name: 'bucket pail' },
	{ emoji: '🧴', name: 'lotion bottle' },
	{ emoji: '🧹', name: 'broom' },
	{ emoji: '🪠', name: 'plunger' },
	{ emoji: '🧺', name: 'basket laundry' },
	{ emoji: '🧻', name: 'roll paper toilet' },
	{ emoji: '🚽', name: 'toilet' },
	{ emoji: '🚰', name: 'potable water faucet' },
	{ emoji: '🚿', name: 'shower' },
	{ emoji: '🛁', name: 'bathtub bath' },
	{ emoji: '🛀', name: 'person taking bath' },
	{ emoji: '🧼', name: 'soap bar' },
	{ emoji: '🪥', name: 'toothbrush' },
	{ emoji: '🪒', name: 'razor shave' },
	{ emoji: '🪮', name: 'hair pick comb' },
	{ emoji: '🧽', name: 'sponge' },
	{ emoji: '🪞', name: 'mirror' },
	{ emoji: '🪑', name: 'chair seat' },
	{ emoji: '🛋️', name: 'couch sofa lamp' },
	{ emoji: '🛏️', name: 'bed sleep' },
	{ emoji: '🛌', name: 'person sleeping bed' },
	{ emoji: '🧸', name: 'teddy bear toy' },
	{ emoji: '🪆', name: 'nesting dolls matryoshka' },
	{ emoji: '🖼️', name: 'framed picture painting' },
	{ emoji: '🪴', name: 'potted plant' },
	{ emoji: '🛍️', name: 'shopping bags' },
	{ emoji: '🎁', name: 'wrapped gift present' },
	{ emoji: '🎀', name: 'ribbon bow' },
	{ emoji: '🪄', name: 'magic wand' },
	{ emoji: '🎈', name: 'balloon party' },
	{ emoji: '🎏', name: 'carp streamer koinobori' },
	{ emoji: '🎐', name: 'wind chime' },
	{ emoji: '🎊', name: 'confetti ball celebration' },
	{ emoji: '🎉', name: 'party popper tada' },
	{ emoji: '🪩', name: 'mirror ball disco' },
	{ emoji: '🎎', name: 'japanese dolls' },
	{ emoji: '🎍', name: 'pine decoration kadomatsu' },
	{ emoji: '🎋', name: 'tanabata tree' },
	{ emoji: '🧧', name: 'red envelope' },
	{ emoji: '🎃', name: 'jack-o-lantern pumpkin halloween' },
	{ emoji: '👻', name: 'ghost halloween' },
	{ emoji: '☠️', name: 'skull crossbones' },
	{ emoji: '🪦', name: 'headstone gravestone tombstone' },
	{ emoji: '⚱️', name: 'funeral urn' },
	{ emoji: '⚰️', name: 'coffin' },
	{ emoji: '🏷️', name: 'label tag' },
	{ emoji: '📦', name: 'package box parcel' },
	{ emoji: '📫', name: 'mailbox closed flag' },
	{ emoji: '📪', name: 'mailbox closed lowered' },
	{ emoji: '📬', name: 'mailbox open flag' },
	{ emoji: '📭', name: 'mailbox open lowered' },
	{ emoji: '📮', name: 'postbox mail' },
	{ emoji: '📯', name: 'postal horn' },
	{ emoji: '📜', name: 'scroll parchment' },
	{ emoji: '📃', name: 'page curl document' },
	{ emoji: '📄', name: 'page facing up document' },
	{ emoji: '📑', name: 'bookmark tabs' },
	{ emoji: '🔖', name: 'bookmark' },
	{ emoji: '🧾', name: 'receipt' },
	{ emoji: '📊', name: 'bar chart graph' },
	{ emoji: '📈', name: 'chart increasing trending up' },
	{ emoji: '📉', name: 'chart decreasing trending down' },
	{ emoji: '📰', name: 'newspaper' },
	{ emoji: '🗞️', name: 'rolled-up newspaper' },
	{ emoji: '📓', name: 'notebook' },
	{ emoji: '📔', name: 'notebook decorative cover' },
	{ emoji: '📒', name: 'ledger' },
	{ emoji: '📕', name: 'closed book red' },
	{ emoji: '📗', name: 'green book' },
	{ emoji: '📘', name: 'blue book' },
	{ emoji: '📙', name: 'orange book' },
	{ emoji: '📚', name: 'books stack' },
	{ emoji: '📖', name: 'open book reading' },
	{ emoji: '🗒️', name: 'spiral notepad' },
	{ emoji: '🗓️', name: 'spiral calendar' },
	{ emoji: '📅', name: 'calendar date' },
	{ emoji: '📆', name: 'tear-off calendar' },
	{ emoji: '📇', name: 'card index rolodex' },
	{ emoji: '🗃️', name: 'card file box' },
	{ emoji: '🗳️', name: 'ballot box' },
	{ emoji: '🗄️', name: 'file cabinet' },
	{ emoji: '📋', name: 'clipboard' },
	{ emoji: '📁', name: 'file folder' },
	{ emoji: '📂', name: 'open file folder' },
	{ emoji: '🗂️', name: 'card index dividers' },
	{ emoji: '✉️', name: 'envelope mail letter' },
	{ emoji: '📧', name: 'email e-mail' },
	{ emoji: '📨', name: 'incoming envelope' },
	{ emoji: '📩', name: 'envelope arrow' },
	{ emoji: '🏮', name: 'red paper lantern' },
];
