import type { EmojiEntry } from './types.js';

export const people: EmojiEntry[] = [
	{ emoji: '👶', name: 'baby' },
	{ emoji: '🧒', name: 'child kid' },
	{ emoji: '👦', name: 'boy' },
	{ emoji: '👧', name: 'girl' },
	{ emoji: '🧑', name: 'person adult' },
	{ emoji: '👱', name: 'person blond hair' },
	{ emoji: '👨', name: 'man' },
	{ emoji: '🧔', name: 'man beard' },
	{ emoji: '👩', name: 'woman' },
	{ emoji: '🧓', name: 'older person elder' },
	{ emoji: '👴', name: 'old man grandfather' },
	{ emoji: '👵', name: 'old woman grandmother' },
	{ emoji: '🙍', name: 'person frowning' },
	{ emoji: '🙎', name: 'person pouting' },
	{ emoji: '🙅', name: 'person gesturing no' },
	{ emoji: '🙆', name: 'person gesturing ok' },
	{ emoji: '💁', name: 'person tipping hand' },
	{ emoji: '🙋', name: 'person raising hand' },
	{ emoji: '🧏', name: 'deaf person' },
	{ emoji: '🙇', name: 'person bowing' },
	{ emoji: '🤦', name: 'person facepalm' },
	{ emoji: '🤷', name: 'person shrugging' },
	{ emoji: '👮', name: 'police officer cop' },
	{ emoji: '🕵️', name: 'detective spy' },
	{ emoji: '💂', name: 'guard soldier' },
	{ emoji: '🥷', name: 'ninja' },
	{ emoji: '👷', name: 'construction worker' },
	{ emoji: '🫅', name: 'person crown royal' },
	{ emoji: '🤴', name: 'prince' },
	{ emoji: '👸', name: 'princess' },
	{ emoji: '👳', name: 'person turban' },
	{ emoji: '👲', name: 'person skullcap' },
	{ emoji: '🧕', name: 'woman headscarf hijab' },
	{ emoji: '🤵', name: 'person tuxedo groom' },
	{ emoji: '👰', name: 'person veil bride wedding' },
	{ emoji: '🤰', name: 'pregnant woman' },
	{ emoji: '🫃', name: 'pregnant man' },
	{ emoji: '🤱', name: 'breast feeding nursing' },
	{ emoji: '👼', name: 'baby angel cherub' },
	{ emoji: '🎅', name: 'santa claus christmas' },
	{ emoji: '🤶', name: 'mrs claus christmas' },
	{ emoji: '🦸', name: 'superhero' },
	{ emoji: '🦹', name: 'supervillain' },
	{ emoji: '🧙', name: 'mage wizard' },
	{ emoji: '🧚', name: 'fairy' },
	{ emoji: '🧛', name: 'vampire' },
	{ emoji: '🧜', name: 'merperson mermaid' },
	{ emoji: '🧝', name: 'elf' },
	{ emoji: '🧞', name: 'genie' },
	{ emoji: '🧟', name: 'zombie' },
	{ emoji: '🧌', name: 'troll' },
	{ emoji: '💆', name: 'person getting massage' },
	{ emoji: '💇', name: 'person getting haircut' },
	{ emoji: '🚶', name: 'person walking' },
	{ emoji: '🧍', name: 'person standing' },
	{ emoji: '🧎', name: 'person kneeling' },
	{ emoji: '🏃', name: 'person running' },
	{ emoji: '💃', name: 'woman dancing' },
	{ emoji: '🕺', name: 'man dancing' },
	{ emoji: '👯', name: 'people bunny ears party' },
];
