import type { EmojiEntry } from './types.js';

export const symbols: EmojiEntry[] = [
	{ emoji: '❤️', name: 'red heart love' },
	{ emoji: '🧡', name: 'orange heart' },
	{ emoji: '💛', name: 'yellow heart' },
	{ emoji: '💚', name: 'green heart' },
	{ emoji: '💙', name: 'blue heart' },
	{ emoji: '💜', name: 'purple heart' },
	{ emoji: '🖤', name: 'black heart' },
	{ emoji: '🤍', name: 'white heart' },
	{ emoji: '🤎', name: 'brown heart' },
	{ emoji: '🩷', name: 'pink heart' },
	{ emoji: '🩵', name: 'light blue heart' },
	{ emoji: '🩶', name: 'grey heart' },
	{ emoji: '💔', name: 'broken heart' },
	{ emoji: '❤️‍🔥', name: 'heart fire burning' },
	{ emoji: '❤️‍🩹', name: 'mending heart bandage' },
	{ emoji: '❣️', name: 'heart exclamation' },
	{ emoji: '💕', name: 'two hearts' },
	{ emoji: '💞', name: 'revolving hearts' },
	{ emoji: '💓', name: 'beating heart' },
	{ emoji: '💗', name: 'growing heart' },
	{ emoji: '💖', name: 'sparkling heart' },
	{ emoji: '💘', name: 'heart arrow cupid' },
	{ emoji: '💝', name: 'heart ribbon gift' },
	{ emoji: '💟', name: 'heart decoration' },
	{ emoji: '☮️', name: 'peace symbol' },
	{ emoji: '✝️', name: 'latin cross christian' },
	{ emoji: '☪️', name: 'star crescent islam' },
	{ emoji: '🕉️', name: 'om hindu' },
	{ emoji: '☸️', name: 'wheel dharma buddhism' },
	{ emoji: '✡️', name: 'star david jewish' },
	{ emoji: '🔯', name: 'six pointed star' },
	{ emoji: '🕎', name: 'menorah' },
	{ emoji: '☯️', name: 'yin yang' },
	{ emoji: '☦️', name: 'orthodox cross' },
	{ emoji: '🛐', name: 'place worship' },
	{ emoji: '⛎', name: 'ophiuchus zodiac' },
	{ emoji: '♈', name: 'aries zodiac' },
	{ emoji: '♉', name: 'taurus zodiac' },
	{ emoji: '♊', name: 'gemini zodiac' },
	{ emoji: '♋', name: 'cancer zodiac' },
	{ emoji: '♌', name: 'leo zodiac' },
	{ emoji: '♍', name: 'virgo zodiac' },
	{ emoji: '♎', name: 'libra zodiac' },
	{ emoji: '♏', name: 'scorpio zodiac' },
	{ emoji: '♐', name: 'sagittarius zodiac' },
	{ emoji: '♑', name: 'capricorn zodiac' },
	{ emoji: '♒', name: 'aquarius zodiac' },
	{ emoji: '♓', name: 'pisces zodiac' },
	{ emoji: '🆔', name: 'id button identity' },
	{ emoji: '⚛️', name: 'atom symbol science' },
	{ emoji: '🉑', name: 'japanese acceptable' },
	{ emoji: '☢️', name: 'radioactive' },
	{ emoji: '☣️', name: 'biohazard' },
	{ emoji: '📴', name: 'mobile phone off' },
	{ emoji: '📳', name: 'vibration mode' },
	{ emoji: '🈶', name: 'japanese not free charge' },
	{ emoji: '🈚', name: 'japanese free charge' },
	{ emoji: '🈸', name: 'japanese application' },
	{ emoji: '🈺', name: 'japanese open business' },
	{ emoji: '🈷️', name: 'japanese monthly amount' },
	{ emoji: '✴️', name: 'eight pointed star' },
	{ emoji: '🆚', name: 'vs versus button' },
	{ emoji: '💮', name: 'white flower' },
	{ emoji: '🉐', name: 'japanese bargain' },
	{ emoji: '㊙️', name: 'japanese secret' },
	{ emoji: '㊗️', name: 'japanese congratulations' },
	{ emoji: '🈴', name: 'japanese passing grade' },
	{ emoji: '🈵', name: 'japanese no vacancy' },
	{ emoji: '🈹', name: 'japanese discount' },
	{ emoji: '🈲', name: 'japanese prohibited' },
	{ emoji: '🅰️', name: 'a button blood type' },
	{ emoji: '🅱️', name: 'b button blood type' },
	{ emoji: '🆎', name: 'ab button blood type' },
	{ emoji: '🆑', name: 'cl button clear' },
	{ emoji: '🅾️', name: 'o button blood type' },
	{ emoji: '🆘', name: 'sos emergency help' },
	{ emoji: '❌', name: 'cross mark x wrong' },
	{ emoji: '⭕', name: 'hollow circle' },
	{ emoji: '🛑', name: 'stop sign' },
	{ emoji: '⛔', name: 'no entry prohibited' },
	{ emoji: '📛', name: 'name badge' },
	{ emoji: '🚫', name: 'prohibited forbidden' },
	{ emoji: '💯', name: 'hundred points percent' },
	{ emoji: '💢', name: 'anger symbol' },
	{ emoji: '♨️', name: 'hot springs' },
	{ emoji: '🚷', name: 'no pedestrians' },
	{ emoji: '🚯', name: 'no littering' },
	{ emoji: '🚳', name: 'no bicycles' },
	{ emoji: '🚱', name: 'non-potable water' },
	{ emoji: '🔞', name: 'no one under eighteen' },
	{ emoji: '📵', name: 'no mobile phones' },
	{ emoji: '🔇', name: 'muted speaker silence' },
	{ emoji: '🔕', name: 'bell slash no notification' },
	{ emoji: '🚭', name: 'no smoking' },
	{ emoji: '❗', name: 'exclamation mark red' },
	{ emoji: '❕', name: 'exclamation mark white' },
	{ emoji: '❓', name: 'question mark red' },
	{ emoji: '❔', name: 'question mark white' },
	{ emoji: '‼️', name: 'double exclamation' },
	{ emoji: '⁉️', name: 'exclamation question' },
	{ emoji: '🔅', name: 'dim brightness low' },
	{ emoji: '🔆', name: 'bright brightness high' },
	{ emoji: '〽️', name: 'part alternation mark' },
	{ emoji: '⚠️', name: 'warning sign' },
	{ emoji: '🚸', name: 'children crossing' },
	{ emoji: '🔱', name: 'trident emblem' },
	{ emoji: '⚜️', name: 'fleur-de-lis' },
	{ emoji: '🔰', name: 'japanese symbol beginner' },
	{ emoji: '♻️', name: 'recycling symbol' },
	{ emoji: '✅', name: 'check mark button done' },
	{ emoji: '🈯', name: 'japanese reserved' },
	{ emoji: '💹', name: 'chart increasing yen' },
	{ emoji: '❇️', name: 'sparkle' },
	{ emoji: '✳️', name: 'eight spoked asterisk' },
	{ emoji: '❎', name: 'cross mark button' },
	{ emoji: '🌐', name: 'globe meridians web internet' },
	{ emoji: '💠', name: 'diamond dot' },
	{ emoji: 'Ⓜ️', name: 'circled m metro' },
	{ emoji: '🌀', name: 'cyclone spiral' },
	{ emoji: '💤', name: 'zzz sleep' },
	{ emoji: '🏧', name: 'atm sign' },
	{ emoji: '🚾', name: 'water closet wc restroom' },
	{ emoji: '♿', name: 'wheelchair accessible' },
	{ emoji: '🅿️', name: 'parking button' },
	{ emoji: '🛗', name: 'elevator lift' },
	{ emoji: '🈳', name: 'japanese vacancy' },
	{ emoji: '🈂️', name: 'japanese service charge' },
	{ emoji: '🛂', name: 'passport control' },
	{ emoji: '🛃', name: 'customs' },
	{ emoji: '🛄', name: 'baggage claim' },
	{ emoji: '🛅', name: 'left luggage' },
	{ emoji: '🔣', name: 'input symbols' },
	{ emoji: '🔤', name: 'input latin letters abc' },
	{ emoji: '🔠', name: 'input latin uppercase' },
	{ emoji: '🔡', name: 'input latin lowercase' },
	{ emoji: '🔢', name: 'input numbers 1234' },
	{ emoji: '🔀', name: 'shuffle tracks' },
	{ emoji: '🔁', name: 'repeat' },
	{ emoji: '🔂', name: 'repeat single' },
	{ emoji: '▶️', name: 'play button' },
	{ emoji: '⏩', name: 'fast forward' },
	{ emoji: '⏭️', name: 'next track' },
	{ emoji: '⏯️', name: 'play pause' },
	{ emoji: '◀️', name: 'reverse button' },
	{ emoji: '⏪', name: 'fast reverse rewind' },
	{ emoji: '⏮️', name: 'last previous track' },
	{ emoji: '🔼', name: 'upwards button triangle' },
	{ emoji: '⏫', name: 'fast up button' },
	{ emoji: '🔽', name: 'downwards button triangle' },
	{ emoji: '⏬', name: 'fast down button' },
	{ emoji: '⏸️', name: 'pause button' },
	{ emoji: '⏹️', name: 'stop button' },
	{ emoji: '⏺️', name: 'record button' },
	{ emoji: '⏏️', name: 'eject button' },
	{ emoji: '🔈', name: 'speaker low volume' },
	{ emoji: '🔉', name: 'speaker medium volume' },
	{ emoji: '🔊', name: 'speaker high volume loud' },
	{ emoji: '🎵', name: 'musical note' },
	{ emoji: '🎶', name: 'musical notes music' },
	{ emoji: '🎼', name: 'musical score' },
	{ emoji: '🔔', name: 'bell notification' },
	{ emoji: '📢', name: 'loudspeaker announcement' },
	{ emoji: '💬', name: 'speech balloon chat message' },
	{ emoji: '💭', name: 'thought balloon thinking' },
	{ emoji: '🗯️', name: 'right anger bubble' },
	{ emoji: '🗨️', name: 'left speech bubble' },
	{ emoji: '♠️', name: 'spade suit cards' },
	{ emoji: '♣️', name: 'club suit cards' },
	{ emoji: '♥️', name: 'heart suit cards' },
	{ emoji: '♦️', name: 'diamond suit cards' },
	{ emoji: '🃏', name: 'joker card' },
	{ emoji: '🎴', name: 'flower playing cards' },
	{ emoji: '🀄', name: 'mahjong red dragon' },
	{ emoji: '🔃', name: 'clockwise arrows' },
	{ emoji: '🔄', name: 'counterclockwise arrows refresh' },
	{ emoji: '🔙', name: 'back arrow' },
	{ emoji: '🔚', name: 'end arrow' },
	{ emoji: '🔛', name: 'on arrow' },
	{ emoji: '🔜', name: 'soon arrow' },
	{ emoji: '🔝', name: 'top arrow' },
	{ emoji: '⬆️', name: 'up arrow' },
	{ emoji: '⬇️', name: 'down arrow' },
	{ emoji: '⬅️', name: 'left arrow' },
	{ emoji: '➡️', name: 'right arrow' },
	{ emoji: '↗️', name: 'up-right arrow' },
	{ emoji: '↘️', name: 'down-right arrow' },
	{ emoji: '↙️', name: 'down-left arrow' },
	{ emoji: '↖️', name: 'up-left arrow' },
	{ emoji: '↕️', name: 'up-down arrow' },
	{ emoji: '↔️', name: 'left-right arrow' },
	{ emoji: '↩️', name: 'right arrow curving left' },
	{ emoji: '↪️', name: 'left arrow curving right' },
	{ emoji: '⤴️', name: 'right arrow curving up' },
	{ emoji: '⤵️', name: 'right arrow curving down' },
	{ emoji: '#️⃣', name: 'hash number sign' },
	{ emoji: '*️⃣', name: 'asterisk keycap' },
	{ emoji: '0️⃣', name: 'keycap zero' },
	{ emoji: '1️⃣', name: 'keycap one' },
	{ emoji: '2️⃣', name: 'keycap two' },
	{ emoji: '3️⃣', name: 'keycap three' },
	{ emoji: '4️⃣', name: 'keycap four' },
	{ emoji: '5️⃣', name: 'keycap five' },
	{ emoji: '6️⃣', name: 'keycap six' },
	{ emoji: '7️⃣', name: 'keycap seven' },
	{ emoji: '8️⃣', name: 'keycap eight' },
	{ emoji: '9️⃣', name: 'keycap nine' },
	{ emoji: '🔟', name: 'keycap ten' },
	{ emoji: '➕', name: 'plus sign add' },
	{ emoji: '➖', name: 'minus sign subtract' },
	{ emoji: '➗', name: 'divide sign division' },
	{ emoji: '✖️', name: 'multiply sign' },
	{ emoji: '🟰', name: 'heavy equals sign' },
	{ emoji: '♾️', name: 'infinity' },
	{ emoji: '💲', name: 'heavy dollar sign money' },
	{ emoji: '©️', name: 'copyright' },
	{ emoji: '®️', name: 'registered' },
	{ emoji: '™️', name: 'trade mark' },
];
