import type { EmojiEntry } from './types.js';

export const travel: EmojiEntry[] = [
	{ emoji: '🚗', name: 'automobile car' },
	{ emoji: '🚕', name: 'taxi cab' },
	{ emoji: '🚙', name: 'sport utility vehicle suv' },
	{ emoji: '🚌', name: 'bus' },
	{ emoji: '🚎', name: 'trolleybus' },
	{ emoji: '🏎️', name: 'racing car formula' },
	{ emoji: '🚓', name: 'police car' },
	{ emoji: '🚑', name: 'ambulance' },
	{ emoji: '🚒', name: 'fire engine truck' },
	{ emoji: '🚐', name: 'minibus van' },
	{ emoji: '🛻', name: 'pickup truck' },
	{ emoji: '🚚', name: 'delivery truck' },
	{ emoji: '🚛', name: 'articulated lorry' },
	{ emoji: '🚜', name: 'tractor farm' },
	{ emoji: '🏍️', name: 'motorcycle' },
	{ emoji: '🛵', name: 'motor scooter' },
	{ emoji: '🚲', name: 'bicycle bike' },
	{ emoji: '🛴', name: 'kick scooter' },
	{ emoji: '🛺', name: 'auto rickshaw' },
	{ emoji: '🚍', name: 'oncoming bus' },
	{ emoji: '🚘', name: 'oncoming automobile' },
	{ emoji: '🚖', name: 'oncoming taxi' },
	{ emoji: '🛞', name: 'wheel tire' },
	{ emoji: '🚡', name: 'aerial tramway' },
	{ emoji: '🚠', name: 'mountain cableway' },
	{ emoji: '🚟', name: 'suspension railway' },
	{ emoji: '🚃', name: 'railway car' },
	{ emoji: '🚋', name: 'tramcar streetcar' },
	{ emoji: '🚞', name: 'mountain railway' },
	{ emoji: '🚝', name: 'monorail' },
	{ emoji: '🚄', name: 'high speed train bullet' },
	{ emoji: '🚅', name: 'bullet train' },
	{ emoji: '🚈', name: 'light rail' },
	{ emoji: '🚂', name: 'locomotive train steam' },
	{ emoji: '🚆', name: 'train' },
	{ emoji: '🚇', name: 'metro subway' },
	{ emoji: '🚊', name: 'tram' },
	{ emoji: '🚉', name: 'station' },
	{ emoji: '✈️', name: 'airplane plane' },
	{ emoji: '🛫', name: 'airplane departure takeoff' },
	{ emoji: '🛬', name: 'airplane arrival landing' },
	{ emoji: '🛩️', name: 'small airplane' },
	{ emoji: '💺', name: 'seat' },
	{ emoji: '🛰️', name: 'satellite' },
	{ emoji: '🚀', name: 'rocket ship space' },
	{ emoji: '🛸', name: 'flying saucer ufo' },
	{ emoji: '🚁', name: 'helicopter' },
	{ emoji: '🛶', name: 'canoe kayak' },
	{ emoji: '⛵', name: 'sailboat' },
	{ emoji: '🚤', name: 'speedboat' },
	{ emoji: '🛥️', name: 'motor boat' },
	{ emoji: '🛳️', name: 'passenger ship cruise' },
	{ emoji: '⛴️', name: 'ferry' },
	{ emoji: '🚢', name: 'ship' },
	{ emoji: '⚓', name: 'anchor' },
	{ emoji: '🪝', name: 'hook' },
	{ emoji: '⛽', name: 'fuel pump gas' },
	{ emoji: '🚧', name: 'construction' },
	{ emoji: '🚦', name: 'vertical traffic light' },
	{ emoji: '🚥', name: 'horizontal traffic light' },
	{ emoji: '🗺️', name: 'world map' },
	{ emoji: '🗿', name: 'moai statue easter island' },
	{ emoji: '🗼', name: 'tokyo tower' },
	{ emoji: '🏰', name: 'castle european' },
	{ emoji: '🏯', name: 'japanese castle' },
	{ emoji: '🏟️', name: 'stadium' },
	{ emoji: '🎡', name: 'ferris wheel' },
	{ emoji: '🎢', name: 'roller coaster' },
	{ emoji: '🎠', name: 'carousel horse' },
	{ emoji: '⛲', name: 'fountain' },
	{ emoji: '⛱️', name: 'umbrella ground beach' },
	{ emoji: '🏖️', name: 'beach umbrella sand' },
	{ emoji: '🏝️', name: 'desert island' },
	{ emoji: '🏜️', name: 'desert' },
	{ emoji: '🌋', name: 'volcano' },
	{ emoji: '⛰️', name: 'mountain' },
	{ emoji: '🏔️', name: 'snow capped mountain' },
	{ emoji: '🗻', name: 'mount fuji' },
	{ emoji: '🏕️', name: 'camping tent' },
	{ emoji: '⛺', name: 'tent' },
	{ emoji: '🏠', name: 'house building home' },
	{ emoji: '🏡', name: 'house garden' },
	{ emoji: '🏘️', name: 'houses neighborhood' },
	{ emoji: '🏗️', name: 'building construction crane' },
	{ emoji: '🏭', name: 'factory industrial' },
	{ emoji: '🏢', name: 'office building' },
	{ emoji: '🏬', name: 'department store' },
	{ emoji: '🏣', name: 'japanese post office' },
	{ emoji: '🏤', name: 'post office' },
	{ emoji: '🏥', name: 'hospital' },
	{ emoji: '🏦', name: 'bank' },
	{ emoji: '🏨', name: 'hotel' },
	{ emoji: '🏪', name: 'convenience store' },
	{ emoji: '🏫', name: 'school' },
	{ emoji: '🏩', name: 'love hotel' },
	{ emoji: '💒', name: 'wedding church' },
	{ emoji: '🏛️', name: 'classical building' },
	{ emoji: '⛪', name: 'church' },
	{ emoji: '🕌', name: 'mosque' },
	{ emoji: '🕍', name: 'synagogue' },
	{ emoji: '🛕', name: 'hindu temple' },
	{ emoji: '🕋', name: 'kaaba' },
	{ emoji: '⛩️', name: 'shinto shrine torii' },
	{ emoji: '🛤️', name: 'railway track' },
	{ emoji: '🛣️', name: 'motorway highway' },
	{ emoji: '🗾', name: 'map japan' },
	{ emoji: '🎑', name: 'moon viewing ceremony' },
	{ emoji: '🏞️', name: 'national park' },
	{ emoji: '🌅', name: 'sunrise' },
	{ emoji: '🌄', name: 'sunrise mountains' },
	{ emoji: '🌠', name: 'shooting star' },
	{ emoji: '🎇', name: 'sparkler firework' },
	{ emoji: '🎆', name: 'fireworks' },
	{ emoji: '🌇', name: 'sunset' },
	{ emoji: '🌆', name: 'cityscape dusk' },
	{ emoji: '🏙️', name: 'cityscape skyline' },
	{ emoji: '🌃', name: 'night stars city' },
	{ emoji: '🌌', name: 'milky way galaxy' },
	{ emoji: '🌉', name: 'bridge night' },
	{ emoji: '🌁', name: 'foggy' },
];
