/**
 * Category Seed — official taxonomy data shipped with the app.
 *
 * This constant is used ONLY for initial population.
 * At runtime, all category data comes from IndexedDB.
 *
 * If the taxonomy changes during development, delete the local DB and reload.
 */

import type { Category, CategoryTreeId } from './category.js';

type SeedCategory = Omit<Category, 'isActive'>;

// ── Subject Tree ───────────────────────────────────────────────────────

const subjectTree: SeedCategory[] = [
	// Technology
	{ id: 'subj-tech',          label: 'Technology',           treeId: 'subject', parentId: null,            depth: 0, order: 0, isSystem: true },
	{ id: 'subj-tech-oss',      label: 'Open Source',          treeId: 'subject', parentId: 'subj-tech',     depth: 1, order: 0, isSystem: true },
	{ id: 'subj-tech-webdev',   label: 'Web Development',      treeId: 'subject', parentId: 'subj-tech',     depth: 1, order: 1, isSystem: true },
	{ id: 'subj-tech-ai',       label: 'Artificial Intelligence', treeId: 'subject', parentId: 'subj-tech',  depth: 1, order: 2, isSystem: true },
	{ id: 'subj-tech-security', label: 'Security',             treeId: 'subject', parentId: 'subj-tech',     depth: 1, order: 3, isSystem: true },
	{ id: 'subj-tech-mobile',   label: 'Mobile',               treeId: 'subject', parentId: 'subj-tech',     depth: 1, order: 4, isSystem: true },
	{ id: 'subj-tech-devops',   label: 'DevOps & Infra',       treeId: 'subject', parentId: 'subj-tech',     depth: 1, order: 5, isSystem: true },

	// Science
	{ id: 'subj-science',       label: 'Science',              treeId: 'subject', parentId: null,            depth: 0, order: 1, isSystem: true },
	{ id: 'subj-science-phys',  label: 'Physics',              treeId: 'subject', parentId: 'subj-science',  depth: 1, order: 0, isSystem: true },
	{ id: 'subj-science-bio',   label: 'Biology',              treeId: 'subject', parentId: 'subj-science',  depth: 1, order: 1, isSystem: true },
	{ id: 'subj-science-space', label: 'Space & Astronomy',    treeId: 'subject', parentId: 'subj-science',  depth: 1, order: 2, isSystem: true },

	// Politics
	{ id: 'subj-politics',       label: 'Politics',            treeId: 'subject', parentId: null,              depth: 0, order: 2, isSystem: true },
	{ id: 'subj-politics-natl',  label: 'National Politics',   treeId: 'subject', parentId: 'subj-politics',  depth: 1, order: 0, isSystem: true },
	{ id: 'subj-politics-intl',  label: 'International Politics', treeId: 'subject', parentId: 'subj-politics', depth: 1, order: 1, isSystem: true },

	// Economy
	{ id: 'subj-economy',        label: 'Economy',             treeId: 'subject', parentId: null,             depth: 0, order: 3, isSystem: true },
	{ id: 'subj-economy-finance', label: 'Finance & Markets',  treeId: 'subject', parentId: 'subj-economy',  depth: 1, order: 0, isSystem: true },
	{ id: 'subj-economy-crypto', label: 'Crypto & Web3',       treeId: 'subject', parentId: 'subj-economy',  depth: 1, order: 1, isSystem: true },
	{ id: 'subj-economy-startup', label: 'Startups',           treeId: 'subject', parentId: 'subj-economy',  depth: 1, order: 2, isSystem: true },

	// Culture
	{ id: 'subj-culture',         label: 'Culture',            treeId: 'subject', parentId: null,             depth: 0, order: 4, isSystem: true },
	{ id: 'subj-culture-gaming',  label: 'Gaming',             treeId: 'subject', parentId: 'subj-culture',  depth: 1, order: 0, isSystem: true },
	{ id: 'subj-culture-music',   label: 'Music',              treeId: 'subject', parentId: 'subj-culture',  depth: 1, order: 1, isSystem: true },
	{ id: 'subj-culture-film',    label: 'Film & TV',          treeId: 'subject', parentId: 'subj-culture',  depth: 1, order: 2, isSystem: true },
	{ id: 'subj-culture-books',   label: 'Books & Literature', treeId: 'subject', parentId: 'subj-culture',  depth: 1, order: 3, isSystem: true },

	// Health
	{ id: 'subj-health',          label: 'Health',             treeId: 'subject', parentId: null,             depth: 0, order: 5, isSystem: true },
	{ id: 'subj-health-fitness',  label: 'Fitness',            treeId: 'subject', parentId: 'subj-health',   depth: 1, order: 0, isSystem: true },
	{ id: 'subj-health-mental',   label: 'Mental Health',      treeId: 'subject', parentId: 'subj-health',   depth: 1, order: 1, isSystem: true },
	{ id: 'subj-health-nutrition', label: 'Nutrition',         treeId: 'subject', parentId: 'subj-health',   depth: 1, order: 2, isSystem: true },

	// Education
	{ id: 'subj-education',       label: 'Education',          treeId: 'subject', parentId: null,             depth: 0, order: 6, isSystem: true },
	{ id: 'subj-education-lang',  label: 'Languages',          treeId: 'subject', parentId: 'subj-education', depth: 1, order: 0, isSystem: true },
	{ id: 'subj-education-math',  label: 'Mathematics',        treeId: 'subject', parentId: 'subj-education', depth: 1, order: 1, isSystem: true }
];

// ── Content Type Tree ──────────────────────────────────────────────────

const contentTypeTree: SeedCategory[] = [
	// Format
	{ id: 'ct-format',           label: 'Format',              treeId: 'content_type', parentId: null,          depth: 0, order: 0, isSystem: true },
	{ id: 'ct-format-news',      label: 'News',                treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 0, isSystem: true },
	{ id: 'ct-format-analysis',  label: 'Analysis',            treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 1, isSystem: true },
	{ id: 'ct-format-research',  label: 'Research',            treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 2, isSystem: true },
	{ id: 'ct-format-tutorial',  label: 'Tutorial',            treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 3, isSystem: true },
	{ id: 'ct-format-opinion',   label: 'Opinion',             treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 4, isSystem: true },
	{ id: 'ct-format-review',    label: 'Review',              treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 5, isSystem: true },
	{ id: 'ct-format-interview', label: 'Interview',           treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 6, isSystem: true },
	{ id: 'ct-format-podcast',   label: 'Podcast',             treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 7, isSystem: true },
	{ id: 'ct-format-video',     label: 'Video',               treeId: 'content_type', parentId: 'ct-format',   depth: 1, order: 8, isSystem: true }
];

// ── Region Tree ────────────────────────────────────────────────────────

const regionTree: SeedCategory[] = [
	// World
	{ id: 'reg-world',           label: 'World',               treeId: 'region', parentId: null,              depth: 0, order: 0, isSystem: true },
	{ id: 'reg-world-earth',     label: 'Earth',               treeId: 'region', parentId: 'reg-world',       depth: 1, order: 0, isSystem: true },
	{ id: 'reg-world-moon',      label: 'Moon',                treeId: 'region', parentId: 'reg-world',       depth: 1, order: 1, isSystem: true },
	{ id: 'reg-world-mars',      label: 'Mars',                treeId: 'region', parentId: 'reg-world',       depth: 1, order: 2, isSystem: true },
	{ id: 'reg-world-venus',     label: 'Venus',               treeId: 'region', parentId: 'reg-world',       depth: 1, order: 3, isSystem: true },
	{ id: 'reg-world-mercury',   label: 'Mercury',             treeId: 'region', parentId: 'reg-world',       depth: 1, order: 4, isSystem: true },
	{ id: 'reg-world-jupiter',   label: 'Jupiter',             treeId: 'region', parentId: 'reg-world',       depth: 1, order: 5, isSystem: true },
	{ id: 'reg-world-saturn',    label: 'Saturn',              treeId: 'region', parentId: 'reg-world',       depth: 1, order: 6, isSystem: true },
	{ id: 'reg-world-uranus',    label: 'Uranus',              treeId: 'region', parentId: 'reg-world',       depth: 1, order: 7, isSystem: true },
	{ id: 'reg-world-neptune',   label: 'Neptune',             treeId: 'region', parentId: 'reg-world',       depth: 1, order: 8, isSystem: true },

	// Continent
	{ id: 'reg-cont',            label: 'Continent',           treeId: 'region', parentId: null,              depth: 0, order: 1, isSystem: true },
	{ id: 'reg-cont-africa',     label: 'Africa',              treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 0, isSystem: true },
	{ id: 'reg-cont-namerica',   label: 'North America',       treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 1, isSystem: true },
	{ id: 'reg-cont-camerica',   label: 'Central America',     treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 2, isSystem: true },
	{ id: 'reg-cont-samerica',   label: 'South America',       treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 3, isSystem: true },
	{ id: 'reg-cont-europe',     label: 'Europe',              treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 4, isSystem: true },
	{ id: 'reg-cont-asia',       label: 'Asia',                treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 5, isSystem: true },
	{ id: 'reg-cont-oceania',    label: 'Oceania',             treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 6, isSystem: true },
	{ id: 'reg-cont-antarctica', label: 'Antarctica',          treeId: 'region', parentId: 'reg-cont',        depth: 1, order: 7, isSystem: true },

	// Country
	{ id: 'reg-country',         label: 'Country',             treeId: 'region', parentId: null,              depth: 0, order: 2, isSystem: true },
	{ id: 'reg-country-af',      label: 'Afghanistan',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 0, isSystem: true },
	{ id: 'reg-country-al',      label: 'Albania',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 1, isSystem: true },
	{ id: 'reg-country-dz',      label: 'Algeria',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 2, isSystem: true },
	{ id: 'reg-country-ad',      label: 'Andorra',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 3, isSystem: true },
	{ id: 'reg-country-ao',      label: 'Angola',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 4, isSystem: true },
	{ id: 'reg-country-ag',      label: 'Antigua and Barbuda', treeId: 'region', parentId: 'reg-country',     depth: 1, order: 5, isSystem: true },
	{ id: 'reg-country-ar',      label: 'Argentina',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 6, isSystem: true },
	{ id: 'reg-country-am',      label: 'Armenia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 7, isSystem: true },
	{ id: 'reg-country-au',      label: 'Australia',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 8, isSystem: true },
	{ id: 'reg-country-at',      label: 'Austria',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 9, isSystem: true },
	{ id: 'reg-country-az',      label: 'Azerbaijan',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 10, isSystem: true },
	{ id: 'reg-country-bs',      label: 'Bahamas',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 11, isSystem: true },
	{ id: 'reg-country-bh',      label: 'Bahrain',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 12, isSystem: true },
	{ id: 'reg-country-bd',      label: 'Bangladesh',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 13, isSystem: true },
	{ id: 'reg-country-bb',      label: 'Barbados',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 14, isSystem: true },
	{ id: 'reg-country-by',      label: 'Belarus',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 15, isSystem: true },
	{ id: 'reg-country-be',      label: 'Belgium',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 16, isSystem: true },
	{ id: 'reg-country-bz',      label: 'Belize',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 17, isSystem: true },
	{ id: 'reg-country-bj',      label: 'Benin',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 18, isSystem: true },
	{ id: 'reg-country-bt',      label: 'Bhutan',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 19, isSystem: true },
	{ id: 'reg-country-bo',      label: 'Bolivia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 20, isSystem: true },
	{ id: 'reg-country-ba',      label: 'Bosnia and Herzegovina', treeId: 'region', parentId: 'reg-country',  depth: 1, order: 21, isSystem: true },
	{ id: 'reg-country-bw',      label: 'Botswana',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 22, isSystem: true },
	{ id: 'reg-country-br',      label: 'Brazil',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 23, isSystem: true },
	{ id: 'reg-country-bn',      label: 'Brunei',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 24, isSystem: true },
	{ id: 'reg-country-bg',      label: 'Bulgaria',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 25, isSystem: true },
	{ id: 'reg-country-bf',      label: 'Burkina Faso',        treeId: 'region', parentId: 'reg-country',     depth: 1, order: 26, isSystem: true },
	{ id: 'reg-country-bi',      label: 'Burundi',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 27, isSystem: true },
	{ id: 'reg-country-cv',      label: 'Cabo Verde',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 28, isSystem: true },
	{ id: 'reg-country-kh',      label: 'Cambodia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 29, isSystem: true },
	{ id: 'reg-country-cm',      label: 'Cameroon',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 30, isSystem: true },
	{ id: 'reg-country-ca',      label: 'Canada',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 31, isSystem: true },
	{ id: 'reg-country-cf',      label: 'Central African Republic', treeId: 'region', parentId: 'reg-country', depth: 1, order: 32, isSystem: true },
	{ id: 'reg-country-td',      label: 'Chad',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 33, isSystem: true },
	{ id: 'reg-country-cl',      label: 'Chile',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 34, isSystem: true },
	{ id: 'reg-country-cn',      label: 'China',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 35, isSystem: true },
	{ id: 'reg-country-co',      label: 'Colombia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 36, isSystem: true },
	{ id: 'reg-country-km',      label: 'Comoros',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 37, isSystem: true },
	{ id: 'reg-country-cd',      label: 'Congo (DRC)',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 38, isSystem: true },
	{ id: 'reg-country-cg',      label: 'Congo (Republic)',    treeId: 'region', parentId: 'reg-country',     depth: 1, order: 39, isSystem: true },
	{ id: 'reg-country-cr',      label: 'Costa Rica',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 40, isSystem: true },
	{ id: 'reg-country-ci',      label: "Côte d'Ivoire",       treeId: 'region', parentId: 'reg-country',     depth: 1, order: 41, isSystem: true },
	{ id: 'reg-country-hr',      label: 'Croatia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 42, isSystem: true },
	{ id: 'reg-country-cu',      label: 'Cuba',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 43, isSystem: true },
	{ id: 'reg-country-cy',      label: 'Cyprus',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 44, isSystem: true },
	{ id: 'reg-country-cz',      label: 'Czechia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 45, isSystem: true },
	{ id: 'reg-country-dk',      label: 'Denmark',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 46, isSystem: true },
	{ id: 'reg-country-dj',      label: 'Djibouti',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 47, isSystem: true },
	{ id: 'reg-country-dm',      label: 'Dominica',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 48, isSystem: true },
	{ id: 'reg-country-do',      label: 'Dominican Republic',  treeId: 'region', parentId: 'reg-country',     depth: 1, order: 49, isSystem: true },
	{ id: 'reg-country-ec',      label: 'Ecuador',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 50, isSystem: true },
	{ id: 'reg-country-eg',      label: 'Egypt',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 51, isSystem: true },
	{ id: 'reg-country-sv',      label: 'El Salvador',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 52, isSystem: true },
	{ id: 'reg-country-gq',      label: 'Equatorial Guinea',   treeId: 'region', parentId: 'reg-country',     depth: 1, order: 53, isSystem: true },
	{ id: 'reg-country-er',      label: 'Eritrea',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 54, isSystem: true },
	{ id: 'reg-country-ee',      label: 'Estonia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 55, isSystem: true },
	{ id: 'reg-country-sz',      label: 'Eswatini',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 56, isSystem: true },
	{ id: 'reg-country-et',      label: 'Ethiopia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 57, isSystem: true },
	{ id: 'reg-country-fj',      label: 'Fiji',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 58, isSystem: true },
	{ id: 'reg-country-fi',      label: 'Finland',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 59, isSystem: true },
	{ id: 'reg-country-fr',      label: 'France',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 60, isSystem: true },
	{ id: 'reg-country-ga',      label: 'Gabon',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 61, isSystem: true },
	{ id: 'reg-country-gm',      label: 'Gambia',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 62, isSystem: true },
	{ id: 'reg-country-ge',      label: 'Georgia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 63, isSystem: true },
	{ id: 'reg-country-de',      label: 'Germany',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 64, isSystem: true },
	{ id: 'reg-country-gh',      label: 'Ghana',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 65, isSystem: true },
	{ id: 'reg-country-gr',      label: 'Greece',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 66, isSystem: true },
	{ id: 'reg-country-gd',      label: 'Grenada',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 67, isSystem: true },
	{ id: 'reg-country-gt',      label: 'Guatemala',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 68, isSystem: true },
	{ id: 'reg-country-gn',      label: 'Guinea',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 69, isSystem: true },
	{ id: 'reg-country-gw',      label: 'Guinea-Bissau',       treeId: 'region', parentId: 'reg-country',     depth: 1, order: 70, isSystem: true },
	{ id: 'reg-country-gy',      label: 'Guyana',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 71, isSystem: true },
	{ id: 'reg-country-ht',      label: 'Haiti',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 72, isSystem: true },
	{ id: 'reg-country-hn',      label: 'Honduras',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 73, isSystem: true },
	{ id: 'reg-country-hu',      label: 'Hungary',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 74, isSystem: true },
	{ id: 'reg-country-is',      label: 'Iceland',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 75, isSystem: true },
	{ id: 'reg-country-in',      label: 'India',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 76, isSystem: true },
	{ id: 'reg-country-id',      label: 'Indonesia',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 77, isSystem: true },
	{ id: 'reg-country-ir',      label: 'Iran',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 78, isSystem: true },
	{ id: 'reg-country-iq',      label: 'Iraq',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 79, isSystem: true },
	{ id: 'reg-country-ie',      label: 'Ireland',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 80, isSystem: true },
	{ id: 'reg-country-il',      label: 'Israel',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 81, isSystem: true },
	{ id: 'reg-country-it',      label: 'Italy',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 82, isSystem: true },
	{ id: 'reg-country-jm',      label: 'Jamaica',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 83, isSystem: true },
	{ id: 'reg-country-jp',      label: 'Japan',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 84, isSystem: true },
	{ id: 'reg-country-jo',      label: 'Jordan',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 85, isSystem: true },
	{ id: 'reg-country-kz',      label: 'Kazakhstan',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 86, isSystem: true },
	{ id: 'reg-country-ke',      label: 'Kenya',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 87, isSystem: true },
	{ id: 'reg-country-ki',      label: 'Kiribati',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 88, isSystem: true },
	{ id: 'reg-country-kp',      label: 'North Korea',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 89, isSystem: true },
	{ id: 'reg-country-kr',      label: 'South Korea',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 90, isSystem: true },
	{ id: 'reg-country-xk',      label: 'Kosovo',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 91, isSystem: true },
	{ id: 'reg-country-kw',      label: 'Kuwait',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 92, isSystem: true },
	{ id: 'reg-country-kg',      label: 'Kyrgyzstan',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 93, isSystem: true },
	{ id: 'reg-country-la',      label: 'Laos',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 94, isSystem: true },
	{ id: 'reg-country-lv',      label: 'Latvia',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 95, isSystem: true },
	{ id: 'reg-country-lb',      label: 'Lebanon',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 96, isSystem: true },
	{ id: 'reg-country-ls',      label: 'Lesotho',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 97, isSystem: true },
	{ id: 'reg-country-lr',      label: 'Liberia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 98, isSystem: true },
	{ id: 'reg-country-ly',      label: 'Libya',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 99, isSystem: true },
	{ id: 'reg-country-li',      label: 'Liechtenstein',       treeId: 'region', parentId: 'reg-country',     depth: 1, order: 100, isSystem: true },
	{ id: 'reg-country-lt',      label: 'Lithuania',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 101, isSystem: true },
	{ id: 'reg-country-lu',      label: 'Luxembourg',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 102, isSystem: true },
	{ id: 'reg-country-mg',      label: 'Madagascar',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 103, isSystem: true },
	{ id: 'reg-country-mw',      label: 'Malawi',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 104, isSystem: true },
	{ id: 'reg-country-my',      label: 'Malaysia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 105, isSystem: true },
	{ id: 'reg-country-mv',      label: 'Maldives',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 106, isSystem: true },
	{ id: 'reg-country-ml',      label: 'Mali',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 107, isSystem: true },
	{ id: 'reg-country-mt',      label: 'Malta',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 108, isSystem: true },
	{ id: 'reg-country-mh',      label: 'Marshall Islands',    treeId: 'region', parentId: 'reg-country',     depth: 1, order: 109, isSystem: true },
	{ id: 'reg-country-mr',      label: 'Mauritania',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 110, isSystem: true },
	{ id: 'reg-country-mu',      label: 'Mauritius',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 111, isSystem: true },
	{ id: 'reg-country-mx',      label: 'Mexico',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 112, isSystem: true },
	{ id: 'reg-country-fm',      label: 'Micronesia',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 113, isSystem: true },
	{ id: 'reg-country-md',      label: 'Moldova',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 114, isSystem: true },
	{ id: 'reg-country-mc',      label: 'Monaco',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 115, isSystem: true },
	{ id: 'reg-country-mn',      label: 'Mongolia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 116, isSystem: true },
	{ id: 'reg-country-me',      label: 'Montenegro',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 117, isSystem: true },
	{ id: 'reg-country-ma',      label: 'Morocco',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 118, isSystem: true },
	{ id: 'reg-country-mz',      label: 'Mozambique',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 119, isSystem: true },
	{ id: 'reg-country-mm',      label: 'Myanmar',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 120, isSystem: true },
	{ id: 'reg-country-na',      label: 'Namibia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 121, isSystem: true },
	{ id: 'reg-country-nr',      label: 'Nauru',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 122, isSystem: true },
	{ id: 'reg-country-np',      label: 'Nepal',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 123, isSystem: true },
	{ id: 'reg-country-nl',      label: 'Netherlands',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 124, isSystem: true },
	{ id: 'reg-country-nz',      label: 'New Zealand',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 125, isSystem: true },
	{ id: 'reg-country-ni',      label: 'Nicaragua',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 126, isSystem: true },
	{ id: 'reg-country-ne',      label: 'Niger',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 127, isSystem: true },
	{ id: 'reg-country-ng',      label: 'Nigeria',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 128, isSystem: true },
	{ id: 'reg-country-mk',      label: 'North Macedonia',     treeId: 'region', parentId: 'reg-country',     depth: 1, order: 129, isSystem: true },
	{ id: 'reg-country-no',      label: 'Norway',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 130, isSystem: true },
	{ id: 'reg-country-om',      label: 'Oman',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 131, isSystem: true },
	{ id: 'reg-country-pk',      label: 'Pakistan',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 132, isSystem: true },
	{ id: 'reg-country-pw',      label: 'Palau',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 133, isSystem: true },
	{ id: 'reg-country-ps',      label: 'Palestine',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 134, isSystem: true },
	{ id: 'reg-country-pa',      label: 'Panama',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 135, isSystem: true },
	{ id: 'reg-country-pg',      label: 'Papua New Guinea',    treeId: 'region', parentId: 'reg-country',     depth: 1, order: 136, isSystem: true },
	{ id: 'reg-country-py',      label: 'Paraguay',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 137, isSystem: true },
	{ id: 'reg-country-pe',      label: 'Peru',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 138, isSystem: true },
	{ id: 'reg-country-ph',      label: 'Philippines',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 139, isSystem: true },
	{ id: 'reg-country-pl',      label: 'Poland',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 140, isSystem: true },
	{ id: 'reg-country-pt',      label: 'Portugal',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 141, isSystem: true },
	{ id: 'reg-country-qa',      label: 'Qatar',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 142, isSystem: true },
	{ id: 'reg-country-ro',      label: 'Romania',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 143, isSystem: true },
	{ id: 'reg-country-ru',      label: 'Russia',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 144, isSystem: true },
	{ id: 'reg-country-rw',      label: 'Rwanda',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 145, isSystem: true },
	{ id: 'reg-country-kn',      label: 'Saint Kitts and Nevis', treeId: 'region', parentId: 'reg-country',   depth: 1, order: 146, isSystem: true },
	{ id: 'reg-country-lc',      label: 'Saint Lucia',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 147, isSystem: true },
	{ id: 'reg-country-vc',      label: 'Saint Vincent and the Grenadines', treeId: 'region', parentId: 'reg-country', depth: 1, order: 148, isSystem: true },
	{ id: 'reg-country-ws',      label: 'Samoa',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 149, isSystem: true },
	{ id: 'reg-country-sm',      label: 'San Marino',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 150, isSystem: true },
	{ id: 'reg-country-st',      label: 'São Tomé and Príncipe', treeId: 'region', parentId: 'reg-country',   depth: 1, order: 151, isSystem: true },
	{ id: 'reg-country-sa',      label: 'Saudi Arabia',        treeId: 'region', parentId: 'reg-country',     depth: 1, order: 152, isSystem: true },
	{ id: 'reg-country-sn',      label: 'Senegal',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 153, isSystem: true },
	{ id: 'reg-country-rs',      label: 'Serbia',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 154, isSystem: true },
	{ id: 'reg-country-sc',      label: 'Seychelles',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 155, isSystem: true },
	{ id: 'reg-country-sl',      label: 'Sierra Leone',        treeId: 'region', parentId: 'reg-country',     depth: 1, order: 156, isSystem: true },
	{ id: 'reg-country-sg',      label: 'Singapore',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 157, isSystem: true },
	{ id: 'reg-country-sk',      label: 'Slovakia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 158, isSystem: true },
	{ id: 'reg-country-si',      label: 'Slovenia',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 159, isSystem: true },
	{ id: 'reg-country-sb',      label: 'Solomon Islands',     treeId: 'region', parentId: 'reg-country',     depth: 1, order: 160, isSystem: true },
	{ id: 'reg-country-so',      label: 'Somalia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 161, isSystem: true },
	{ id: 'reg-country-za',      label: 'South Africa',        treeId: 'region', parentId: 'reg-country',     depth: 1, order: 162, isSystem: true },
	{ id: 'reg-country-ss',      label: 'South Sudan',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 163, isSystem: true },
	{ id: 'reg-country-es',      label: 'Spain',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 164, isSystem: true },
	{ id: 'reg-country-lk',      label: 'Sri Lanka',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 165, isSystem: true },
	{ id: 'reg-country-sd',      label: 'Sudan',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 166, isSystem: true },
	{ id: 'reg-country-sr',      label: 'Suriname',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 167, isSystem: true },
	{ id: 'reg-country-se',      label: 'Sweden',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 168, isSystem: true },
	{ id: 'reg-country-ch',      label: 'Switzerland',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 169, isSystem: true },
	{ id: 'reg-country-sy',      label: 'Syria',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 170, isSystem: true },
	{ id: 'reg-country-tw',      label: 'Taiwan',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 171, isSystem: true },
	{ id: 'reg-country-tj',      label: 'Tajikistan',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 172, isSystem: true },
	{ id: 'reg-country-tz',      label: 'Tanzania',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 173, isSystem: true },
	{ id: 'reg-country-th',      label: 'Thailand',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 174, isSystem: true },
	{ id: 'reg-country-tl',      label: 'Timor-Leste',         treeId: 'region', parentId: 'reg-country',     depth: 1, order: 175, isSystem: true },
	{ id: 'reg-country-tg',      label: 'Togo',                treeId: 'region', parentId: 'reg-country',     depth: 1, order: 176, isSystem: true },
	{ id: 'reg-country-to',      label: 'Tonga',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 177, isSystem: true },
	{ id: 'reg-country-tt',      label: 'Trinidad and Tobago', treeId: 'region', parentId: 'reg-country',     depth: 1, order: 178, isSystem: true },
	{ id: 'reg-country-tn',      label: 'Tunisia',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 179, isSystem: true },
	{ id: 'reg-country-tr',      label: 'Türkiye',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 180, isSystem: true },
	{ id: 'reg-country-tm',      label: 'Turkmenistan',        treeId: 'region', parentId: 'reg-country',     depth: 1, order: 181, isSystem: true },
	{ id: 'reg-country-tv',      label: 'Tuvalu',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 182, isSystem: true },
	{ id: 'reg-country-ug',      label: 'Uganda',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 183, isSystem: true },
	{ id: 'reg-country-ua',      label: 'Ukraine',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 184, isSystem: true },
	{ id: 'reg-country-ae',      label: 'United Arab Emirates', treeId: 'region', parentId: 'reg-country',    depth: 1, order: 185, isSystem: true },
	{ id: 'reg-country-gb',      label: 'United Kingdom',      treeId: 'region', parentId: 'reg-country',     depth: 1, order: 186, isSystem: true },
	{ id: 'reg-country-us',      label: 'United States',       treeId: 'region', parentId: 'reg-country',     depth: 1, order: 187, isSystem: true },
	{ id: 'reg-country-uy',      label: 'Uruguay',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 188, isSystem: true },
	{ id: 'reg-country-uz',      label: 'Uzbekistan',          treeId: 'region', parentId: 'reg-country',     depth: 1, order: 189, isSystem: true },
	{ id: 'reg-country-vu',      label: 'Vanuatu',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 190, isSystem: true },
	{ id: 'reg-country-va',      label: 'Vatican City',        treeId: 'region', parentId: 'reg-country',     depth: 1, order: 191, isSystem: true },
	{ id: 'reg-country-ve',      label: 'Venezuela',           treeId: 'region', parentId: 'reg-country',     depth: 1, order: 192, isSystem: true },
	{ id: 'reg-country-vn',      label: 'Vietnam',             treeId: 'region', parentId: 'reg-country',     depth: 1, order: 193, isSystem: true },
	{ id: 'reg-country-ye',      label: 'Yemen',               treeId: 'region', parentId: 'reg-country',     depth: 1, order: 194, isSystem: true },
	{ id: 'reg-country-zm',      label: 'Zambia',              treeId: 'region', parentId: 'reg-country',     depth: 1, order: 195, isSystem: true },
	{ id: 'reg-country-zw',      label: 'Zimbabwe',            treeId: 'region', parentId: 'reg-country',     depth: 1, order: 196, isSystem: true },
];

// ── Full seed ──────────────────────────────────────────────────────────

export const CATEGORY_SEED: SeedCategory[] = [...subjectTree, ...contentTypeTree, ...regionTree];
