/**
 * Region Seed — geographic taxonomy (World / UN M49 macro-regions / ISO 3166-1 standard).
 *
 * The macro-region hierarchy follows the UN M49 standard:
 * https://unstats.un.org/unsd/methodology/m49/
 *
 * The country hierarchy follows the ISO 3166-1 standard:
 * https://www.iso.org/iso-3166-country-codes.html
 */

import type { SeedCategory } from './category-seed.js';

export const regionSeed: SeedCategory[] = [

	// ── Macro-region (UN M49) ──────────────────────────────────────────────
	{ id: 'da',                label: 'Macro-region',               treeId: 'region', parentId: null,           depth: 0, order: 1, isSystem: true },

	// Africa (002)
	{ id: 'daa',              label: 'Africa',                    treeId: 'region', parentId: 'da',          depth: 1, order: 0, isSystem: true },
	{ id: 'daaaa',     label: 'Northern Africa',           treeId: 'region', parentId: 'daa',   depth: 2, order: 0, isSystem: true },
	{ id: 'daaab',      label: 'Eastern Africa',            treeId: 'region', parentId: 'daa',   depth: 2, order: 1, isSystem: true },
	{ id: 'daaac',       label: 'Middle Africa',             treeId: 'region', parentId: 'daa',   depth: 2, order: 2, isSystem: true },
	{ id: 'daaad',     label: 'Southern Africa',           treeId: 'region', parentId: 'daa',   depth: 2, order: 3, isSystem: true },
	{ id: 'daaae',      label: 'Western Africa',            treeId: 'region', parentId: 'daa',   depth: 2, order: 4, isSystem: true },

	// Americas (019)
	{ id: 'dab',            label: 'Americas',                  treeId: 'region', parentId: 'da',            depth: 1, order: 1, isSystem: true },
	{ id: 'dabaa',   label: 'Northern America',          treeId: 'region', parentId: 'dab',   depth: 2, order: 0, isSystem: true },
	{ id: 'dabab',  label: 'Caribbean',                 treeId: 'region', parentId: 'dab',   depth: 2, order: 1, isSystem: true },
	{ id: 'dabac',    label: 'Central America',           treeId: 'region', parentId: 'dab',   depth: 2, order: 2, isSystem: true },
	{ id: 'dabad',      label: 'South America',             treeId: 'region', parentId: 'dab',   depth: 2, order: 3, isSystem: true },

	// Asia (142)
	{ id: 'dac',                label: 'Asia',                      treeId: 'region', parentId: 'da',         depth: 1, order: 2, isSystem: true },
	{ id: 'dacaa',        label: 'Central Asia',              treeId: 'region', parentId: 'dac',    depth: 2, order: 0, isSystem: true },
	{ id: 'dacab',        label: 'Eastern Asia',              treeId: 'region', parentId: 'dac',    depth: 2, order: 1, isSystem: true },
	{ id: 'dacac',   label: 'South-eastern Asia',        treeId: 'region', parentId: 'dac',    depth: 2, order: 2, isSystem: true },
	{ id: 'dacad',       label: 'Southern Asia',             treeId: 'region', parentId: 'dac',    depth: 2, order: 3, isSystem: true },
	{ id: 'dacae',        label: 'Western Asia',              treeId: 'region', parentId: 'dac',    depth: 2, order: 4, isSystem: true },

	// Europe (150)
	{ id: 'dad',              label: 'Europe',                    treeId: 'region', parentId: 'da',           depth: 1, order: 3, isSystem: true },
	{ id: 'dadaa',      label: 'Eastern Europe',            treeId: 'region', parentId: 'dad',    depth: 2, order: 0, isSystem: true },
	{ id: 'dadab',     label: 'Northern Europe',           treeId: 'region', parentId: 'dad',    depth: 2, order: 1, isSystem: true },
	{ id: 'dadac',     label: 'Southern Europe',           treeId: 'region', parentId: 'dad',    depth: 2, order: 2, isSystem: true },
	{ id: 'dadad',      label: 'Western Europe',            treeId: 'region', parentId: 'dad',    depth: 2, order: 3, isSystem: true },

	// Oceania (009)
	{ id: 'dae',             label: 'Oceania',                   treeId: 'region', parentId: 'da',            depth: 1, order: 4, isSystem: true },
	{ id: 'daeaa',        label: 'Australia and New Zealand', treeId: 'region', parentId: 'dae',    depth: 2, order: 0, isSystem: true },
	{ id: 'daeab',   label: 'Melanesia',                 treeId: 'region', parentId: 'dae',    depth: 2, order: 1, isSystem: true },
	{ id: 'daeac',  label: 'Micronesia',                treeId: 'region', parentId: 'dae',    depth: 2, order: 2, isSystem: true },
	{ id: 'daead',   label: 'Polynesia',                 treeId: 'region', parentId: 'dae',    depth: 2, order: 3, isSystem: true },

	// ── Country (ISO 3166-1) ──────────────────────────────────────────────
	{ id: 'db',             label: 'Country',                   treeId: 'region', parentId: null,                 depth: 0, order: 2, isSystem: true },

	// Sovereign States
	{ id: 'dba',   label: 'Sovereign States',          treeId: 'region', parentId: 'db',         depth: 1, order: 0, isSystem: true },
	{ id: 'dbaaa',      label: 'Afghanistan',                   treeId: 'region', parentId: 'dba', depth: 2, order: 0,   isSystem: true },
	{ id: 'dbaab',      label: 'Albania',                       treeId: 'region', parentId: 'dba', depth: 2, order: 1,   isSystem: true },
	{ id: 'dbaac',      label: 'Algeria',                       treeId: 'region', parentId: 'dba', depth: 2, order: 2,   isSystem: true },
	{ id: 'dbaad',      label: 'Andorra',                       treeId: 'region', parentId: 'dba', depth: 2, order: 3,   isSystem: true },
	{ id: 'dbaae',      label: 'Angola',                        treeId: 'region', parentId: 'dba', depth: 2, order: 4,   isSystem: true },
	{ id: 'dbaaf',      label: 'Antigua and Barbuda',           treeId: 'region', parentId: 'dba', depth: 2, order: 5,   isSystem: true },
	{ id: 'dbaag',      label: 'Argentina',                     treeId: 'region', parentId: 'dba', depth: 2, order: 6,   isSystem: true },
	{ id: 'dbaah',      label: 'Armenia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 7,   isSystem: true },
	{ id: 'dbaai',      label: 'Australia',                     treeId: 'region', parentId: 'dba', depth: 2, order: 8,   isSystem: true },
	{ id: 'dbaaj',      label: 'Austria',                       treeId: 'region', parentId: 'dba', depth: 2, order: 9,   isSystem: true },
	{ id: 'dbaak',      label: 'Azerbaijan',                    treeId: 'region', parentId: 'dba', depth: 2, order: 10,  isSystem: true },
	{ id: 'dbaal',      label: 'Bahamas',                       treeId: 'region', parentId: 'dba', depth: 2, order: 11,  isSystem: true },
	{ id: 'dbaam',      label: 'Bahrain',                       treeId: 'region', parentId: 'dba', depth: 2, order: 12,  isSystem: true },
	{ id: 'dbaan',      label: 'Bangladesh',                    treeId: 'region', parentId: 'dba', depth: 2, order: 13,  isSystem: true },
	{ id: 'dbaao',      label: 'Barbados',                      treeId: 'region', parentId: 'dba', depth: 2, order: 14,  isSystem: true },
	{ id: 'dbaap',      label: 'Belarus',                       treeId: 'region', parentId: 'dba', depth: 2, order: 15,  isSystem: true },
	{ id: 'dbaaq',      label: 'Belgium',                       treeId: 'region', parentId: 'dba', depth: 2, order: 16,  isSystem: true },
	{ id: 'dbaar',      label: 'Belize',                        treeId: 'region', parentId: 'dba', depth: 2, order: 17,  isSystem: true },
	{ id: 'dbaas',      label: 'Benin',                         treeId: 'region', parentId: 'dba', depth: 2, order: 18,  isSystem: true },
	{ id: 'dbaat',      label: 'Bhutan',                        treeId: 'region', parentId: 'dba', depth: 2, order: 19,  isSystem: true },
	{ id: 'dbaau',      label: 'Bolivia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 20,  isSystem: true },
	{ id: 'dbaav',      label: 'Bosnia and Herzegovina',        treeId: 'region', parentId: 'dba', depth: 2, order: 21,  isSystem: true },
	{ id: 'dbaaw',      label: 'Botswana',                      treeId: 'region', parentId: 'dba', depth: 2, order: 22,  isSystem: true },
	{ id: 'dbaax',      label: 'Brazil',                        treeId: 'region', parentId: 'dba', depth: 2, order: 23,  isSystem: true },
	{ id: 'dbaay',      label: 'Brunei',                        treeId: 'region', parentId: 'dba', depth: 2, order: 24,  isSystem: true },
	{ id: 'dbaaz',      label: 'Bulgaria',                      treeId: 'region', parentId: 'dba', depth: 2, order: 25,  isSystem: true },
	{ id: 'dbaaA',      label: 'Burkina Faso',                  treeId: 'region', parentId: 'dba', depth: 2, order: 26,  isSystem: true },
	{ id: 'dbaaB',      label: 'Burundi',                       treeId: 'region', parentId: 'dba', depth: 2, order: 27,  isSystem: true },
	{ id: 'dbaaC',      label: 'Cabo Verde',                    treeId: 'region', parentId: 'dba', depth: 2, order: 28,  isSystem: true },
	{ id: 'dbaaD',      label: 'Cambodia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 29,  isSystem: true },
	{ id: 'dbaaE',      label: 'Cameroon',                      treeId: 'region', parentId: 'dba', depth: 2, order: 30,  isSystem: true },
	{ id: 'dbaaF',      label: 'Canada',                        treeId: 'region', parentId: 'dba', depth: 2, order: 31,  isSystem: true },
	{ id: 'dbaaG',      label: 'Central African Republic',      treeId: 'region', parentId: 'dba', depth: 2, order: 32,  isSystem: true },
	{ id: 'dbaaH',      label: 'Chad',                          treeId: 'region', parentId: 'dba', depth: 2, order: 33,  isSystem: true },
	{ id: 'dbaaI',      label: 'Chile',                         treeId: 'region', parentId: 'dba', depth: 2, order: 34,  isSystem: true },
	{ id: 'dbaaJ',      label: 'China',                         treeId: 'region', parentId: 'dba', depth: 2, order: 35,  isSystem: true },
	{ id: 'dbaaK',      label: 'Colombia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 36,  isSystem: true },
	{ id: 'dbaaL',      label: 'Comoros',                       treeId: 'region', parentId: 'dba', depth: 2, order: 37,  isSystem: true },
	{ id: 'dbaaM',      label: 'Congo (DRC)',                   treeId: 'region', parentId: 'dba', depth: 2, order: 38,  isSystem: true },
	{ id: 'dbaaN',      label: 'Congo (Republic)',              treeId: 'region', parentId: 'dba', depth: 2, order: 39,  isSystem: true },
	{ id: 'dbaaO',      label: 'Costa Rica',                    treeId: 'region', parentId: 'dba', depth: 2, order: 40,  isSystem: true },
	{ id: 'dbaaP',      label: "Côte d'Ivoire",                 treeId: 'region', parentId: 'dba', depth: 2, order: 41,  isSystem: true },
	{ id: 'dbaaQ',      label: 'Croatia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 42,  isSystem: true },
	{ id: 'dbaaR',      label: 'Cuba',                          treeId: 'region', parentId: 'dba', depth: 2, order: 43,  isSystem: true },
	{ id: 'dbaaS',      label: 'Cyprus',                        treeId: 'region', parentId: 'dba', depth: 2, order: 44,  isSystem: true },
	{ id: 'dbaaT',      label: 'Czechia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 45,  isSystem: true },
	{ id: 'dbaaU',      label: 'Denmark',                       treeId: 'region', parentId: 'dba', depth: 2, order: 46,  isSystem: true },
	{ id: 'dbaaV',      label: 'Djibouti',                      treeId: 'region', parentId: 'dba', depth: 2, order: 47,  isSystem: true },
	{ id: 'dbaaW',      label: 'Dominica',                      treeId: 'region', parentId: 'dba', depth: 2, order: 48,  isSystem: true },
	{ id: 'dbaaX',      label: 'Dominican Republic',            treeId: 'region', parentId: 'dba', depth: 2, order: 49,  isSystem: true },
	{ id: 'dbaaY',      label: 'Ecuador',                       treeId: 'region', parentId: 'dba', depth: 2, order: 50,  isSystem: true },
	{ id: 'dbaaZ',      label: 'Egypt',                         treeId: 'region', parentId: 'dba', depth: 2, order: 51,  isSystem: true },
	{ id: 'dbaba',      label: 'El Salvador',                   treeId: 'region', parentId: 'dba', depth: 2, order: 52,  isSystem: true },
	{ id: 'dbabb',      label: 'Equatorial Guinea',             treeId: 'region', parentId: 'dba', depth: 2, order: 53,  isSystem: true },
	{ id: 'dbabc',      label: 'Eritrea',                       treeId: 'region', parentId: 'dba', depth: 2, order: 54,  isSystem: true },
	{ id: 'dbabd',      label: 'Estonia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 55,  isSystem: true },
	{ id: 'dbabe',      label: 'Eswatini',                      treeId: 'region', parentId: 'dba', depth: 2, order: 56,  isSystem: true },
	{ id: 'dbabf',      label: 'Ethiopia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 57,  isSystem: true },
	{ id: 'dbabg',      label: 'Fiji',                          treeId: 'region', parentId: 'dba', depth: 2, order: 58,  isSystem: true },
	{ id: 'dbabh',      label: 'Finland',                       treeId: 'region', parentId: 'dba', depth: 2, order: 59,  isSystem: true },
	{ id: 'dbabi',      label: 'France',                        treeId: 'region', parentId: 'dba', depth: 2, order: 60,  isSystem: true },
	{ id: 'dbabj',      label: 'Gabon',                         treeId: 'region', parentId: 'dba', depth: 2, order: 61,  isSystem: true },
	{ id: 'dbabk',      label: 'Gambia',                        treeId: 'region', parentId: 'dba', depth: 2, order: 62,  isSystem: true },
	{ id: 'dbabl',      label: 'Georgia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 63,  isSystem: true },
	{ id: 'dbabm',      label: 'Germany',                       treeId: 'region', parentId: 'dba', depth: 2, order: 64,  isSystem: true },
	{ id: 'dbabn',      label: 'Ghana',                         treeId: 'region', parentId: 'dba', depth: 2, order: 65,  isSystem: true },
	{ id: 'dbabo',      label: 'Greece',                        treeId: 'region', parentId: 'dba', depth: 2, order: 66,  isSystem: true },
	{ id: 'dbabp',      label: 'Grenada',                       treeId: 'region', parentId: 'dba', depth: 2, order: 67,  isSystem: true },
	{ id: 'dbabq',      label: 'Guatemala',                     treeId: 'region', parentId: 'dba', depth: 2, order: 68,  isSystem: true },
	{ id: 'dbabr',      label: 'Guinea',                        treeId: 'region', parentId: 'dba', depth: 2, order: 69,  isSystem: true },
	{ id: 'dbabs',      label: 'Guinea-Bissau',                 treeId: 'region', parentId: 'dba', depth: 2, order: 70,  isSystem: true },
	{ id: 'dbabt',      label: 'Guyana',                        treeId: 'region', parentId: 'dba', depth: 2, order: 71,  isSystem: true },
	{ id: 'dbabu',      label: 'Haiti',                         treeId: 'region', parentId: 'dba', depth: 2, order: 72,  isSystem: true },
	{ id: 'dbabv',      label: 'Honduras',                      treeId: 'region', parentId: 'dba', depth: 2, order: 73,  isSystem: true },
	{ id: 'dbabw',      label: 'Hungary',                       treeId: 'region', parentId: 'dba', depth: 2, order: 74,  isSystem: true },
	{ id: 'dbabx',      label: 'Iceland',                       treeId: 'region', parentId: 'dba', depth: 2, order: 75,  isSystem: true },
	{ id: 'dbaby',      label: 'India',                         treeId: 'region', parentId: 'dba', depth: 2, order: 76,  isSystem: true },
	{ id: 'dbabz',      label: 'Indonesia',                     treeId: 'region', parentId: 'dba', depth: 2, order: 77,  isSystem: true },
	{ id: 'dbabA',      label: 'Iran',                          treeId: 'region', parentId: 'dba', depth: 2, order: 78,  isSystem: true },
	{ id: 'dbabB',      label: 'Iraq',                          treeId: 'region', parentId: 'dba', depth: 2, order: 79,  isSystem: true },
	{ id: 'dbabC',      label: 'Ireland',                       treeId: 'region', parentId: 'dba', depth: 2, order: 80,  isSystem: true },
	{ id: 'dbabD',      label: 'Israel',                        treeId: 'region', parentId: 'dba', depth: 2, order: 81,  isSystem: true },
	{ id: 'dbabE',      label: 'Italy',                         treeId: 'region', parentId: 'dba', depth: 2, order: 82,  isSystem: true },
	{ id: 'dbabF',      label: 'Jamaica',                       treeId: 'region', parentId: 'dba', depth: 2, order: 83,  isSystem: true },
	{ id: 'dbabG',      label: 'Japan',                         treeId: 'region', parentId: 'dba', depth: 2, order: 84,  isSystem: true },
	{ id: 'dbabH',      label: 'Jordan',                        treeId: 'region', parentId: 'dba', depth: 2, order: 85,  isSystem: true },
	{ id: 'dbabI',      label: 'Kazakhstan',                    treeId: 'region', parentId: 'dba', depth: 2, order: 86,  isSystem: true },
	{ id: 'dbabJ',      label: 'Kenya',                         treeId: 'region', parentId: 'dba', depth: 2, order: 87,  isSystem: true },
	{ id: 'dbabK',      label: 'Kiribati',                      treeId: 'region', parentId: 'dba', depth: 2, order: 88,  isSystem: true },
	{ id: 'dbabL',      label: 'North Korea',                   treeId: 'region', parentId: 'dba', depth: 2, order: 89,  isSystem: true },
	{ id: 'dbabM',      label: 'South Korea',                   treeId: 'region', parentId: 'dba', depth: 2, order: 90,  isSystem: true },
	{ id: 'dbabN',      label: 'Kosovo',                        treeId: 'region', parentId: 'dba', depth: 2, order: 91,  isSystem: true },
	{ id: 'dbabO',      label: 'Kuwait',                        treeId: 'region', parentId: 'dba', depth: 2, order: 92,  isSystem: true },
	{ id: 'dbabP',      label: 'Kyrgyzstan',                    treeId: 'region', parentId: 'dba', depth: 2, order: 93,  isSystem: true },
	{ id: 'dbabQ',      label: 'Laos',                          treeId: 'region', parentId: 'dba', depth: 2, order: 94,  isSystem: true },
	{ id: 'dbabR',      label: 'Latvia',                        treeId: 'region', parentId: 'dba', depth: 2, order: 95,  isSystem: true },
	{ id: 'dbabS',      label: 'Lebanon',                       treeId: 'region', parentId: 'dba', depth: 2, order: 96,  isSystem: true },
	{ id: 'dbabT',      label: 'Lesotho',                       treeId: 'region', parentId: 'dba', depth: 2, order: 97,  isSystem: true },
	{ id: 'dbabU',      label: 'Liberia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 98,  isSystem: true },
	{ id: 'dbabV',      label: 'Libya',                         treeId: 'region', parentId: 'dba', depth: 2, order: 99,  isSystem: true },
	{ id: 'dbabW',      label: 'Liechtenstein',                 treeId: 'region', parentId: 'dba', depth: 2, order: 100, isSystem: true },
	{ id: 'dbabX',      label: 'Lithuania',                     treeId: 'region', parentId: 'dba', depth: 2, order: 101, isSystem: true },
	{ id: 'dbabY',      label: 'Luxembourg',                    treeId: 'region', parentId: 'dba', depth: 2, order: 102, isSystem: true },
	{ id: 'dbabZ',      label: 'Madagascar',                    treeId: 'region', parentId: 'dba', depth: 2, order: 103, isSystem: true },
	{ id: 'dbaca',      label: 'Malawi',                        treeId: 'region', parentId: 'dba', depth: 2, order: 104, isSystem: true },
	{ id: 'dbacb',      label: 'Malaysia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 105, isSystem: true },
	{ id: 'dbacc',      label: 'Maldives',                      treeId: 'region', parentId: 'dba', depth: 2, order: 106, isSystem: true },
	{ id: 'dbacd',      label: 'Mali',                          treeId: 'region', parentId: 'dba', depth: 2, order: 107, isSystem: true },
	{ id: 'dbace',      label: 'Malta',                         treeId: 'region', parentId: 'dba', depth: 2, order: 108, isSystem: true },
	{ id: 'dbacf',      label: 'Marshall Islands',              treeId: 'region', parentId: 'dba', depth: 2, order: 109, isSystem: true },
	{ id: 'dbacg',      label: 'Mauritania',                    treeId: 'region', parentId: 'dba', depth: 2, order: 110, isSystem: true },
	{ id: 'dbach',      label: 'Mauritius',                     treeId: 'region', parentId: 'dba', depth: 2, order: 111, isSystem: true },
	{ id: 'dbaci',      label: 'Mexico',                        treeId: 'region', parentId: 'dba', depth: 2, order: 112, isSystem: true },
	{ id: 'dbacj',      label: 'Micronesia',                    treeId: 'region', parentId: 'dba', depth: 2, order: 113, isSystem: true },
	{ id: 'dback',      label: 'Moldova',                       treeId: 'region', parentId: 'dba', depth: 2, order: 114, isSystem: true },
	{ id: 'dbacl',      label: 'Monaco',                        treeId: 'region', parentId: 'dba', depth: 2, order: 115, isSystem: true },
	{ id: 'dbacm',      label: 'Mongolia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 116, isSystem: true },
	{ id: 'dbacn',      label: 'Montenegro',                    treeId: 'region', parentId: 'dba', depth: 2, order: 117, isSystem: true },
	{ id: 'dbaco',      label: 'Morocco',                       treeId: 'region', parentId: 'dba', depth: 2, order: 118, isSystem: true },
	{ id: 'dbacp',      label: 'Mozambique',                    treeId: 'region', parentId: 'dba', depth: 2, order: 119, isSystem: true },
	{ id: 'dbacq',      label: 'Myanmar',                       treeId: 'region', parentId: 'dba', depth: 2, order: 120, isSystem: true },
	{ id: 'dbacr',      label: 'Namibia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 121, isSystem: true },
	{ id: 'dbacs',      label: 'Nauru',                         treeId: 'region', parentId: 'dba', depth: 2, order: 122, isSystem: true },
	{ id: 'dbact',      label: 'Nepal',                         treeId: 'region', parentId: 'dba', depth: 2, order: 123, isSystem: true },
	{ id: 'dbacu',      label: 'Netherlands',                   treeId: 'region', parentId: 'dba', depth: 2, order: 124, isSystem: true },
	{ id: 'dbacv',      label: 'New Zealand',                   treeId: 'region', parentId: 'dba', depth: 2, order: 125, isSystem: true },
	{ id: 'dbacw',      label: 'Nicaragua',                     treeId: 'region', parentId: 'dba', depth: 2, order: 126, isSystem: true },
	{ id: 'dbacx',      label: 'Niger',                         treeId: 'region', parentId: 'dba', depth: 2, order: 127, isSystem: true },
	{ id: 'dbacy',      label: 'Nigeria',                       treeId: 'region', parentId: 'dba', depth: 2, order: 128, isSystem: true },
	{ id: 'dbacz',      label: 'North Macedonia',               treeId: 'region', parentId: 'dba', depth: 2, order: 129, isSystem: true },
	{ id: 'dbacA',      label: 'Norway',                        treeId: 'region', parentId: 'dba', depth: 2, order: 130, isSystem: true },
	{ id: 'dbacB',      label: 'Oman',                          treeId: 'region', parentId: 'dba', depth: 2, order: 131, isSystem: true },
	{ id: 'dbacC',      label: 'Pakistan',                      treeId: 'region', parentId: 'dba', depth: 2, order: 132, isSystem: true },
	{ id: 'dbacD',      label: 'Palau',                         treeId: 'region', parentId: 'dba', depth: 2, order: 133, isSystem: true },
	{ id: 'dbacE',      label: 'Palestine',                     treeId: 'region', parentId: 'dba', depth: 2, order: 134, isSystem: true },
	{ id: 'dbacF',      label: 'Panama',                        treeId: 'region', parentId: 'dba', depth: 2, order: 135, isSystem: true },
	{ id: 'dbacG',      label: 'Papua New Guinea',              treeId: 'region', parentId: 'dba', depth: 2, order: 136, isSystem: true },
	{ id: 'dbacH',      label: 'Paraguay',                      treeId: 'region', parentId: 'dba', depth: 2, order: 137, isSystem: true },
	{ id: 'dbacI',      label: 'Peru',                          treeId: 'region', parentId: 'dba', depth: 2, order: 138, isSystem: true },
	{ id: 'dbacJ',      label: 'Philippines',                   treeId: 'region', parentId: 'dba', depth: 2, order: 139, isSystem: true },
	{ id: 'dbacK',      label: 'Poland',                        treeId: 'region', parentId: 'dba', depth: 2, order: 140, isSystem: true },
	{ id: 'dbacL',      label: 'Portugal',                      treeId: 'region', parentId: 'dba', depth: 2, order: 141, isSystem: true },
	{ id: 'dbacM',      label: 'Qatar',                         treeId: 'region', parentId: 'dba', depth: 2, order: 142, isSystem: true },
	{ id: 'dbacN',      label: 'Romania',                       treeId: 'region', parentId: 'dba', depth: 2, order: 143, isSystem: true },
	{ id: 'dbacO',      label: 'Russia',                        treeId: 'region', parentId: 'dba', depth: 2, order: 144, isSystem: true },
	{ id: 'dbacP',      label: 'Rwanda',                        treeId: 'region', parentId: 'dba', depth: 2, order: 145, isSystem: true },
	{ id: 'dbacQ',      label: 'Saint Kitts and Nevis',         treeId: 'region', parentId: 'dba', depth: 2, order: 146, isSystem: true },
	{ id: 'dbacR',      label: 'Saint Lucia',                   treeId: 'region', parentId: 'dba', depth: 2, order: 147, isSystem: true },
	{ id: 'dbacS',      label: 'Saint Vincent and the Grenadines', treeId: 'region', parentId: 'dba', depth: 2, order: 148, isSystem: true },
	{ id: 'dbacT',      label: 'Samoa',                         treeId: 'region', parentId: 'dba', depth: 2, order: 149, isSystem: true },
	{ id: 'dbacU',      label: 'San Marino',                    treeId: 'region', parentId: 'dba', depth: 2, order: 150, isSystem: true },
	{ id: 'dbacV',      label: 'São Tomé and Príncipe',         treeId: 'region', parentId: 'dba', depth: 2, order: 151, isSystem: true },
	{ id: 'dbacW',      label: 'Saudi Arabia',                  treeId: 'region', parentId: 'dba', depth: 2, order: 152, isSystem: true },
	{ id: 'dbacX',      label: 'Senegal',                       treeId: 'region', parentId: 'dba', depth: 2, order: 153, isSystem: true },
	{ id: 'dbacY',      label: 'Serbia',                        treeId: 'region', parentId: 'dba', depth: 2, order: 154, isSystem: true },
	{ id: 'dbacZ',      label: 'Seychelles',                    treeId: 'region', parentId: 'dba', depth: 2, order: 155, isSystem: true },
	{ id: 'dbada',      label: 'Sierra Leone',                  treeId: 'region', parentId: 'dba', depth: 2, order: 156, isSystem: true },
	{ id: 'dbadb',      label: 'Singapore',                     treeId: 'region', parentId: 'dba', depth: 2, order: 157, isSystem: true },
	{ id: 'dbadc',      label: 'Slovakia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 158, isSystem: true },
	{ id: 'dbadd',      label: 'Slovenia',                      treeId: 'region', parentId: 'dba', depth: 2, order: 159, isSystem: true },
	{ id: 'dbade',      label: 'Solomon Islands',               treeId: 'region', parentId: 'dba', depth: 2, order: 160, isSystem: true },
	{ id: 'dbadf',      label: 'Somalia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 161, isSystem: true },
	{ id: 'dbadg',      label: 'South Africa',                  treeId: 'region', parentId: 'dba', depth: 2, order: 162, isSystem: true },
	{ id: 'dbadh',      label: 'South Sudan',                   treeId: 'region', parentId: 'dba', depth: 2, order: 163, isSystem: true },
	{ id: 'dbadi',      label: 'Spain',                         treeId: 'region', parentId: 'dba', depth: 2, order: 164, isSystem: true },
	{ id: 'dbadj',      label: 'Sri Lanka',                     treeId: 'region', parentId: 'dba', depth: 2, order: 165, isSystem: true },
	{ id: 'dbadk',      label: 'Sudan',                         treeId: 'region', parentId: 'dba', depth: 2, order: 166, isSystem: true },
	{ id: 'dbadl',      label: 'Suriname',                      treeId: 'region', parentId: 'dba', depth: 2, order: 167, isSystem: true },
	{ id: 'dbadm',      label: 'Sweden',                        treeId: 'region', parentId: 'dba', depth: 2, order: 168, isSystem: true },
	{ id: 'dbadn',      label: 'Switzerland',                   treeId: 'region', parentId: 'dba', depth: 2, order: 169, isSystem: true },
	{ id: 'dbado',      label: 'Syria',                         treeId: 'region', parentId: 'dba', depth: 2, order: 170, isSystem: true },
	{ id: 'dbadp',      label: 'Taiwan',                        treeId: 'region', parentId: 'dba', depth: 2, order: 171, isSystem: true },
	{ id: 'dbadq',      label: 'Tajikistan',                    treeId: 'region', parentId: 'dba', depth: 2, order: 172, isSystem: true },
	{ id: 'dbadr',      label: 'Tanzania',                      treeId: 'region', parentId: 'dba', depth: 2, order: 173, isSystem: true },
	{ id: 'dbads',      label: 'Thailand',                      treeId: 'region', parentId: 'dba', depth: 2, order: 174, isSystem: true },
	{ id: 'dbadt',      label: 'Timor-Leste',                   treeId: 'region', parentId: 'dba', depth: 2, order: 175, isSystem: true },
	{ id: 'dbadu',      label: 'Togo',                          treeId: 'region', parentId: 'dba', depth: 2, order: 176, isSystem: true },
	{ id: 'dbadv',      label: 'Tonga',                         treeId: 'region', parentId: 'dba', depth: 2, order: 177, isSystem: true },
	{ id: 'dbadw',      label: 'Trinidad and Tobago',           treeId: 'region', parentId: 'dba', depth: 2, order: 178, isSystem: true },
	{ id: 'dbadx',      label: 'Tunisia',                       treeId: 'region', parentId: 'dba', depth: 2, order: 179, isSystem: true },
	{ id: 'dbady',      label: 'Turkey',                        treeId: 'region', parentId: 'dba', depth: 2, order: 180, isSystem: true },
	{ id: 'dbadz',      label: 'Turkmenistan',                  treeId: 'region', parentId: 'dba', depth: 2, order: 181, isSystem: true },
	{ id: 'dbadA',      label: 'Tuvalu',                        treeId: 'region', parentId: 'dba', depth: 2, order: 182, isSystem: true },
	{ id: 'dbadB',      label: 'Uganda',                        treeId: 'region', parentId: 'dba', depth: 2, order: 183, isSystem: true },
	{ id: 'dbadC',      label: 'Ukraine',                       treeId: 'region', parentId: 'dba', depth: 2, order: 184, isSystem: true },
	{ id: 'dbadD',      label: 'United Arab Emirates',          treeId: 'region', parentId: 'dba', depth: 2, order: 185, isSystem: true },
	{ id: 'dbadE',      label: 'United Kingdom',                treeId: 'region', parentId: 'dba', depth: 2, order: 186, isSystem: true },
	{ id: 'dbadF',      label: 'United States',                 treeId: 'region', parentId: 'dba', depth: 2, order: 187, isSystem: true },
	{ id: 'dbadG',      label: 'Uruguay',                       treeId: 'region', parentId: 'dba', depth: 2, order: 188, isSystem: true },
	{ id: 'dbadH',      label: 'Uzbekistan',                    treeId: 'region', parentId: 'dba', depth: 2, order: 189, isSystem: true },
	{ id: 'dbadI',      label: 'Vanuatu',                       treeId: 'region', parentId: 'dba', depth: 2, order: 190, isSystem: true },
	{ id: 'dbadJ',      label: 'Vatican City',                  treeId: 'region', parentId: 'dba', depth: 2, order: 191, isSystem: true },
	{ id: 'dbadK',      label: 'Venezuela',                     treeId: 'region', parentId: 'dba', depth: 2, order: 192, isSystem: true },
	{ id: 'dbadL',      label: 'Vietnam',                       treeId: 'region', parentId: 'dba', depth: 2, order: 193, isSystem: true },
	{ id: 'dbadM',      label: 'Yemen',                         treeId: 'region', parentId: 'dba', depth: 2, order: 194, isSystem: true },
	{ id: 'dbadN',      label: 'Zambia',                        treeId: 'region', parentId: 'dba', depth: 2, order: 195, isSystem: true },
	{ id: 'dbadO',      label: 'Zimbabwe',                      treeId: 'region', parentId: 'dba', depth: 2, order: 196, isSystem: true },

	// Territories & Dependencies (ISO 3166-1 — inhabited, non-sovereign)
	{ id: 'dbb',  label: 'Territories & Dependencies', treeId: 'region', parentId: 'db',          depth: 1, order: 1, isSystem: true },
	{ id: 'dbbaa',      label: 'Anguilla',                      treeId: 'region', parentId: 'dbb', depth: 2, order: 0,  isSystem: true },
	{ id: 'dbbab',      label: 'American Samoa',                treeId: 'region', parentId: 'dbb', depth: 2, order: 1,  isSystem: true },
	{ id: 'dbbac',      label: 'Aruba',                         treeId: 'region', parentId: 'dbb', depth: 2, order: 2,  isSystem: true },
	{ id: 'dbbad',      label: 'Åland Islands',                 treeId: 'region', parentId: 'dbb', depth: 2, order: 3,  isSystem: true },
	{ id: 'dbbae',      label: 'Saint Barthélemy',              treeId: 'region', parentId: 'dbb', depth: 2, order: 4,  isSystem: true },
	{ id: 'dbbaf',      label: 'Bermuda',                       treeId: 'region', parentId: 'dbb', depth: 2, order: 5,  isSystem: true },
	{ id: 'dbbag',      label: 'Bonaire, Sint Eustatius & Saba', treeId: 'region', parentId: 'dbb', depth: 2, order: 6,  isSystem: true },
	{ id: 'dbbah',      label: 'Cocos (Keeling) Islands',       treeId: 'region', parentId: 'dbb', depth: 2, order: 7,  isSystem: true },
	{ id: 'dbbai',      label: 'Cook Islands',                  treeId: 'region', parentId: 'dbb', depth: 2, order: 8,  isSystem: true },
	{ id: 'dbbaj',      label: 'Curaçao',                       treeId: 'region', parentId: 'dbb', depth: 2, order: 9,  isSystem: true },
	{ id: 'dbbak',      label: 'Christmas Island',              treeId: 'region', parentId: 'dbb', depth: 2, order: 10, isSystem: true },
	{ id: 'dbbal',      label: 'Western Sahara',                treeId: 'region', parentId: 'dbb', depth: 2, order: 11, isSystem: true },
	{ id: 'dbbam',      label: 'Falkland Islands',              treeId: 'region', parentId: 'dbb', depth: 2, order: 12, isSystem: true },
	{ id: 'dbban',      label: 'Faroe Islands',                 treeId: 'region', parentId: 'dbb', depth: 2, order: 13, isSystem: true },
	{ id: 'dbbao',      label: 'French Guiana',                 treeId: 'region', parentId: 'dbb', depth: 2, order: 14, isSystem: true },
	{ id: 'dbbap',      label: 'Guernsey',                      treeId: 'region', parentId: 'dbb', depth: 2, order: 15, isSystem: true },
	{ id: 'dbbaq',      label: 'Gibraltar',                     treeId: 'region', parentId: 'dbb', depth: 2, order: 16, isSystem: true },
	{ id: 'dbbar',      label: 'Greenland',                     treeId: 'region', parentId: 'dbb', depth: 2, order: 17, isSystem: true },
	{ id: 'dbbas',      label: 'Guadeloupe',                    treeId: 'region', parentId: 'dbb', depth: 2, order: 18, isSystem: true },
	{ id: 'dbbat',      label: 'Guam',                          treeId: 'region', parentId: 'dbb', depth: 2, order: 19, isSystem: true },
	{ id: 'dbbau',      label: 'Hong Kong',                     treeId: 'region', parentId: 'dbb', depth: 2, order: 20, isSystem: true },
	{ id: 'dbbav',      label: 'Isle of Man',                   treeId: 'region', parentId: 'dbb', depth: 2, order: 21, isSystem: true },
	{ id: 'dbbaw',      label: 'Jersey',                        treeId: 'region', parentId: 'dbb', depth: 2, order: 22, isSystem: true },
	{ id: 'dbbax',      label: 'Cayman Islands',                treeId: 'region', parentId: 'dbb', depth: 2, order: 23, isSystem: true },
	{ id: 'dbbay',      label: 'Saint Martin',                  treeId: 'region', parentId: 'dbb', depth: 2, order: 24, isSystem: true },
	{ id: 'dbbaz',      label: 'Macao',                         treeId: 'region', parentId: 'dbb', depth: 2, order: 25, isSystem: true },
	{ id: 'dbbaA',      label: 'Northern Mariana Islands',      treeId: 'region', parentId: 'dbb', depth: 2, order: 26, isSystem: true },
	{ id: 'dbbaB',      label: 'Martinique',                    treeId: 'region', parentId: 'dbb', depth: 2, order: 27, isSystem: true },
	{ id: 'dbbaC',      label: 'Montserrat',                    treeId: 'region', parentId: 'dbb', depth: 2, order: 28, isSystem: true },
	{ id: 'dbbaD',      label: 'New Caledonia',                 treeId: 'region', parentId: 'dbb', depth: 2, order: 29, isSystem: true },
	{ id: 'dbbaE',      label: 'Norfolk Island',                treeId: 'region', parentId: 'dbb', depth: 2, order: 30, isSystem: true },
	{ id: 'dbbaF',      label: 'Niue',                          treeId: 'region', parentId: 'dbb', depth: 2, order: 31, isSystem: true },
	{ id: 'dbbaG',      label: 'French Polynesia',              treeId: 'region', parentId: 'dbb', depth: 2, order: 32, isSystem: true },
	{ id: 'dbbaH',      label: 'Saint Pierre and Miquelon',     treeId: 'region', parentId: 'dbb', depth: 2, order: 33, isSystem: true },
	{ id: 'dbbaI',      label: 'Pitcairn Islands',              treeId: 'region', parentId: 'dbb', depth: 2, order: 34, isSystem: true },
	{ id: 'dbbaJ',      label: 'Puerto Rico',                   treeId: 'region', parentId: 'dbb', depth: 2, order: 35, isSystem: true },
	{ id: 'dbbaK',      label: 'Réunion',                       treeId: 'region', parentId: 'dbb', depth: 2, order: 36, isSystem: true },
	{ id: 'dbbaL',      label: 'Saint Helena',                  treeId: 'region', parentId: 'dbb', depth: 2, order: 37, isSystem: true },
	{ id: 'dbbaM',      label: 'Svalbard and Jan Mayen',        treeId: 'region', parentId: 'dbb', depth: 2, order: 38, isSystem: true },
	{ id: 'dbbaN',      label: 'Sint Maarten',                  treeId: 'region', parentId: 'dbb', depth: 2, order: 39, isSystem: true },
	{ id: 'dbbaO',      label: 'Turks and Caicos Islands',      treeId: 'region', parentId: 'dbb', depth: 2, order: 40, isSystem: true },
	{ id: 'dbbaP',      label: 'Tokelau',                       treeId: 'region', parentId: 'dbb', depth: 2, order: 41, isSystem: true },
	{ id: 'dbbaQ',      label: 'British Virgin Islands',        treeId: 'region', parentId: 'dbb', depth: 2, order: 42, isSystem: true },
	{ id: 'dbbaR',      label: 'U.S. Virgin Islands',           treeId: 'region', parentId: 'dbb', depth: 2, order: 43, isSystem: true },
	{ id: 'dbbaS',      label: 'Wallis and Futuna',             treeId: 'region', parentId: 'dbb', depth: 2, order: 44, isSystem: true },
	{ id: 'dbbaT',      label: 'Mayotte',                       treeId: 'region', parentId: 'dbb', depth: 2, order: 45, isSystem: true },
];
