/**
 * Region Seed — geographic taxonomy (World / UN M49 macro-regions / ISO 3166-1 standard).
 *
 * The macro-region hierarchy follows the UN M49 standard:
 * https://unstats.un.org/unsd/methodology/m49/
 *
 * The country hierarchy follows the ISO 3166-1 standard:
 * https://www.iso.org/iso-3166-country-codes.html
 */

import type { SeedCategory } from './category-seed.js';

export const regionSeed: SeedCategory[] = [

	// ── Macro-region (UN M49) ──────────────────────────────────────────────
	{ id: 'reg-macro',                label: 'Macro-region',               treeId: 'region', parentId: null,           depth: 0, order: 1, isSystem: true },

	// Africa (002)
	{ id: 'reg-macro-africa',              label: 'Africa',                    treeId: 'region', parentId: 'reg-macro',          depth: 1, order: 0, isSystem: true },
	{ id: 'reg-macro-africa-northern',     label: 'Northern Africa',           treeId: 'region', parentId: 'reg-macro-africa',   depth: 2, order: 0, isSystem: true },
	{ id: 'reg-macro-africa-eastern',      label: 'Eastern Africa',            treeId: 'region', parentId: 'reg-macro-africa',   depth: 2, order: 1, isSystem: true },
	{ id: 'reg-macro-africa-middle',       label: 'Middle Africa',             treeId: 'region', parentId: 'reg-macro-africa',   depth: 2, order: 2, isSystem: true },
	{ id: 'reg-macro-africa-southern',     label: 'Southern Africa',           treeId: 'region', parentId: 'reg-macro-africa',   depth: 2, order: 3, isSystem: true },
	{ id: 'reg-macro-africa-western',      label: 'Western Africa',            treeId: 'region', parentId: 'reg-macro-africa',   depth: 2, order: 4, isSystem: true },

	// Americas (019)
	{ id: 'reg-macro-americas',            label: 'Americas',                  treeId: 'region', parentId: 'reg-macro',            depth: 1, order: 1, isSystem: true },
	{ id: 'reg-macro-americas-northern',   label: 'Northern America',          treeId: 'region', parentId: 'reg-macro-americas',   depth: 2, order: 0, isSystem: true },
	{ id: 'reg-macro-americas-caribbean',  label: 'Caribbean',                 treeId: 'region', parentId: 'reg-macro-americas',   depth: 2, order: 1, isSystem: true },
	{ id: 'reg-macro-americas-central',    label: 'Central America',           treeId: 'region', parentId: 'reg-macro-americas',   depth: 2, order: 2, isSystem: true },
	{ id: 'reg-macro-americas-south',      label: 'South America',             treeId: 'region', parentId: 'reg-macro-americas',   depth: 2, order: 3, isSystem: true },

	// Asia (142)
	{ id: 'reg-macro-asia',                label: 'Asia',                      treeId: 'region', parentId: 'reg-macro',         depth: 1, order: 2, isSystem: true },
	{ id: 'reg-macro-asia-central',        label: 'Central Asia',              treeId: 'region', parentId: 'reg-macro-asia',    depth: 2, order: 0, isSystem: true },
	{ id: 'reg-macro-asia-eastern',        label: 'Eastern Asia',              treeId: 'region', parentId: 'reg-macro-asia',    depth: 2, order: 1, isSystem: true },
	{ id: 'reg-macro-asia-southeastern',   label: 'South-eastern Asia',        treeId: 'region', parentId: 'reg-macro-asia',    depth: 2, order: 2, isSystem: true },
	{ id: 'reg-macro-asia-southern',       label: 'Southern Asia',             treeId: 'region', parentId: 'reg-macro-asia',    depth: 2, order: 3, isSystem: true },
	{ id: 'reg-macro-asia-western',        label: 'Western Asia',              treeId: 'region', parentId: 'reg-macro-asia',    depth: 2, order: 4, isSystem: true },

	// Europe (150)
	{ id: 'reg-macro-europe',              label: 'Europe',                    treeId: 'region', parentId: 'reg-macro',           depth: 1, order: 3, isSystem: true },
	{ id: 'reg-macro-europe-eastern',      label: 'Eastern Europe',            treeId: 'region', parentId: 'reg-macro-europe',    depth: 2, order: 0, isSystem: true },
	{ id: 'reg-macro-europe-northern',     label: 'Northern Europe',           treeId: 'region', parentId: 'reg-macro-europe',    depth: 2, order: 1, isSystem: true },
	{ id: 'reg-macro-europe-southern',     label: 'Southern Europe',           treeId: 'region', parentId: 'reg-macro-europe',    depth: 2, order: 2, isSystem: true },
	{ id: 'reg-macro-europe-western',      label: 'Western Europe',            treeId: 'region', parentId: 'reg-macro-europe',    depth: 2, order: 3, isSystem: true },

	// Oceania (009)
	{ id: 'reg-macro-oceania',             label: 'Oceania',                   treeId: 'region', parentId: 'reg-macro',            depth: 1, order: 4, isSystem: true },
	{ id: 'reg-macro-oceania-aunz',        label: 'Australia and New Zealand', treeId: 'region', parentId: 'reg-macro-oceania',    depth: 2, order: 0, isSystem: true },
	{ id: 'reg-macro-oceania-melanesia',   label: 'Melanesia',                 treeId: 'region', parentId: 'reg-macro-oceania',    depth: 2, order: 1, isSystem: true },
	{ id: 'reg-macro-oceania-micronesia',  label: 'Micronesia',                treeId: 'region', parentId: 'reg-macro-oceania',    depth: 2, order: 2, isSystem: true },
	{ id: 'reg-macro-oceania-polynesia',   label: 'Polynesia',                 treeId: 'region', parentId: 'reg-macro-oceania',    depth: 2, order: 3, isSystem: true },

	// ── Country (ISO 3166-1) ──────────────────────────────────────────────
	{ id: 'reg-country',             label: 'Country',                   treeId: 'region', parentId: null,                 depth: 0, order: 2, isSystem: true },

	// Sovereign States
	{ id: 'reg-country-sovereign',   label: 'Sovereign States',          treeId: 'region', parentId: 'reg-country',         depth: 1, order: 0, isSystem: true },
	{ id: 'reg-country-af',      label: 'Afghanistan',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 0,   isSystem: true },
	{ id: 'reg-country-al',      label: 'Albania',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 1,   isSystem: true },
	{ id: 'reg-country-dz',      label: 'Algeria',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 2,   isSystem: true },
	{ id: 'reg-country-ad',      label: 'Andorra',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 3,   isSystem: true },
	{ id: 'reg-country-ao',      label: 'Angola',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 4,   isSystem: true },
	{ id: 'reg-country-ag',      label: 'Antigua and Barbuda',           treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 5,   isSystem: true },
	{ id: 'reg-country-ar',      label: 'Argentina',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 6,   isSystem: true },
	{ id: 'reg-country-am',      label: 'Armenia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 7,   isSystem: true },
	{ id: 'reg-country-au',      label: 'Australia',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 8,   isSystem: true },
	{ id: 'reg-country-at',      label: 'Austria',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 9,   isSystem: true },
	{ id: 'reg-country-az',      label: 'Azerbaijan',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 10,  isSystem: true },
	{ id: 'reg-country-bs',      label: 'Bahamas',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 11,  isSystem: true },
	{ id: 'reg-country-bh',      label: 'Bahrain',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 12,  isSystem: true },
	{ id: 'reg-country-bd',      label: 'Bangladesh',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 13,  isSystem: true },
	{ id: 'reg-country-bb',      label: 'Barbados',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 14,  isSystem: true },
	{ id: 'reg-country-by',      label: 'Belarus',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 15,  isSystem: true },
	{ id: 'reg-country-be',      label: 'Belgium',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 16,  isSystem: true },
	{ id: 'reg-country-bz',      label: 'Belize',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 17,  isSystem: true },
	{ id: 'reg-country-bj',      label: 'Benin',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 18,  isSystem: true },
	{ id: 'reg-country-bt',      label: 'Bhutan',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 19,  isSystem: true },
	{ id: 'reg-country-bo',      label: 'Bolivia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 20,  isSystem: true },
	{ id: 'reg-country-ba',      label: 'Bosnia and Herzegovina',        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 21,  isSystem: true },
	{ id: 'reg-country-bw',      label: 'Botswana',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 22,  isSystem: true },
	{ id: 'reg-country-br',      label: 'Brazil',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 23,  isSystem: true },
	{ id: 'reg-country-bn',      label: 'Brunei',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 24,  isSystem: true },
	{ id: 'reg-country-bg',      label: 'Bulgaria',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 25,  isSystem: true },
	{ id: 'reg-country-bf',      label: 'Burkina Faso',                  treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 26,  isSystem: true },
	{ id: 'reg-country-bi',      label: 'Burundi',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 27,  isSystem: true },
	{ id: 'reg-country-cv',      label: 'Cabo Verde',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 28,  isSystem: true },
	{ id: 'reg-country-kh',      label: 'Cambodia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 29,  isSystem: true },
	{ id: 'reg-country-cm',      label: 'Cameroon',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 30,  isSystem: true },
	{ id: 'reg-country-ca',      label: 'Canada',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 31,  isSystem: true },
	{ id: 'reg-country-cf',      label: 'Central African Republic',      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 32,  isSystem: true },
	{ id: 'reg-country-td',      label: 'Chad',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 33,  isSystem: true },
	{ id: 'reg-country-cl',      label: 'Chile',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 34,  isSystem: true },
	{ id: 'reg-country-cn',      label: 'China',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 35,  isSystem: true },
	{ id: 'reg-country-co',      label: 'Colombia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 36,  isSystem: true },
	{ id: 'reg-country-km',      label: 'Comoros',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 37,  isSystem: true },
	{ id: 'reg-country-cd',      label: 'Congo (DRC)',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 38,  isSystem: true },
	{ id: 'reg-country-cg',      label: 'Congo (Republic)',              treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 39,  isSystem: true },
	{ id: 'reg-country-cr',      label: 'Costa Rica',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 40,  isSystem: true },
	{ id: 'reg-country-ci',      label: "Côte d'Ivoire",                 treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 41,  isSystem: true },
	{ id: 'reg-country-hr',      label: 'Croatia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 42,  isSystem: true },
	{ id: 'reg-country-cu',      label: 'Cuba',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 43,  isSystem: true },
	{ id: 'reg-country-cy',      label: 'Cyprus',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 44,  isSystem: true },
	{ id: 'reg-country-cz',      label: 'Czechia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 45,  isSystem: true },
	{ id: 'reg-country-dk',      label: 'Denmark',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 46,  isSystem: true },
	{ id: 'reg-country-dj',      label: 'Djibouti',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 47,  isSystem: true },
	{ id: 'reg-country-dm',      label: 'Dominica',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 48,  isSystem: true },
	{ id: 'reg-country-do',      label: 'Dominican Republic',            treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 49,  isSystem: true },
	{ id: 'reg-country-ec',      label: 'Ecuador',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 50,  isSystem: true },
	{ id: 'reg-country-eg',      label: 'Egypt',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 51,  isSystem: true },
	{ id: 'reg-country-sv',      label: 'El Salvador',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 52,  isSystem: true },
	{ id: 'reg-country-gq',      label: 'Equatorial Guinea',             treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 53,  isSystem: true },
	{ id: 'reg-country-er',      label: 'Eritrea',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 54,  isSystem: true },
	{ id: 'reg-country-ee',      label: 'Estonia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 55,  isSystem: true },
	{ id: 'reg-country-sz',      label: 'Eswatini',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 56,  isSystem: true },
	{ id: 'reg-country-et',      label: 'Ethiopia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 57,  isSystem: true },
	{ id: 'reg-country-fj',      label: 'Fiji',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 58,  isSystem: true },
	{ id: 'reg-country-fi',      label: 'Finland',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 59,  isSystem: true },
	{ id: 'reg-country-fr',      label: 'France',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 60,  isSystem: true },
	{ id: 'reg-country-ga',      label: 'Gabon',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 61,  isSystem: true },
	{ id: 'reg-country-gm',      label: 'Gambia',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 62,  isSystem: true },
	{ id: 'reg-country-ge',      label: 'Georgia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 63,  isSystem: true },
	{ id: 'reg-country-de',      label: 'Germany',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 64,  isSystem: true },
	{ id: 'reg-country-gh',      label: 'Ghana',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 65,  isSystem: true },
	{ id: 'reg-country-gr',      label: 'Greece',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 66,  isSystem: true },
	{ id: 'reg-country-gd',      label: 'Grenada',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 67,  isSystem: true },
	{ id: 'reg-country-gt',      label: 'Guatemala',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 68,  isSystem: true },
	{ id: 'reg-country-gn',      label: 'Guinea',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 69,  isSystem: true },
	{ id: 'reg-country-gw',      label: 'Guinea-Bissau',                 treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 70,  isSystem: true },
	{ id: 'reg-country-gy',      label: 'Guyana',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 71,  isSystem: true },
	{ id: 'reg-country-ht',      label: 'Haiti',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 72,  isSystem: true },
	{ id: 'reg-country-hn',      label: 'Honduras',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 73,  isSystem: true },
	{ id: 'reg-country-hu',      label: 'Hungary',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 74,  isSystem: true },
	{ id: 'reg-country-is',      label: 'Iceland',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 75,  isSystem: true },
	{ id: 'reg-country-in',      label: 'India',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 76,  isSystem: true },
	{ id: 'reg-country-id',      label: 'Indonesia',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 77,  isSystem: true },
	{ id: 'reg-country-ir',      label: 'Iran',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 78,  isSystem: true },
	{ id: 'reg-country-iq',      label: 'Iraq',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 79,  isSystem: true },
	{ id: 'reg-country-ie',      label: 'Ireland',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 80,  isSystem: true },
	{ id: 'reg-country-il',      label: 'Israel',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 81,  isSystem: true },
	{ id: 'reg-country-it',      label: 'Italy',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 82,  isSystem: true },
	{ id: 'reg-country-jm',      label: 'Jamaica',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 83,  isSystem: true },
	{ id: 'reg-country-jp',      label: 'Japan',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 84,  isSystem: true },
	{ id: 'reg-country-jo',      label: 'Jordan',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 85,  isSystem: true },
	{ id: 'reg-country-kz',      label: 'Kazakhstan',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 86,  isSystem: true },
	{ id: 'reg-country-ke',      label: 'Kenya',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 87,  isSystem: true },
	{ id: 'reg-country-ki',      label: 'Kiribati',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 88,  isSystem: true },
	{ id: 'reg-country-kp',      label: 'North Korea',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 89,  isSystem: true },
	{ id: 'reg-country-kr',      label: 'South Korea',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 90,  isSystem: true },
	{ id: 'reg-country-xk',      label: 'Kosovo',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 91,  isSystem: true },
	{ id: 'reg-country-kw',      label: 'Kuwait',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 92,  isSystem: true },
	{ id: 'reg-country-kg',      label: 'Kyrgyzstan',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 93,  isSystem: true },
	{ id: 'reg-country-la',      label: 'Laos',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 94,  isSystem: true },
	{ id: 'reg-country-lv',      label: 'Latvia',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 95,  isSystem: true },
	{ id: 'reg-country-lb',      label: 'Lebanon',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 96,  isSystem: true },
	{ id: 'reg-country-ls',      label: 'Lesotho',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 97,  isSystem: true },
	{ id: 'reg-country-lr',      label: 'Liberia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 98,  isSystem: true },
	{ id: 'reg-country-ly',      label: 'Libya',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 99,  isSystem: true },
	{ id: 'reg-country-li',      label: 'Liechtenstein',                 treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 100, isSystem: true },
	{ id: 'reg-country-lt',      label: 'Lithuania',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 101, isSystem: true },
	{ id: 'reg-country-lu',      label: 'Luxembourg',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 102, isSystem: true },
	{ id: 'reg-country-mg',      label: 'Madagascar',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 103, isSystem: true },
	{ id: 'reg-country-mw',      label: 'Malawi',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 104, isSystem: true },
	{ id: 'reg-country-my',      label: 'Malaysia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 105, isSystem: true },
	{ id: 'reg-country-mv',      label: 'Maldives',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 106, isSystem: true },
	{ id: 'reg-country-ml',      label: 'Mali',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 107, isSystem: true },
	{ id: 'reg-country-mt',      label: 'Malta',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 108, isSystem: true },
	{ id: 'reg-country-mh',      label: 'Marshall Islands',              treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 109, isSystem: true },
	{ id: 'reg-country-mr',      label: 'Mauritania',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 110, isSystem: true },
	{ id: 'reg-country-mu',      label: 'Mauritius',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 111, isSystem: true },
	{ id: 'reg-country-mx',      label: 'Mexico',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 112, isSystem: true },
	{ id: 'reg-country-fm',      label: 'Micronesia',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 113, isSystem: true },
	{ id: 'reg-country-md',      label: 'Moldova',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 114, isSystem: true },
	{ id: 'reg-country-mc',      label: 'Monaco',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 115, isSystem: true },
	{ id: 'reg-country-mn',      label: 'Mongolia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 116, isSystem: true },
	{ id: 'reg-country-me',      label: 'Montenegro',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 117, isSystem: true },
	{ id: 'reg-country-ma',      label: 'Morocco',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 118, isSystem: true },
	{ id: 'reg-country-mz',      label: 'Mozambique',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 119, isSystem: true },
	{ id: 'reg-country-mm',      label: 'Myanmar',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 120, isSystem: true },
	{ id: 'reg-country-na',      label: 'Namibia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 121, isSystem: true },
	{ id: 'reg-country-nr',      label: 'Nauru',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 122, isSystem: true },
	{ id: 'reg-country-np',      label: 'Nepal',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 123, isSystem: true },
	{ id: 'reg-country-nl',      label: 'Netherlands',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 124, isSystem: true },
	{ id: 'reg-country-nz',      label: 'New Zealand',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 125, isSystem: true },
	{ id: 'reg-country-ni',      label: 'Nicaragua',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 126, isSystem: true },
	{ id: 'reg-country-ne',      label: 'Niger',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 127, isSystem: true },
	{ id: 'reg-country-ng',      label: 'Nigeria',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 128, isSystem: true },
	{ id: 'reg-country-mk',      label: 'North Macedonia',               treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 129, isSystem: true },
	{ id: 'reg-country-no',      label: 'Norway',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 130, isSystem: true },
	{ id: 'reg-country-om',      label: 'Oman',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 131, isSystem: true },
	{ id: 'reg-country-pk',      label: 'Pakistan',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 132, isSystem: true },
	{ id: 'reg-country-pw',      label: 'Palau',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 133, isSystem: true },
	{ id: 'reg-country-ps',      label: 'Palestine',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 134, isSystem: true },
	{ id: 'reg-country-pa',      label: 'Panama',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 135, isSystem: true },
	{ id: 'reg-country-pg',      label: 'Papua New Guinea',              treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 136, isSystem: true },
	{ id: 'reg-country-py',      label: 'Paraguay',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 137, isSystem: true },
	{ id: 'reg-country-pe',      label: 'Peru',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 138, isSystem: true },
	{ id: 'reg-country-ph',      label: 'Philippines',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 139, isSystem: true },
	{ id: 'reg-country-pl',      label: 'Poland',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 140, isSystem: true },
	{ id: 'reg-country-pt',      label: 'Portugal',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 141, isSystem: true },
	{ id: 'reg-country-qa',      label: 'Qatar',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 142, isSystem: true },
	{ id: 'reg-country-ro',      label: 'Romania',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 143, isSystem: true },
	{ id: 'reg-country-ru',      label: 'Russia',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 144, isSystem: true },
	{ id: 'reg-country-rw',      label: 'Rwanda',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 145, isSystem: true },
	{ id: 'reg-country-kn',      label: 'Saint Kitts and Nevis',         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 146, isSystem: true },
	{ id: 'reg-country-lc',      label: 'Saint Lucia',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 147, isSystem: true },
	{ id: 'reg-country-vc',      label: 'Saint Vincent and the Grenadines', treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 148, isSystem: true },
	{ id: 'reg-country-ws',      label: 'Samoa',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 149, isSystem: true },
	{ id: 'reg-country-sm',      label: 'San Marino',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 150, isSystem: true },
	{ id: 'reg-country-st',      label: 'São Tomé and Príncipe',         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 151, isSystem: true },
	{ id: 'reg-country-sa',      label: 'Saudi Arabia',                  treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 152, isSystem: true },
	{ id: 'reg-country-sn',      label: 'Senegal',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 153, isSystem: true },
	{ id: 'reg-country-rs',      label: 'Serbia',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 154, isSystem: true },
	{ id: 'reg-country-sc',      label: 'Seychelles',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 155, isSystem: true },
	{ id: 'reg-country-sl',      label: 'Sierra Leone',                  treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 156, isSystem: true },
	{ id: 'reg-country-sg',      label: 'Singapore',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 157, isSystem: true },
	{ id: 'reg-country-sk',      label: 'Slovakia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 158, isSystem: true },
	{ id: 'reg-country-si',      label: 'Slovenia',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 159, isSystem: true },
	{ id: 'reg-country-sb',      label: 'Solomon Islands',               treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 160, isSystem: true },
	{ id: 'reg-country-so',      label: 'Somalia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 161, isSystem: true },
	{ id: 'reg-country-za',      label: 'South Africa',                  treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 162, isSystem: true },
	{ id: 'reg-country-ss',      label: 'South Sudan',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 163, isSystem: true },
	{ id: 'reg-country-es',      label: 'Spain',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 164, isSystem: true },
	{ id: 'reg-country-lk',      label: 'Sri Lanka',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 165, isSystem: true },
	{ id: 'reg-country-sd',      label: 'Sudan',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 166, isSystem: true },
	{ id: 'reg-country-sr',      label: 'Suriname',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 167, isSystem: true },
	{ id: 'reg-country-se',      label: 'Sweden',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 168, isSystem: true },
	{ id: 'reg-country-ch',      label: 'Switzerland',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 169, isSystem: true },
	{ id: 'reg-country-sy',      label: 'Syria',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 170, isSystem: true },
	{ id: 'reg-country-tw',      label: 'Taiwan',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 171, isSystem: true },
	{ id: 'reg-country-tj',      label: 'Tajikistan',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 172, isSystem: true },
	{ id: 'reg-country-tz',      label: 'Tanzania',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 173, isSystem: true },
	{ id: 'reg-country-th',      label: 'Thailand',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 174, isSystem: true },
	{ id: 'reg-country-tl',      label: 'Timor-Leste',                   treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 175, isSystem: true },
	{ id: 'reg-country-tg',      label: 'Togo',                          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 176, isSystem: true },
	{ id: 'reg-country-to',      label: 'Tonga',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 177, isSystem: true },
	{ id: 'reg-country-tt',      label: 'Trinidad and Tobago',           treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 178, isSystem: true },
	{ id: 'reg-country-tn',      label: 'Tunisia',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 179, isSystem: true },
	{ id: 'reg-country-tr',      label: 'Türkiye',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 180, isSystem: true },
	{ id: 'reg-country-tm',      label: 'Turkmenistan',                  treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 181, isSystem: true },
	{ id: 'reg-country-tv',      label: 'Tuvalu',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 182, isSystem: true },
	{ id: 'reg-country-ug',      label: 'Uganda',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 183, isSystem: true },
	{ id: 'reg-country-ua',      label: 'Ukraine',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 184, isSystem: true },
	{ id: 'reg-country-ae',      label: 'United Arab Emirates',          treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 185, isSystem: true },
	{ id: 'reg-country-gb',      label: 'United Kingdom',                treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 186, isSystem: true },
	{ id: 'reg-country-us',      label: 'United States',                 treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 187, isSystem: true },
	{ id: 'reg-country-uy',      label: 'Uruguay',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 188, isSystem: true },
	{ id: 'reg-country-uz',      label: 'Uzbekistan',                    treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 189, isSystem: true },
	{ id: 'reg-country-vu',      label: 'Vanuatu',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 190, isSystem: true },
	{ id: 'reg-country-va',      label: 'Vatican City',                  treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 191, isSystem: true },
	{ id: 'reg-country-ve',      label: 'Venezuela',                     treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 192, isSystem: true },
	{ id: 'reg-country-vn',      label: 'Vietnam',                       treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 193, isSystem: true },
	{ id: 'reg-country-ye',      label: 'Yemen',                         treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 194, isSystem: true },
	{ id: 'reg-country-zm',      label: 'Zambia',                        treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 195, isSystem: true },
	{ id: 'reg-country-zw',      label: 'Zimbabwe',                      treeId: 'region', parentId: 'reg-country-sovereign', depth: 2, order: 196, isSystem: true },

	// Territories & Dependencies (ISO 3166-1 — inhabited, non-sovereign)
	{ id: 'reg-country-territory',  label: 'Territories & Dependencies', treeId: 'region', parentId: 'reg-country',          depth: 1, order: 1, isSystem: true },
	{ id: 'reg-country-ai',      label: 'Anguilla',                      treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 0,  isSystem: true },
	{ id: 'reg-country-as',      label: 'American Samoa',                treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 1,  isSystem: true },
	{ id: 'reg-country-aw',      label: 'Aruba',                         treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 2,  isSystem: true },
	{ id: 'reg-country-ax',      label: 'Åland Islands',                 treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 3,  isSystem: true },
	{ id: 'reg-country-bl',      label: 'Saint Barthélemy',              treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 4,  isSystem: true },
	{ id: 'reg-country-bm',      label: 'Bermuda',                       treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 5,  isSystem: true },
	{ id: 'reg-country-bq',      label: 'Bonaire, Sint Eustatius & Saba', treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 6,  isSystem: true },
	{ id: 'reg-country-cc',      label: 'Cocos (Keeling) Islands',       treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 7,  isSystem: true },
	{ id: 'reg-country-ck',      label: 'Cook Islands',                  treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 8,  isSystem: true },
	{ id: 'reg-country-cw',      label: 'Curaçao',                       treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 9,  isSystem: true },
	{ id: 'reg-country-cx',      label: 'Christmas Island',              treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 10, isSystem: true },
	{ id: 'reg-country-eh',      label: 'Western Sahara',                treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 11, isSystem: true },
	{ id: 'reg-country-fk',      label: 'Falkland Islands',              treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 12, isSystem: true },
	{ id: 'reg-country-fo',      label: 'Faroe Islands',                 treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 13, isSystem: true },
	{ id: 'reg-country-gf',      label: 'French Guiana',                 treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 14, isSystem: true },
	{ id: 'reg-country-gg',      label: 'Guernsey',                      treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 15, isSystem: true },
	{ id: 'reg-country-gi',      label: 'Gibraltar',                     treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 16, isSystem: true },
	{ id: 'reg-country-gl',      label: 'Greenland',                     treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 17, isSystem: true },
	{ id: 'reg-country-gp',      label: 'Guadeloupe',                    treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 18, isSystem: true },
	{ id: 'reg-country-gu',      label: 'Guam',                          treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 19, isSystem: true },
	{ id: 'reg-country-hk',      label: 'Hong Kong',                     treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 20, isSystem: true },
	{ id: 'reg-country-im',      label: 'Isle of Man',                   treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 21, isSystem: true },
	{ id: 'reg-country-je',      label: 'Jersey',                        treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 22, isSystem: true },
	{ id: 'reg-country-ky',      label: 'Cayman Islands',                treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 23, isSystem: true },
	{ id: 'reg-country-mf',      label: 'Saint Martin',                  treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 24, isSystem: true },
	{ id: 'reg-country-mo',      label: 'Macao',                         treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 25, isSystem: true },
	{ id: 'reg-country-mp',      label: 'Northern Mariana Islands',      treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 26, isSystem: true },
	{ id: 'reg-country-mq',      label: 'Martinique',                    treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 27, isSystem: true },
	{ id: 'reg-country-ms',      label: 'Montserrat',                    treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 28, isSystem: true },
	{ id: 'reg-country-nc',      label: 'New Caledonia',                 treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 29, isSystem: true },
	{ id: 'reg-country-nf',      label: 'Norfolk Island',                treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 30, isSystem: true },
	{ id: 'reg-country-nu',      label: 'Niue',                          treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 31, isSystem: true },
	{ id: 'reg-country-pf',      label: 'French Polynesia',              treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 32, isSystem: true },
	{ id: 'reg-country-pm',      label: 'Saint Pierre and Miquelon',     treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 33, isSystem: true },
	{ id: 'reg-country-pn',      label: 'Pitcairn Islands',              treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 34, isSystem: true },
	{ id: 'reg-country-pr',      label: 'Puerto Rico',                   treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 35, isSystem: true },
	{ id: 'reg-country-re',      label: 'Réunion',                       treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 36, isSystem: true },
	{ id: 'reg-country-sh',      label: 'Saint Helena',                  treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 37, isSystem: true },
	{ id: 'reg-country-sj',      label: 'Svalbard and Jan Mayen',        treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 38, isSystem: true },
	{ id: 'reg-country-sx',      label: 'Sint Maarten',                  treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 39, isSystem: true },
	{ id: 'reg-country-tc',      label: 'Turks and Caicos Islands',      treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 40, isSystem: true },
	{ id: 'reg-country-tk',      label: 'Tokelau',                       treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 41, isSystem: true },
	{ id: 'reg-country-vg',      label: 'British Virgin Islands',        treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 42, isSystem: true },
	{ id: 'reg-country-vi',      label: 'U.S. Virgin Islands',           treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 43, isSystem: true },
	{ id: 'reg-country-wf',      label: 'Wallis and Futuna',             treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 44, isSystem: true },
	{ id: 'reg-country-yt',      label: 'Mayotte',                       treeId: 'region', parentId: 'reg-country-territory', depth: 2, order: 45, isSystem: true },
];
