/**
 * Subject Seed — IPTC NewsCodes Media Topics taxonomy.
 *
 * 17 top-level topics with standard subtopics.
 * Reference: https://cv.iptc.org/newscodes/mediatopic/
 */

import type { SeedCategory } from './category-seed.js';

export const subjectSeed: SeedCategory[] = [
	// 01 — Arts, culture, entertainment and media
	{ id: 'aa',                label: 'Arts, Culture & Media',      treeId: 'subject', parentId: null,          depth: 0, order: 0,  isSystem: true },
	{ id: 'aaaaa',         label: 'Visual Arts',                treeId: 'subject', parentId: 'aa',   depth: 1, order: 0,  isSystem: true },
	{ id: 'aaaab',          label: 'Music',                      treeId: 'subject', parentId: 'aa',   depth: 1, order: 1,  isSystem: true },
	{ id: 'aaaac',         label: 'Cinema',                     treeId: 'subject', parentId: 'aa',   depth: 1, order: 2,  isSystem: true },
	{ id: 'aaaad',        label: 'Theatre & Dance',            treeId: 'subject', parentId: 'aa',   depth: 1, order: 3,  isSystem: true },
	{ id: 'aaaae',     label: 'Literature',                 treeId: 'subject', parentId: 'aa',   depth: 1, order: 4,  isSystem: true },
	{ id: 'aaaaf',   label: 'Architecture',               treeId: 'subject', parentId: 'aa',   depth: 1, order: 5,  isSystem: true },
	{ id: 'aaaag',        label: 'Fashion',                    treeId: 'subject', parentId: 'aa',   depth: 1, order: 6,  isSystem: true },
	{ id: 'aaaah',    label: 'Photography',                treeId: 'subject', parentId: 'aa',   depth: 1, order: 7,  isSystem: true },
	{ id: 'aaaai',         label: 'Library & Museum',           treeId: 'subject', parentId: 'aa',   depth: 1, order: 8,  isSystem: true },
	{ id: 'aaaaj',             label: 'Television & Radio',         treeId: 'subject', parentId: 'aa',   depth: 1, order: 9,  isSystem: true },
	{ id: 'aaaak',        label: 'Digital Media',              treeId: 'subject', parentId: 'aa',   depth: 1, order: 10, isSystem: true },
	{ id: 'aaaal',         label: 'Gaming',                     treeId: 'subject', parentId: 'aa',   depth: 1, order: 11, isSystem: true },
	{ id: 'aaaam',       label: 'Cultural Heritage',          treeId: 'subject', parentId: 'aa',   depth: 1, order: 12, isSystem: true },
	{ id: 'aaaan',      label: 'Festivals',                  treeId: 'subject', parentId: 'aa',   depth: 1, order: 13, isSystem: true },

	// 02 — Conflict, war and peace
	{ id: 'ab',            label: 'Conflict, War & Peace',      treeId: 'subject', parentId: null,              depth: 0, order: 1,  isSystem: true },
	{ id: 'abaaa',      label: 'Armed Conflict',             treeId: 'subject', parentId: 'ab',   depth: 1, order: 0,  isSystem: true },
	{ id: 'abaab',      label: 'Civil Unrest',               treeId: 'subject', parentId: 'ab',   depth: 1, order: 1,  isSystem: true },
	{ id: 'abaac',  label: 'Terrorism',                  treeId: 'subject', parentId: 'ab',   depth: 1, order: 2,  isSystem: true },
	{ id: 'abaad',      label: 'Peacekeeping',               treeId: 'subject', parentId: 'ab',   depth: 1, order: 3,  isSystem: true },
	{ id: 'abaae',  label: 'War Crimes',                 treeId: 'subject', parentId: 'ab',   depth: 1, order: 4,  isSystem: true },
	{ id: 'abaaf',  label: 'Guerrilla Activity',         treeId: 'subject', parentId: 'ab',   depth: 1, order: 5,  isSystem: true },
	{ id: 'abaag',   label: 'Refugees & Displaced',       treeId: 'subject', parentId: 'ab',   depth: 1, order: 6,  isSystem: true },
	{ id: 'abaah',  label: 'Ceasefire & Peace Process',  treeId: 'subject', parentId: 'ab',   depth: 1, order: 7,  isSystem: true },
	{ id: 'abaai',   label: 'Military',                   treeId: 'subject', parentId: 'ab',   depth: 1, order: 8,  isSystem: true },

	// 03 — Crime, law and justice
	{ id: 'ac',               label: 'Crime, Law & Justice',       treeId: 'subject', parentId: null,            depth: 0, order: 2,  isSystem: true },
	{ id: 'acaaa',         label: 'Crime',                      treeId: 'subject', parentId: 'ac',    depth: 1, order: 0,  isSystem: true },
	{ id: 'acaab',     label: 'Organized Crime',            treeId: 'subject', parentId: 'ac',    depth: 1, order: 1,  isSystem: true },
	{ id: 'acaac',     label: 'Judiciary',                  treeId: 'subject', parentId: 'ac',    depth: 1, order: 2,  isSystem: true },
	{ id: 'acaad',        label: 'Police',                     treeId: 'subject', parentId: 'ac',    depth: 1, order: 3,  isSystem: true },
	{ id: 'acaae',   label: 'Legislation',                treeId: 'subject', parentId: 'ac',    depth: 1, order: 4,  isSystem: true },
	{ id: 'acaaf',         label: 'Cybercrime',                 treeId: 'subject', parentId: 'ac',    depth: 1, order: 5,  isSystem: true },
	{ id: 'acaag',         label: 'Drug Trafficking',           treeId: 'subject', parentId: 'ac',    depth: 1, order: 6,  isSystem: true },
	{ id: 'acaah',         label: 'Fraud & Corruption',         treeId: 'subject', parentId: 'ac',    depth: 1, order: 7,  isSystem: true },
	{ id: 'acaai',        label: 'Prison',                     treeId: 'subject', parentId: 'ac',    depth: 1, order: 8,  isSystem: true },
	{ id: 'acaaj',        label: 'Human Rights',               treeId: 'subject', parentId: 'ac',    depth: 1, order: 9,  isSystem: true },

	// 04 — Disaster, accident and emergency incident
	{ id: 'ad',            label: 'Disaster & Emergency',       treeId: 'subject', parentId: null,               depth: 0, order: 3,  isSystem: true },
	{ id: 'adaaa',    label: 'Natural Disaster',           treeId: 'subject', parentId: 'ad',    depth: 1, order: 0,  isSystem: true },
	{ id: 'adaab', label: 'Earthquake',                 treeId: 'subject', parentId: 'ad',    depth: 1, order: 1,  isSystem: true },
	{ id: 'adaac',      label: 'Flood',                      treeId: 'subject', parentId: 'ad',    depth: 1, order: 2,  isSystem: true },
	{ id: 'adaad',       label: 'Fire',                       treeId: 'subject', parentId: 'ad',    depth: 1, order: 3,  isSystem: true },
	{ id: 'adaae',    label: 'Volcanic Eruption',          treeId: 'subject', parentId: 'ad',    depth: 1, order: 4,  isSystem: true },
	{ id: 'adaaf',    label: 'Drought',                    treeId: 'subject', parentId: 'ad',    depth: 1, order: 5,  isSystem: true },
	{ id: 'adaag', label: 'Industrial Accident',        treeId: 'subject', parentId: 'ad',    depth: 1, order: 6,  isSystem: true },
	{ id: 'adaah',  label: 'Transport Accident',         treeId: 'subject', parentId: 'ad',    depth: 1, order: 7,  isSystem: true },
	{ id: 'adaai',     label: 'Famine',                     treeId: 'subject', parentId: 'ad',    depth: 1, order: 8,  isSystem: true },
	{ id: 'adaaj',   label: 'Epidemic & Pandemic',        treeId: 'subject', parentId: 'ad',    depth: 1, order: 9,  isSystem: true },
	{ id: 'adaak',     label: 'Rescue & Recovery',          treeId: 'subject', parentId: 'ad',    depth: 1, order: 10, isSystem: true },

	// 05 — Economy, business and finance
	{ id: 'ae',             label: 'Economy & Finance',          treeId: 'subject', parentId: null,              depth: 0, order: 4,  isSystem: true },
	{ id: 'aeaaa',       label: 'Macroeconomics',             treeId: 'subject', parentId: 'ae',    depth: 1, order: 0,  isSystem: true },
	{ id: 'aeaab',     label: 'Markets & Exchanges',        treeId: 'subject', parentId: 'ae',    depth: 1, order: 1,  isSystem: true },
	{ id: 'aeaac',    label: 'Business & Industry',        treeId: 'subject', parentId: 'ae',    depth: 1, order: 2,  isSystem: true },
	{ id: 'aeaad',     label: 'Banking',                    treeId: 'subject', parentId: 'ae',    depth: 1, order: 3,  isSystem: true },
	{ id: 'aeaae',       label: 'International Trade',        treeId: 'subject', parentId: 'ae',    depth: 1, order: 4,  isSystem: true },
	{ id: 'aeaaf', label: 'Agriculture',                treeId: 'subject', parentId: 'ae',    depth: 1, order: 5,  isSystem: true },
	{ id: 'aeaag',      label: 'Energy',                     treeId: 'subject', parentId: 'ae',    depth: 1, order: 6,  isSystem: true },
	{ id: 'aeaah',  label: 'Real Estate',                treeId: 'subject', parentId: 'ae',    depth: 1, order: 7,  isSystem: true },
	{ id: 'aeaai',      label: 'Cryptocurrency',             treeId: 'subject', parentId: 'ae',    depth: 1, order: 8,  isSystem: true },
	{ id: 'aeaaj',    label: 'Startups',                   treeId: 'subject', parentId: 'ae',    depth: 1, order: 9,  isSystem: true },
	{ id: 'aeaak',     label: 'Tourism & Hospitality',      treeId: 'subject', parentId: 'ae',    depth: 1, order: 10, isSystem: true },

	// 06 — Education
	{ id: 'af',            label: 'Education',                 treeId: 'subject', parentId: null,                depth: 0, order: 5,  isSystem: true },
	{ id: 'afaaa',    label: 'Primary Education',         treeId: 'subject', parentId: 'af',   depth: 1, order: 0,  isSystem: true },
	{ id: 'afaab',  label: 'Secondary Education',       treeId: 'subject', parentId: 'af',   depth: 1, order: 1,  isSystem: true },
	{ id: 'afaac',     label: 'Higher Education',          treeId: 'subject', parentId: 'af',   depth: 1, order: 2,  isSystem: true },
	{ id: 'afaad',      label: 'Adult Education',           treeId: 'subject', parentId: 'af',   depth: 1, order: 3,  isSystem: true },
	{ id: 'afaae', label: 'Vocational Training',       treeId: 'subject', parentId: 'af',   depth: 1, order: 4,  isSystem: true },
	{ id: 'afaaf',     label: 'Educational Policy',        treeId: 'subject', parentId: 'af',   depth: 1, order: 5,  isSystem: true },
	{ id: 'afaag',   label: 'Research & Development',    treeId: 'subject', parentId: 'af',   depth: 1, order: 6,  isSystem: true },

	// 07 — Environment
	{ id: 'ag',           label: 'Environment',              treeId: 'subject', parentId: null,                   depth: 0, order: 6,  isSystem: true },
	{ id: 'agaaa',   label: 'Climate Change',           treeId: 'subject', parentId: 'ag',    depth: 1, order: 0,  isSystem: true },
	{ id: 'agaab',   label: 'Conservation',             treeId: 'subject', parentId: 'ag',    depth: 1, order: 1,  isSystem: true },
	{ id: 'agaac', label: 'Pollution',                treeId: 'subject', parentId: 'ag',    depth: 1, order: 2,  isSystem: true },
	{ id: 'agaad',    label: 'Biodiversity',             treeId: 'subject', parentId: 'ag',    depth: 1, order: 3,  isSystem: true },
	{ id: 'agaae',  label: 'Deforestation',            treeId: 'subject', parentId: 'ag',    depth: 1, order: 4,  isSystem: true },
	{ id: 'agaaf', label: 'Renewable Energy',         treeId: 'subject', parentId: 'ag',    depth: 1, order: 5,  isSystem: true },
	{ id: 'agaag',     label: 'Waste Management',         treeId: 'subject', parentId: 'ag',    depth: 1, order: 6,  isSystem: true },
	{ id: 'agaah', label: 'Natural Resources',        treeId: 'subject', parentId: 'ag',    depth: 1, order: 7,  isSystem: true },
	{ id: 'agaai',    label: 'Environmental Policy',     treeId: 'subject', parentId: 'ag',    depth: 1, order: 8,  isSystem: true },
	{ id: 'agaaj',   label: 'Sustainability',           treeId: 'subject', parentId: 'ag',    depth: 1, order: 9,  isSystem: true },

	// 08 — Health
	{ id: 'ah',              label: 'Health',                     treeId: 'subject', parentId: null,              depth: 0, order: 7,  isSystem: true },
	{ id: 'ahaaa',       label: 'Public Health',              treeId: 'subject', parentId: 'ah',    depth: 1, order: 0,  isSystem: true },
	{ id: 'ahaab',     label: 'Diseases & Conditions',      treeId: 'subject', parentId: 'ah',    depth: 1, order: 1,  isSystem: true },
	{ id: 'ahaac',       label: 'Healthcare System',          treeId: 'subject', parentId: 'ah',    depth: 1, order: 2,  isSystem: true },
	{ id: 'ahaad',       label: 'Mental Health',              treeId: 'subject', parentId: 'ah',    depth: 1, order: 3,  isSystem: true },
	{ id: 'ahaae',    label: 'Nutrition',                  treeId: 'subject', parentId: 'ah',    depth: 1, order: 4,  isSystem: true },
	{ id: 'ahaaf',       label: 'Pharmaceutical',             treeId: 'subject', parentId: 'ah',    depth: 1, order: 5,  isSystem: true },
	{ id: 'ahaag',     label: 'Medical Research',           treeId: 'subject', parentId: 'ah',    depth: 1, order: 6,  isSystem: true },
	{ id: 'ahaah',      label: 'Fitness & Wellness',         treeId: 'subject', parentId: 'ah',    depth: 1, order: 7,  isSystem: true },
	{ id: 'ahaai',     label: 'Epidemics',                  treeId: 'subject', parentId: 'ah',    depth: 1, order: 8,  isSystem: true },

	// 09 — Human interest
	{ id: 'ai',               label: 'Human Interest',             treeId: 'subject', parentId: null,             depth: 0, order: 8,  isSystem: true },
	{ id: 'aiaaa',        label: 'People',                     treeId: 'subject', parentId: 'ai',     depth: 1, order: 0,  isSystem: true },
	{ id: 'aiaab',       label: 'Animals',                    treeId: 'subject', parentId: 'ai',     depth: 1, order: 1,  isSystem: true },
	{ id: 'aiaac',       label: 'Unusual Events',             treeId: 'subject', parentId: 'ai',     depth: 1, order: 2,  isSystem: true },
	{ id: 'aiaad',     label: 'Community',                  treeId: 'subject', parentId: 'ai',     depth: 1, order: 3,  isSystem: true },
	{ id: 'aiaae',        label: 'Awards & Prizes',            treeId: 'subject', parentId: 'ai',     depth: 1, order: 4,  isSystem: true },
	{ id: 'aiaaf',      label: 'Obituary',                   treeId: 'subject', parentId: 'ai',     depth: 1, order: 5,  isSystem: true },

	// 10 — Labour
	{ id: 'aj',              label: 'Labour',                     treeId: 'subject', parentId: null,              depth: 0, order: 9,  isSystem: true },
	{ id: 'ajaaa',   label: 'Employment',                 treeId: 'subject', parentId: 'aj',    depth: 1, order: 0,  isSystem: true },
	{ id: 'ajaab',    label: 'Labour Relations',           treeId: 'subject', parentId: 'aj',    depth: 1, order: 1,  isSystem: true },
	{ id: 'ajaac',       label: 'Unions',                     treeId: 'subject', parentId: 'aj',    depth: 1, order: 2,  isSystem: true },
	{ id: 'ajaad',       label: 'Labour Market',              treeId: 'subject', parentId: 'aj',    depth: 1, order: 3,  isSystem: true },
	{ id: 'ajaae',       label: 'Workplace Safety',           treeId: 'subject', parentId: 'aj',    depth: 1, order: 4,  isSystem: true },
	{ id: 'ajaaf',   label: 'Retirement',                 treeId: 'subject', parentId: 'aj',    depth: 1, order: 5,  isSystem: true },
	{ id: 'ajaag',   label: 'Working Conditions',         treeId: 'subject', parentId: 'aj',    depth: 1, order: 6,  isSystem: true },
	{ id: 'ajaah',       label: 'Strike Action',              treeId: 'subject', parentId: 'aj',    depth: 1, order: 7,  isSystem: true },

	// 11 — Lifestyle and leisure
	{ id: 'ak',           label: 'Lifestyle & Leisure',        treeId: 'subject', parentId: null,                depth: 0, order: 10, isSystem: true },
	{ id: 'akaaa',      label: 'Food & Drink',               treeId: 'subject', parentId: 'ak',    depth: 1, order: 0,  isSystem: true },
	{ id: 'akaab',    label: 'Travel & Tourism',           treeId: 'subject', parentId: 'ak',    depth: 1, order: 1,  isSystem: true },
	{ id: 'akaac',      label: 'Home & Garden',              treeId: 'subject', parentId: 'ak',    depth: 1, order: 2,  isSystem: true },
	{ id: 'akaad',   label: 'Hobbies',                    treeId: 'subject', parentId: 'ak',    depth: 1, order: 3,  isSystem: true },
	{ id: 'akaae',      label: 'Automotive',                 treeId: 'subject', parentId: 'ak',    depth: 1, order: 4,  isSystem: true },
	{ id: 'akaaf',      label: 'Pets',                       treeId: 'subject', parentId: 'ak',    depth: 1, order: 5,  isSystem: true },
	{ id: 'akaag',  label: 'Shopping & Consumer',        treeId: 'subject', parentId: 'ak',    depth: 1, order: 6,  isSystem: true },
	{ id: 'akaah',  label: 'Personal Finance',           treeId: 'subject', parentId: 'ak',    depth: 1, order: 7,  isSystem: true },

	// 12 — Politics
	{ id: 'al',             label: 'Politics',                  treeId: 'subject', parentId: null,                depth: 0, order: 11, isSystem: true },
	{ id: 'alaaa',   label: 'Elections',                  treeId: 'subject', parentId: 'al',    depth: 1, order: 0,  isSystem: true },
	{ id: 'alaab',  label: 'Government',                treeId: 'subject', parentId: 'al',    depth: 1, order: 1,  isSystem: true },
	{ id: 'alaac',     label: 'Political Parties',         treeId: 'subject', parentId: 'al',    depth: 1, order: 2,  isSystem: true },
	{ id: 'alaad',   label: 'Diplomacy',                 treeId: 'subject', parentId: 'al',    depth: 1, order: 3,  isSystem: true },
	{ id: 'alaae',        label: 'International Relations',   treeId: 'subject', parentId: 'al',    depth: 1, order: 4,  isSystem: true },
	{ id: 'alaaf',       label: 'Heads of State',            treeId: 'subject', parentId: 'al',    depth: 1, order: 5,  isSystem: true },
	{ id: 'alaag',  label: 'Parliament',                treeId: 'subject', parentId: 'al',    depth: 1, order: 6,  isSystem: true },
	{ id: 'alaah',       label: 'Local Government',          treeId: 'subject', parentId: 'al',    depth: 1, order: 7,  isSystem: true },
	{ id: 'alaai',      label: 'Political Crisis',          treeId: 'subject', parentId: 'al',    depth: 1, order: 8,  isSystem: true },

	// 13 — Religion
	{ id: 'am',             label: 'Religion',                  treeId: 'subject', parentId: null,                depth: 0, order: 12, isSystem: true },
	{ id: 'amaaa',   label: 'Christianity',              treeId: 'subject', parentId: 'am',    depth: 1, order: 0,  isSystem: true },
	{ id: 'amaab',       label: 'Islam',                     treeId: 'subject', parentId: 'am',    depth: 1, order: 1,  isSystem: true },
	{ id: 'amaac',     label: 'Judaism',                   treeId: 'subject', parentId: 'am',    depth: 1, order: 2,  isSystem: true },
	{ id: 'amaad',    label: 'Buddhism',                  treeId: 'subject', parentId: 'am',    depth: 1, order: 3,  isSystem: true },
	{ id: 'amaae',    label: 'Hinduism',                  treeId: 'subject', parentId: 'am',    depth: 1, order: 4,  isSystem: true },
	{ id: 'amaaf',  label: 'Interfaith',                treeId: 'subject', parentId: 'am',    depth: 1, order: 5,  isSystem: true },
	{ id: 'amaag',      label: 'Religious Events',          treeId: 'subject', parentId: 'am',    depth: 1, order: 6,  isSystem: true },
	{ id: 'amaah',     label: 'Religious Leaders',         treeId: 'subject', parentId: 'am',    depth: 1, order: 7,  isSystem: true },

	// 14 — Science and technology
	{ id: 'an',             label: 'Science & Technology',       treeId: 'subject', parentId: null,               depth: 0, order: 13, isSystem: true },
	{ id: 'anaaa',          label: 'Computer Science',           treeId: 'subject', parentId: 'an',    depth: 1, order: 0,  isSystem: true },
	{ id: 'anaab',          label: 'Artificial Intelligence',    treeId: 'subject', parentId: 'an',    depth: 1, order: 1,  isSystem: true },
	{ id: 'anaac',       label: 'Space Exploration',          treeId: 'subject', parentId: 'an',    depth: 1, order: 2,  isSystem: true },
	{ id: 'anaad',     label: 'Physics',                    treeId: 'subject', parentId: 'an',    depth: 1, order: 3,  isSystem: true },
	{ id: 'anaae',     label: 'Biology',                    treeId: 'subject', parentId: 'an',    depth: 1, order: 4,  isSystem: true },
	{ id: 'anaaf',   label: 'Chemistry',                  treeId: 'subject', parentId: 'an',    depth: 1, order: 5,  isSystem: true },
	{ id: 'anaag',        label: 'Mathematics',                treeId: 'subject', parentId: 'an',    depth: 1, order: 6,  isSystem: true },
	{ id: 'anaah', label: 'Engineering',                treeId: 'subject', parentId: 'an',    depth: 1, order: 7,  isSystem: true },
	{ id: 'anaai',     label: 'Biotechnology',              treeId: 'subject', parentId: 'an',    depth: 1, order: 8,  isSystem: true },
	{ id: 'anaaj',    label: 'Nanotechnology',             treeId: 'subject', parentId: 'an',    depth: 1, order: 9,  isSystem: true },
	{ id: 'anaak',    label: 'Cybersecurity',              treeId: 'subject', parentId: 'an',    depth: 1, order: 10, isSystem: true },
	{ id: 'anaal',     label: 'Telecommunications',         treeId: 'subject', parentId: 'an',    depth: 1, order: 11, isSystem: true },

	// 15 — Society
	{ id: 'ao',              label: 'Society',                   treeId: 'subject', parentId: null,               depth: 0, order: 14, isSystem: true },
	{ id: 'aoaaa', label: 'Demographics',              treeId: 'subject', parentId: 'ao',    depth: 1, order: 0,  isSystem: true },
	{ id: 'aoaab',  label: 'Immigration',               treeId: 'subject', parentId: 'ao',    depth: 1, order: 1,  isSystem: true },
	{ id: 'aoaac',       label: 'Social Issues',             treeId: 'subject', parentId: 'ao',    depth: 1, order: 2,  isSystem: true },
	{ id: 'aoaad',       label: 'Family',                    treeId: 'subject', parentId: 'ao',    depth: 1, order: 3,  isSystem: true },
	{ id: 'aoaae',   label: 'Minorities',                treeId: 'subject', parentId: 'ao',    depth: 1, order: 4,  isSystem: true },
	{ id: 'aoaaf',       label: 'Gender Issues',             treeId: 'subject', parentId: 'ao',    depth: 1, order: 5,  isSystem: true },
	{ id: 'aoaag',      label: 'Housing',                   treeId: 'subject', parentId: 'ao',    depth: 1, order: 6,  isSystem: true },
	{ id: 'aoaah',      label: 'Poverty',                   treeId: 'subject', parentId: 'ao',    depth: 1, order: 7,  isSystem: true },
	{ id: 'aoaai',     label: 'Social Services',           treeId: 'subject', parentId: 'ao',    depth: 1, order: 8,  isSystem: true },
	{ id: 'aoaaj',        label: 'Urbanization',              treeId: 'subject', parentId: 'ao',    depth: 1, order: 9,  isSystem: true },

	// 16 — Sport
	{ id: 'ap',               label: 'Sport',                      treeId: 'subject', parentId: null,              depth: 0, order: 15, isSystem: true },
	{ id: 'apaaa',      label: 'Football',                   treeId: 'subject', parentId: 'ap',     depth: 1, order: 0,  isSystem: true },
	{ id: 'apaab',    label: 'Basketball',                 treeId: 'subject', parentId: 'ap',     depth: 1, order: 1,  isSystem: true },
	{ id: 'apaac',        label: 'Tennis',                     treeId: 'subject', parentId: 'ap',     depth: 1, order: 2,  isSystem: true },
	{ id: 'apaad',     label: 'Athletics',                  treeId: 'subject', parentId: 'ap',     depth: 1, order: 3,  isSystem: true },
	{ id: 'apaae',    label: 'Motorsport',                 treeId: 'subject', parentId: 'ap',     depth: 1, order: 4,  isSystem: true },
	{ id: 'apaaf',      label: 'Swimming',                   treeId: 'subject', parentId: 'ap',     depth: 1, order: 5,  isSystem: true },
	{ id: 'apaag',       label: 'Cycling',                    treeId: 'subject', parentId: 'ap',     depth: 1, order: 6,  isSystem: true },
	{ id: 'apaah',        label: 'Boxing & MMA',               treeId: 'subject', parentId: 'ap',     depth: 1, order: 7,  isSystem: true },
	{ id: 'apaai',          label: 'Golf',                       treeId: 'subject', parentId: 'ap',     depth: 1, order: 8,  isSystem: true },
	{ id: 'apaaj',         label: 'Rugby',                      treeId: 'subject', parentId: 'ap',     depth: 1, order: 9,  isSystem: true },
	{ id: 'apaak',       label: 'Cricket',                    treeId: 'subject', parentId: 'ap',     depth: 1, order: 10, isSystem: true },
	{ id: 'apaal',      label: 'Baseball',                   treeId: 'subject', parentId: 'ap',     depth: 1, order: 11, isSystem: true },
	{ id: 'apaam',        label: 'Hockey',                     treeId: 'subject', parentId: 'ap',     depth: 1, order: 12, isSystem: true },
	{ id: 'apaan',    label: 'Volleyball',                 treeId: 'subject', parentId: 'ap',     depth: 1, order: 13, isSystem: true },
	{ id: 'apaao',       label: 'E-sports',                   treeId: 'subject', parentId: 'ap',     depth: 1, order: 14, isSystem: true },
	{ id: 'apaap',      label: 'Olympic Games',              treeId: 'subject', parentId: 'ap',     depth: 1, order: 15, isSystem: true },

	// 17 — Weather
	{ id: 'aq',             label: 'Weather',                    treeId: 'subject', parentId: null,               depth: 0, order: 16, isSystem: true },
	{ id: 'aqaaa',    label: 'Forecast',                   treeId: 'subject', parentId: 'aq',    depth: 1, order: 0,  isSystem: true },
	{ id: 'aqaab',      label: 'Severe Weather',             treeId: 'subject', parentId: 'aq',    depth: 1, order: 1,  isSystem: true },
	{ id: 'aqaac',       label: 'Storm',                      treeId: 'subject', parentId: 'aq',    depth: 1, order: 2,  isSystem: true },
	{ id: 'aqaad',    label: 'Tropical Storm',             treeId: 'subject', parentId: 'aq',    depth: 1, order: 3,  isSystem: true },
	{ id: 'aqaae',     label: 'Tornado',                    treeId: 'subject', parentId: 'aq',    depth: 1, order: 4,  isSystem: true },
	{ id: 'aqaaf',    label: 'Heat Wave',                  treeId: 'subject', parentId: 'aq',    depth: 1, order: 5,  isSystem: true },
	{ id: 'aqaag',    label: 'Cold Wave',                  treeId: 'subject', parentId: 'aq',    depth: 1, order: 6,  isSystem: true },
	{ id: 'aqaah',     label: 'Climate Data',               treeId: 'subject', parentId: 'aq',    depth: 1, order: 7,  isSystem: true },
];
